// This file is auto-generated by the Retab oagen emitter. Do not edit by hand.

import { z } from 'zod';
export interface EndsWithCondition {
  /** @default "ends_with" */
  kind: 'ends_with';
  expected: string;
}

export interface EndsWithConditionResponse {
  kind: 'ends_with';
  expected: string;
}

export const ZEndsWithCondition = z.object({
  kind: z.literal('ends_with'),
  expected: z.string(),
}) as z.ZodType<EndsWithCondition>;

export function deserializeEndsWithCondition(wire: EndsWithConditionResponse): EndsWithCondition {
  return {
    kind: wire['kind'],
    expected: wire['expected'],
  };
}
