// This file is auto-generated by the Retab oagen emitter. Do not edit by hand.

import { z } from 'zod';
import type { AssertionSchemaDep, AssertionSchemaDepResponse } from './assertion-schema-dep.interface.js';
import { ZAssertionSchemaDep, deserializeAssertionSchemaDep } from './assertion-schema-dep.interface.js';
import type { AssertionSpec, AssertionSpecResponse } from './assertion-spec.interface.js';
import { ZAssertionSpec, deserializeAssertionSpec } from './assertion-spec.interface.js';
import type { LatestBlockTestRunSummary, LatestBlockTestRunSummaryResponse } from './latest-block-test-run-summary.interface.js';
import { ZLatestBlockTestRunSummary, deserializeLatestBlockTestRunSummary } from './latest-block-test-run-summary.interface.js';
import type { ManualWorkflowTestSource, ManualWorkflowTestSourceResponse } from '../../../workflows/tests/results/interfaces/manual-workflow-test-source.interface.js';
import { ZManualWorkflowTestSource, deserializeManualWorkflowTestSource } from '../../../workflows/tests/results/interfaces/manual-workflow-test-source.interface.js';
import type { RunStepWorkflowTestSource, RunStepWorkflowTestSourceResponse } from '../../../workflows/tests/results/interfaces/run-step-workflow-test-source.interface.js';
import { ZRunStepWorkflowTestSource, deserializeRunStepWorkflowTestSource } from '../../../workflows/tests/results/interfaces/run-step-workflow-test-source.interface.js';
import type { WorkflowTestBlockTarget, WorkflowTestBlockTargetResponse } from '../../../workflows/tests/runs/interfaces/workflow-test-block-target.interface.js';
import { ZWorkflowTestBlockTarget, deserializeWorkflowTestBlockTarget } from '../../../workflows/tests/runs/interfaces/workflow-test-block-target.interface.js';
import type { AssertionDriftStatus } from './assertion-drift-status.interface.js';
import { ZAssertionDriftStatus } from './assertion-drift-status.interface.js';
import type { WorkflowTestSchemaDrift } from './workflow-test-schema-drift.interface.js';
import { ZWorkflowTestSchemaDrift } from './workflow-test-schema-drift.interface.js';

export interface WorkflowTest {
  id: string;
  workflowId: string;
  target: WorkflowTestBlockTarget;
  source: ManualWorkflowTestSource | RunStepWorkflowTestSource;
  name?: string | null;
  assertion?: AssertionSpec | null;
  assertionSchemaDep?: AssertionSchemaDep | null;
  assertionDriftStatus?: AssertionDriftStatus | null;
  /** @default "unknown" */
  schemaDrift?: WorkflowTestSchemaDrift;
  schemaDriftDetail?: string | null;
  /** @default "valid" */
  validationStatus?: string;
  validationIssues?: unknown[];
  latestRunSummary?: LatestBlockTestRunSummary | null;
  latestPassingRunSummary?: LatestBlockTestRunSummary | null;
  latestFailingRunSummary?: LatestBlockTestRunSummary | null;
  createdAt?: Date;
  updatedAt?: Date;
}

export interface WorkflowTestResponse {
  id: string;
  workflow_id: string;
  target: WorkflowTestBlockTargetResponse;
  source: ManualWorkflowTestSourceResponse | RunStepWorkflowTestSourceResponse;
  name?: string | null;
  assertion?: AssertionSpecResponse | null;
  assertion_schema_dep?: AssertionSchemaDepResponse | null;
  assertion_drift_status?: AssertionDriftStatus | null;
  schema_drift?: WorkflowTestSchemaDrift;
  schema_drift_detail?: string | null;
  validation_status?: string;
  validation_issues?: unknown[];
  latest_run_summary?: LatestBlockTestRunSummaryResponse | null;
  latest_passing_run_summary?: LatestBlockTestRunSummaryResponse | null;
  latest_failing_run_summary?: LatestBlockTestRunSummaryResponse | null;
  created_at?: string;
  updated_at?: string;
}

export const ZWorkflowTest = z.object({
  "id": z.string(),
  "workflowId": z.string(),
  "target": ZWorkflowTestBlockTarget,
  "source": z.union([ZManualWorkflowTestSource, ZRunStepWorkflowTestSource]),
  "name": z.string().nullable().optional(),
  "assertion": ZAssertionSpec.nullable().optional(),
  "assertionSchemaDep": ZAssertionSchemaDep.nullable().optional(),
  "assertionDriftStatus": ZAssertionDriftStatus.nullable().optional(),
  "schemaDrift": ZWorkflowTestSchemaDrift.optional(),
  "schemaDriftDetail": z.string().nullable().optional(),
  "validationStatus": z.string().optional(),
  "validationIssues": z.unknown().array().optional(),
  "latestRunSummary": ZLatestBlockTestRunSummary.nullable().optional(),
  "latestPassingRunSummary": ZLatestBlockTestRunSummary.nullable().optional(),
  "latestFailingRunSummary": ZLatestBlockTestRunSummary.nullable().optional(),
  "createdAt": z.coerce.date().optional(),
  "updatedAt": z.coerce.date().optional(),
}) as z.ZodType<WorkflowTest>;

export function deserializeWorkflowTest(wire: WorkflowTestResponse): WorkflowTest {
  return {
    id: wire["id"],
    workflowId: wire["workflow_id"],
    target: deserializeWorkflowTestBlockTarget(wire["target"]),
    source: (({ "manual": () => deserializeManualWorkflowTestSource(wire["source"] as ManualWorkflowTestSourceResponse), "run_step": () => deserializeRunStepWorkflowTestSource(wire["source"] as RunStepWorkflowTestSourceResponse) } as Record<string, () => ManualWorkflowTestSource | RunStepWorkflowTestSource>)[(wire["source"] as unknown as Record<string, string>)["type"]]?.() ?? (wire["source"] as unknown as ManualWorkflowTestSource | RunStepWorkflowTestSource)),
    name: wire["name"],
    assertion: wire["assertion"] == null ? (wire["assertion"] as undefined) : (wire["assertion"] == null ? wire["assertion"] : deserializeAssertionSpec(wire["assertion"])),
    assertionSchemaDep: wire["assertion_schema_dep"] == null ? (wire["assertion_schema_dep"] as undefined) : (wire["assertion_schema_dep"] == null ? wire["assertion_schema_dep"] : deserializeAssertionSchemaDep(wire["assertion_schema_dep"])),
    assertionDriftStatus: wire["assertion_drift_status"],
    schemaDrift: wire["schema_drift"],
    schemaDriftDetail: wire["schema_drift_detail"],
    validationStatus: wire["validation_status"],
    validationIssues: wire["validation_issues"],
    latestRunSummary: wire["latest_run_summary"] == null ? (wire["latest_run_summary"] as undefined) : (wire["latest_run_summary"] == null ? wire["latest_run_summary"] : deserializeLatestBlockTestRunSummary(wire["latest_run_summary"])),
    latestPassingRunSummary: wire["latest_passing_run_summary"] == null ? (wire["latest_passing_run_summary"] as undefined) : (wire["latest_passing_run_summary"] == null ? wire["latest_passing_run_summary"] : deserializeLatestBlockTestRunSummary(wire["latest_passing_run_summary"])),
    latestFailingRunSummary: wire["latest_failing_run_summary"] == null ? (wire["latest_failing_run_summary"] as undefined) : (wire["latest_failing_run_summary"] == null ? wire["latest_failing_run_summary"] : deserializeLatestBlockTestRunSummary(wire["latest_failing_run_summary"])),
    createdAt: wire["created_at"] == null ? (wire["created_at"] as undefined) : new Date(wire["created_at"]),
    updatedAt: wire["updated_at"] == null ? (wire["updated_at"] as undefined) : new Date(wire["updated_at"]),
  };
}
