# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module Retab
  class ValidationError < Retab::Types::BaseModel

    HASH_ATTRS = {
      loc: :loc,
      msg: :msg,
      type: :type,
      input: :input,
      ctx: :ctx
    }.freeze

    attr_accessor(
      :loc,
      :msg,
      :type,
      :input,
      :ctx
    )

    def initialize(json)
      super()
      hash = self.class.normalize(json)
      @loc = (hash[:loc] || [])
      @msg = hash[:msg]
      @type = hash[:type]
      @input = hash[:input]
      @ctx = hash[:ctx] || {}
    end
  end
end
