// This file is auto-generated by the Retab oagen emitter. Do not edit by hand.

import { z } from 'zod';

export type ExtractionsStatus =
  | 'pending'
  | 'queued'
  | 'in_progress'
  | 'completed'
  | 'failed'
  | 'cancelled';

export const ZExtractionsStatus = z.enum([
  'pending',
  'queued',
  'in_progress',
  'completed',
  'failed',
  'cancelled',
] as const);
