// This file is auto-generated by the Retab oagen emitter. Do not edit by hand.

import { z } from 'zod';

export type JobsOrder = 'asc' | 'desc';

export const ZJobsOrder = z.enum(['asc', 'desc'] as const);
