// This file is auto-generated by the Retab oagen emitter. Do not edit by hand.

import { z } from 'zod';
/** The step has been created but execution has not started. */
export interface PendingStepLifecycle {
  /** @default "pending" */
  status: 'pending';
}

export interface PendingStepLifecycleResponse {
  status: 'pending';
}

export const ZPendingStepLifecycle = z.object({
  status: z.literal('pending'),
}) as z.ZodType<PendingStepLifecycle>;

export function deserializePendingStepLifecycle(
  wire: PendingStepLifecycleResponse
): PendingStepLifecycle {
  return {
    status: wire['status'],
  };
}
