// This file is auto-generated by the Retab oagen emitter. Do not edit by hand.

import { z } from 'zod';
import type {
  FileRef,
  FileRefResponse,
} from '../../../extractions/interfaces/file-ref.interface.js';
import {
  ZFileRef,
  deserializeFileRef,
  serializeFileRef,
} from '../../../extractions/interfaces/file-ref.interface.js';
import type { PublicHandlePayloadType } from './public-handle-payload-type.interface.js';
import { ZPublicHandlePayloadType } from './public-handle-payload-type.interface.js';

/** Public handle payload exposed by workflow step APIs. */
export interface PublicHandlePayload {
  /** Type of payload */
  type: PublicHandlePayloadType;
  /** For file handles: document reference */
  document?: FileRef | null;
  /**
   * For JSON handles: structured data
   * @default null
   */
  data?: unknown;
}

export interface PublicHandlePayloadResponse {
  type: PublicHandlePayloadType;
  document?: FileRefResponse | null;
  data?: unknown;
}

export const ZPublicHandlePayload = z.object({
  type: ZPublicHandlePayloadType,
  document: ZFileRef.nullable().optional(),
  data: z.unknown().optional(),
}) as z.ZodType<PublicHandlePayload>;

export function deserializePublicHandlePayload(
  wire: PublicHandlePayloadResponse
): PublicHandlePayload {
  return {
    type: wire['type'],
    document:
      wire['document'] == null
        ? (wire['document'] as undefined)
        : wire['document'] == null
          ? wire['document']
          : deserializeFileRef(wire['document']),
    data: wire['data'],
  };
}

export function serializePublicHandlePayload(
  domain: PublicHandlePayload
): PublicHandlePayloadResponse {
  return {
    type: domain['type'],
    document:
      domain['document'] == null
        ? (domain['document'] as undefined)
        : domain['document'] == null
          ? domain['document']
          : serializeFileRef(domain['document']),
    data: domain['data'],
  };
}
