# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require "json"

module Retab
  class Auth
    def initialize(client)
      @client = client
    end

    # Get Auth Status
    # @param request_options [Hash] (see Retab::Types::RequestOptions)
    # @return [Retab::AuthStatus]
    def list_status(request_options: {})
      response = @client.request(
        method: :get,
        path: "/v1/auth/status",
        auth: true,
        request_options: request_options
      )
      result = Retab::AuthStatus.new(response.body)
      result.last_response = Retab::Types::ApiResponse.new(
        http_status: response.code.to_i,
        http_headers: response.each_header.to_h,
        request_id: response["x-request-id"]
      )
      result
    end
  end
end
