# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require "json"

module Retab
  class Edits
    def initialize(client)
      @client = client
    end

    def templates
      @templates ||= Retab::EditTemplates.new(@client)
    end

    # List Edits
    # @param before [String, nil]
    # @param after [String, nil]
    # @param limit [Integer, nil]
    # @param order [Retab::Types::EditsOrder, nil]
    # @param filename [String, nil]
    # @param template_id [String, nil]
    # @param from_date [String, nil]
    # @param to_date [String, nil]
    # @param request_options [Hash] (see Retab::Types::RequestOptions)
    # @return [Retab::PaginatedList<Retab::Edit>]
    def list(
      before: nil,
      after: nil,
      limit: 10,
      order: "desc",
      filename: nil,
      template_id: nil,
      from_date: nil,
      to_date: nil,
      request_options: {}
    )
      params = {
        "before" => before,
        "after" => after,
        "limit" => limit,
        "order" => order,
        "filename" => filename,
        "template_id" => template_id,
        "from_date" => from_date,
        "to_date" => to_date
      }.compact
      response = @client.request(
        method: :get,
        path: "/v1/edits",
        auth: true,
        params: params,
        request_options: request_options
      )
      fetch_next = -> (cursor) {
        list(
          before: before,
          after: cursor,
          limit: limit,
          order: order,
          filename: filename,
          template_id: template_id,
          from_date: from_date,
          to_date: to_date,
          request_options: request_options
        )
      }
      Retab::PaginatedList.from_response(
        response,
        model: Retab::Edit,
        filters: {
          before: before,
          limit: limit,
          order: order,
          filename: filename,
          template_id: template_id,
          from_date: from_date,
          to_date: to_date
        },
        fetch_next: fetch_next
      )
    end

    # Create Edit
    # @param instructions [String] Instructions describing how to fill the form fields.
    # @param document [Retab::MimeData, Pathname, IO, String, Hash, nil] Input document (PDF, DOCX, XLSX, or PPTX). Mutually exclusive with template_id.
    # @param template_id [String, nil] EditTemplate id to fill. When provided, uses the template's pre-defined form fields and empty PDF. Mutually exclusive with document.
    # @param model [String, nil] The model to use for edit inference.
    # @param config [Retab::EditConfig, nil] Edit configuration (rendering options).
    # @param bust_cache [Boolean, nil] If true, skip the LLM cache and force a fresh completion.
    # @param request_options [Hash] (see Retab::Types::RequestOptions)
    # @return [Retab::Edit]
    def create(
      instructions:,
      document: nil,
      template_id: nil,
      model: nil,
      config: nil,
      bust_cache: nil,
      request_options: {}
    )
      document = Retab::MimeData.coerce(document) unless document.nil?
      body = {
        "instructions" => instructions,
        "document" => document,
        "template_id" => template_id,
        "model" => model,
        "config" => config,
        "bust_cache" => bust_cache
      }.compact
      response = @client.request(
        method: :post,
        path: "/v1/edits",
        auth: true,
        body: body,
        request_options: request_options
      )
      result = Retab::Edit.new(response.body)
      result.last_response = Retab::Types::ApiResponse.new(
        http_status: response.code.to_i,
        http_headers: response.each_header.to_h,
        request_id: response["x-request-id"]
      )
      result
    end

    # Get Edit
    # @param edit_id [String]
    # @param request_options [Hash] (see Retab::Types::RequestOptions)
    # @return [Retab::Edit]
    def get(
      edit_id:,
      request_options: {}
    )
      response = @client.request(
        method: :get,
        path: "/v1/edits/#{Retab::Util.encode_path(edit_id)}",
        auth: true,
        request_options: request_options
      )
      result = Retab::Edit.new(response.body)
      result.last_response = Retab::Types::ApiResponse.new(
        http_status: response.code.to_i,
        http_headers: response.each_header.to_h,
        request_id: response["x-request-id"]
      )
      result
    end

    # Delete Edit
    # @param edit_id [String]
    # @param request_options [Hash] (see Retab::Types::RequestOptions)
    # @return [void]
    def delete(
      edit_id:,
      request_options: {}
    )
      @client.request(
        method: :delete,
        path: "/v1/edits/#{Retab::Util.encode_path(edit_id)}",
        auth: true,
        request_options: request_options
      )
      nil
    end
  end
end
