# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require "json"

module Retab
  class Tables
    def initialize(client)
      @client = client
    end

    # Table.List
    # @param request_options [Hash] (see Retab::Types::RequestOptions)
    # @return [Retab::WorkflowTableListResponse]
    def list(request_options: {})
      response = @client.request(
        method: :get,
        path: "/v1/tables",
        auth: true,
        request_options: request_options
      )
      result = Retab::WorkflowTableListResponse.new(response.body)
      result.last_response = Retab::Types::ApiResponse.new(
        http_status: response.code.to_i,
        http_headers: response.each_header.to_h,
        request_id: response["x-request-id"]
      )
      result
    end

    # Table.Create
    # @param name [String]
    # @param file [String]
    # @param column_schema_overrides [String, nil]
    # @param request_options [Hash] (see Retab::Types::RequestOptions)
    # @return [Retab::WorkflowTableListResponse]
    def create(
      name:,
      file:,
      column_schema_overrides: nil,
      request_options: {}
    )
      body = {
        "name" => name,
        "file" => file,
        "column_schema_overrides" => column_schema_overrides
      }.compact
      response = @client.request(
        method: :post,
        path: "/v1/tables",
        auth: true,
        body: body,
        request_options: request_options
      )
      result = Retab::WorkflowTableListResponse.new(response.body)
      result.last_response = Retab::Types::ApiResponse.new(
        http_status: response.code.to_i,
        http_headers: response.each_header.to_h,
        request_id: response["x-request-id"]
      )
      result
    end

    # Table.Get
    # @param table_id [String]
    # @param request_options [Hash] (see Retab::Types::RequestOptions)
    # @return [Retab::WorkflowTableResponse]
    def get(
      table_id:,
      request_options: {}
    )
      response = @client.request(
        method: :get,
        path: "/v1/tables/#{Retab::Util.encode_path(table_id)}",
        auth: true,
        request_options: request_options
      )
      result = Retab::WorkflowTableResponse.new(response.body)
      result.last_response = Retab::Types::ApiResponse.new(
        http_status: response.code.to_i,
        http_headers: response.each_header.to_h,
        request_id: response["x-request-id"]
      )
      result
    end

    # Table.Replace
    # @param table_id [String]
    # @param file [String]
    # @param column_schema_overrides [String, nil]
    # @param request_options [Hash] (see Retab::Types::RequestOptions)
    # @return [Retab::WorkflowTableListResponse]
    def replace(
      table_id:,
      file:,
      column_schema_overrides: nil,
      request_options: {}
    )
      body = {
        "file" => file,
        "column_schema_overrides" => column_schema_overrides
      }.compact
      response = @client.request(
        method: :put,
        path: "/v1/tables/#{Retab::Util.encode_path(table_id)}",
        auth: true,
        body: body,
        request_options: request_options
      )
      result = Retab::WorkflowTableListResponse.new(response.body)
      result.last_response = Retab::Types::ApiResponse.new(
        http_status: response.code.to_i,
        http_headers: response.each_header.to_h,
        request_id: response["x-request-id"]
      )
      result
    end

    # Table.Update
    # @param table_id [String]
    # @param name [String, nil]
    # @param metadata [Hash{String => Object}, nil]
    # @param request_options [Hash] (see Retab::Types::RequestOptions)
    # @return [Retab::WorkflowTableListResponse]
    def update_table(
      table_id:,
      name: nil,
      metadata: nil,
      request_options: {}
    )
      body = {
        "name" => name,
        "metadata" => metadata
      }.compact
      response = @client.request(
        method: :patch,
        path: "/v1/tables/#{Retab::Util.encode_path(table_id)}",
        auth: true,
        body: body,
        request_options: request_options
      )
      result = Retab::WorkflowTableListResponse.new(response.body)
      result.last_response = Retab::Types::ApiResponse.new(
        http_status: response.code.to_i,
        http_headers: response.each_header.to_h,
        request_id: response["x-request-id"]
      )
      result
    end

    # Table.Delete
    # @param table_id [String]
    # @param request_options [Hash] (see Retab::Types::RequestOptions)
    # @return [void]
    def delete(
      table_id:,
      request_options: {}
    )
      @client.request(
        method: :delete,
        path: "/v1/tables/#{Retab::Util.encode_path(table_id)}",
        auth: true,
        request_options: request_options
      )
      nil
    end

    # Table.Download
    # @param table_id [String]
    # @param request_options [Hash] (see Retab::Types::RequestOptions)
    # @return [String]
    def download(
      table_id:,
      request_options: {}
    )
      response = @client.request(
        method: :get,
        path: "/v1/tables/#{Retab::Util.encode_path(table_id)}/download",
        auth: true,
        request_options: request_options
      )
      JSON.parse(response.body)
    end

    # Table.Get Profile
    # @param table_id [String]
    # @param select [Array<String>, nil]
    # @param request_options [Hash] (see Retab::Types::RequestOptions)
    # @return [Retab::WorkflowTableProfileResponse]
    def profile(
      table_id:,
      select: nil,
      request_options: {}
    )
      params = {
        "select" => select
      }.compact
      response = @client.request(
        method: :get,
        path: "/v1/tables/#{Retab::Util.encode_path(table_id)}/profile",
        auth: true,
        params: params,
        request_options: request_options
      )
      result = Retab::WorkflowTableProfileResponse.new(response.body)
      result.last_response = Retab::Types::ApiResponse.new(
        http_status: response.code.to_i,
        http_headers: response.each_header.to_h,
        request_id: response["x-request-id"]
      )
      result
    end

    # Table.Query
    # @param table_id [String]
    # @param filters [Array<Retab::WorkflowTableFilterRule>, nil]
    # @param search [Retab::WorkflowTableSearchRequest, nil]
    # @param case_sensitive [Boolean, nil]
    # @param select [Array<String>, nil]
    # @param distinct [Retab::WorkflowTableDistinctRequest, nil]
    # @param group_by [Array<String>, nil]
    # @param aggregations [Array<Retab::WorkflowTableAggregationRequest>, nil]
    # @param sort [Array<Retab::WorkflowTableSortRule>, nil]
    # @param sample [Retab::WorkflowTableSampleRequest, nil]
    # @param tail [Retab::WorkflowTableTailRequest, nil]
    # @param count_only [Boolean, nil]
    # @param include_explain [Boolean, nil]
    # @param sort_column [String, nil]
    # @param sort_direction [Retab::Types::WorkflowTableSortDirection, nil]
    # @param viewer_mode [String, nil]
    # @param offset [Integer, nil]
    # @param limit [Integer, nil]
    # @param request_options [Hash] (see Retab::Types::RequestOptions)
    # @return [Retab::WorkflowTableRowsResponse]
    def query(
      table_id:,
      filters: nil,
      search: nil,
      case_sensitive: nil,
      select: nil,
      distinct: nil,
      group_by: nil,
      aggregations: nil,
      sort: nil,
      sample: nil,
      tail: nil,
      count_only: nil,
      include_explain: nil,
      sort_column: nil,
      sort_direction: nil,
      viewer_mode: nil,
      offset: nil,
      limit: nil,
      request_options: {}
    )
      body = {
        "filters" => filters,
        "search" => search,
        "case_sensitive" => case_sensitive,
        "select" => select,
        "distinct" => distinct,
        "group_by" => group_by,
        "aggregations" => aggregations,
        "sort" => sort,
        "sample" => sample,
        "tail" => tail,
        "count_only" => count_only,
        "include_explain" => include_explain,
        "sort_column" => sort_column,
        "sort_direction" => sort_direction,
        "viewer_mode" => viewer_mode,
        "offset" => offset,
        "limit" => limit
      }.compact
      response = @client.request(
        method: :post,
        path: "/v1/tables/#{Retab::Util.encode_path(table_id)}/query",
        auth: true,
        body: body,
        request_options: request_options
      )
      result = Retab::WorkflowTableRowsResponse.new(response.body)
      result.last_response = Retab::Types::ApiResponse.new(
        http_status: response.code.to_i,
        http_headers: response.each_header.to_h,
        request_id: response["x-request-id"]
      )
      result
    end

    # Table.Get Schema
    # @param table_id [String]
    # @param request_options [Hash] (see Retab::Types::RequestOptions)
    # @return [Retab::WorkflowTableSchemaResponse]
    def schema(
      table_id:,
      request_options: {}
    )
      response = @client.request(
        method: :get,
        path: "/v1/tables/#{Retab::Util.encode_path(table_id)}/schema",
        auth: true,
        request_options: request_options
      )
      result = Retab::WorkflowTableSchemaResponse.new(response.body)
      result.last_response = Retab::Types::ApiResponse.new(
        http_status: response.code.to_i,
        http_headers: response.each_header.to_h,
        request_id: response["x-request-id"]
      )
      result
    end

    # Table.Validate
    # @param table_id [String]
    # @param required_columns [Array<String>, nil]
    # @param columns [Hash{String => Retab::WorkflowTableValidationColumnRule}, nil]
    # @param unique [Array<Array<String>>, nil]
    # @param request_options [Hash] (see Retab::Types::RequestOptions)
    # @return [Retab::WorkflowTableValidationResponse]
    def validate(
      table_id:,
      required_columns: nil,
      columns: nil,
      unique: nil,
      request_options: {}
    )
      body = {
        "required_columns" => required_columns,
        "columns" => columns,
        "unique" => unique
      }.compact
      response = @client.request(
        method: :post,
        path: "/v1/tables/#{Retab::Util.encode_path(table_id)}/validate",
        auth: true,
        body: body,
        request_options: request_options
      )
      result = Retab::WorkflowTableValidationResponse.new(response.body)
      result.last_response = Retab::Types::ApiResponse.new(
        http_status: response.code.to_i,
        http_headers: response.each_header.to_h,
        request_id: response["x-request-id"]
      )
      result
    end
  end
end
