# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require "json"

module Retab
  class Usage
    def initialize(client)
      @client = client
    end

    # List Usage Blocks
    # @param limit [Integer, nil] Maximum number of block rows to return.
    # @param order [Retab::Types::UsageOrder, nil] Sort direction on block id.
    # @param before [String, nil] Return blocks before this cursor (opaque token from a prior page's list_metadata).
    # @param after [String, nil] Return blocks after this cursor (opaque token from a prior page's list_metadata).
    # @param workflow_id [String, nil] Filter to a single workflow id.
    # @param block_type [String, nil] Filter by block type (e.g. extract, classify, split, parse, edit, partition).
    # @param from_date [String, nil] Inclusive activity lower bound (YYYY-MM-DD, UTC).
    # @param to_date [String, nil] Inclusive activity upper bound (YYYY-MM-DD, UTC).
    # @param request_options [Hash] (see Retab::Types::RequestOptions)
    # @return [Retab::PaginatedList<Retab::UsageBlockRecord>]
    def list_blocks(
      limit: 20,
      order: "desc",
      before: nil,
      after: nil,
      workflow_id: nil,
      block_type: nil,
      from_date: nil,
      to_date: nil,
      request_options: {}
    )
      params = {
        "limit" => limit,
        "order" => order,
        "before" => before,
        "after" => after,
        "workflow_id" => workflow_id,
        "block_type" => block_type,
        "from_date" => from_date,
        "to_date" => to_date
      }.compact
      response = @client.request(
        method: :get,
        path: "/v1/usage/blocks",
        auth: true,
        params: params,
        request_options: request_options
      )
      fetch_next = -> (cursor) {
        list_blocks(
          limit: limit,
          order: order,
          before: before,
          after: cursor,
          workflow_id: workflow_id,
          block_type: block_type,
          from_date: from_date,
          to_date: to_date,
          request_options: request_options
        )
      }
      Retab::PaginatedList.from_response(
        response,
        model: Retab::UsageBlockRecord,
        filters: {
          limit: limit,
          order: order,
          before: before,
          workflow_id: workflow_id,
          block_type: block_type,
          from_date: from_date,
          to_date: to_date
        },
        fetch_next: fetch_next
      )
    end

    # List Usage Primitives
    # @param limit [Integer, nil] Maximum number of execution rows to return.
    # @param order [Retab::Types::UsageOrder, nil] Sort direction on execution created_at.
    # @param before [String, nil] Return executions before this primitive-execution id (keyset cursor).
    # @param after [String, nil] Return executions after this primitive-execution id (keyset cursor).
    # @param environment_id [String, nil] Scope the export to this environment id within the caller's organization. Defaults to the authenticated identity's environment.
    # @param workflow_id [String, nil] Filter to a single workflow id (origin workflow).
    # @param project_id [String, nil] Filter to executions owned by a single project id.
    # @param api_key_id [String, nil] Filter to executions triggered by a single API key id (the api_key_id returned under triggered_by).
    # @param access_token_id [String, nil] Filter to executions triggered by a single access token id (the access_token_id returned under triggered_by).
    # @param user_id [String, nil] Filter to executions triggered by a single user id (the user_id returned under triggered_by).
    # @param run_id [String, nil] Filter to a single workflow run id (origin run).
    # @param block_id [String, nil] Filter to a single workflow block id (origin block).
    # @param operation [String, nil] Filter by operation (extraction, classify, split, parse, edit, schema_generation).
    # @param status [String, nil] Filter by execution lifecycle status.
    # @param metadata [String, nil] Filter by metadata equality: a JSON object of string key/value pairs (e.g. {"tenant":"acme"}). Pairs AND together.
    # @param from_date [String, nil] Inclusive created_at lower bound (YYYY-MM-DD, UTC).
    # @param to_date [String, nil] Inclusive created_at upper bound (YYYY-MM-DD, UTC).
    # @param request_options [Hash] (see Retab::Types::RequestOptions)
    # @return [Retab::PaginatedList<Retab::UsagePrimitiveRecord>]
    def list_primitives(
      limit: 20,
      order: "desc",
      before: nil,
      after: nil,
      environment_id: nil,
      workflow_id: nil,
      project_id: nil,
      api_key_id: nil,
      access_token_id: nil,
      user_id: nil,
      run_id: nil,
      block_id: nil,
      operation: nil,
      status: nil,
      metadata: nil,
      from_date: nil,
      to_date: nil,
      request_options: {}
    )
      params = {
        "limit" => limit,
        "order" => order,
        "before" => before,
        "after" => after,
        "environment_id" => environment_id,
        "workflow_id" => workflow_id,
        "project_id" => project_id,
        "api_key_id" => api_key_id,
        "access_token_id" => access_token_id,
        "user_id" => user_id,
        "run_id" => run_id,
        "block_id" => block_id,
        "operation" => operation,
        "status" => status,
        "metadata" => metadata,
        "from_date" => from_date,
        "to_date" => to_date
      }.compact
      response = @client.request(
        method: :get,
        path: "/v1/usage/primitives",
        auth: true,
        params: params,
        request_options: request_options
      )
      fetch_next = -> (cursor) {
        list_primitives(
          limit: limit,
          order: order,
          before: before,
          after: cursor,
          environment_id: environment_id,
          workflow_id: workflow_id,
          project_id: project_id,
          api_key_id: api_key_id,
          access_token_id: access_token_id,
          user_id: user_id,
          run_id: run_id,
          block_id: block_id,
          operation: operation,
          status: status,
          metadata: metadata,
          from_date: from_date,
          to_date: to_date,
          request_options: request_options
        )
      }
      Retab::PaginatedList.from_response(
        response,
        model: Retab::UsagePrimitiveRecord,
        filters: {
          limit: limit,
          order: order,
          before: before,
          environment_id: environment_id,
          workflow_id: workflow_id,
          project_id: project_id,
          api_key_id: api_key_id,
          access_token_id: access_token_id,
          user_id: user_id,
          run_id: run_id,
          block_id: block_id,
          operation: operation,
          status: status,
          metadata: metadata,
          from_date: from_date,
          to_date: to_date
        },
        fetch_next: fetch_next
      )
    end

    # List Usage Runs
    # @param limit [Integer, nil] Maximum number of run rows to return.
    # @param order [Retab::Types::UsageOrder, nil] Sort direction on run created_at.
    # @param before [String, nil] Return runs before this run id (keyset cursor).
    # @param after [String, nil] Return runs after this run id (keyset cursor).
    # @param workflow_id [String, nil] Filter to a single workflow id.
    # @param status [String, nil] Filter by lifecycle status: pending, queued, running, completed, error, failed, awaiting_review, or cancelled.
    # @param trigger_type [String, nil] Filter by trigger type: manual, api, schedule, webhook, email, or restart.
    # @param from_date [String, nil] Inclusive created_at lower bound (YYYY-MM-DD, UTC).
    # @param to_date [String, nil] Inclusive created_at upper bound (YYYY-MM-DD, UTC).
    # @param request_options [Hash] (see Retab::Types::RequestOptions)
    # @return [Retab::PaginatedList<Retab::UsageRunRecord>]
    def list_runs(
      limit: 20,
      order: "desc",
      before: nil,
      after: nil,
      workflow_id: nil,
      status: nil,
      trigger_type: nil,
      from_date: nil,
      to_date: nil,
      request_options: {}
    )
      params = {
        "limit" => limit,
        "order" => order,
        "before" => before,
        "after" => after,
        "workflow_id" => workflow_id,
        "status" => status,
        "trigger_type" => trigger_type,
        "from_date" => from_date,
        "to_date" => to_date
      }.compact
      response = @client.request(
        method: :get,
        path: "/v1/usage/runs",
        auth: true,
        params: params,
        request_options: request_options
      )
      fetch_next = -> (cursor) {
        list_runs(
          limit: limit,
          order: order,
          before: before,
          after: cursor,
          workflow_id: workflow_id,
          status: status,
          trigger_type: trigger_type,
          from_date: from_date,
          to_date: to_date,
          request_options: request_options
        )
      }
      Retab::PaginatedList.from_response(
        response,
        model: Retab::UsageRunRecord,
        filters: {
          limit: limit,
          order: order,
          before: before,
          workflow_id: workflow_id,
          status: status,
          trigger_type: trigger_type,
          from_date: from_date,
          to_date: to_date
        },
        fetch_next: fetch_next
      )
    end
  end
end
