# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require "json"

module Retab
  class Workflows
    def initialize(client)
      @client = client
    end

    def artifacts
      @artifacts ||= Retab::WorkflowArtifacts.new(@client)
    end

    def blocks
      @blocks ||= Retab::WorkflowBlocks.new(@client)
    end

    def edges
      @edges ||= Retab::WorkflowEdges.new(@client)
    end

    def experiments
      @experiments ||= Retab::WorkflowExperiments.new(@client)
    end

    def reviews
      @reviews ||= Retab::WorkflowReviews.new(@client)
    end

    def runs
      @runs ||= Retab::WorkflowRuns.new(@client)
    end

    def spec
      @spec ||= Retab::WorkflowSpec.new(@client)
    end

    def steps
      @steps ||= Retab::WorkflowSteps.new(@client)
    end

    def tests
      @tests ||= Retab::WorkflowTests.new(@client)
    end

    # List Workflows
    # @param before [String, nil]
    # @param after [String, nil]
    # @param limit [Integer, nil] Items per page
    # @param order [Retab::Types::WorkflowsOrder, nil]
    # @param sort_by [String, nil]
    # @param request_options [Hash] (see Retab::Types::RequestOptions)
    # @return [Retab::PaginatedList<Retab::Workflow>]
    def list(
      before: nil,
      after: nil,
      limit: 10,
      order: "desc",
      sort_by: "updated_at",
      request_options: {}
    )
      params = {
        "before" => before,
        "after" => after,
        "limit" => limit,
        "order" => order,
        "sort_by" => sort_by
      }.compact
      response = @client.request(
        method: :get,
        path: "/v1/workflows",
        auth: true,
        params: params,
        request_options: request_options
      )
      fetch_next = -> (cursor) {
        list(
          before: before,
          after: cursor,
          limit: limit,
          order: order,
          sort_by: sort_by,
          request_options: request_options
        )
      }
      Retab::PaginatedList.from_response(
        response,
        model: Retab::Workflow,
        filters: {before: before, limit: limit, order: order, sort_by: sort_by},
        fetch_next: fetch_next
      )
    end

    # Create Workflow
    # @param name [String, nil] The name of the workflow
    # @param description [String, nil] Description of the workflow
    # @param request_options [Hash] (see Retab::Types::RequestOptions)
    # @return [Retab::Workflow]
    def create(
      name: nil,
      description: nil,
      request_options: {}
    )
      body = {
        "name" => name,
        "description" => description
      }.compact
      response = @client.request(
        method: :post,
        path: "/v1/workflows",
        auth: true,
        body: body,
        request_options: request_options
      )
      result = Retab::Workflow.new(response.body)
      result.last_response = Retab::Types::ApiResponse.new(
        http_status: response.code.to_i,
        http_headers: response.each_header.to_h,
        request_id: response["x-request-id"]
      )
      result
    end

    # Get Workflow
    # @param workflow_id [String]
    # @param request_options [Hash] (see Retab::Types::RequestOptions)
    # @return [Retab::Workflow]
    def get(
      workflow_id:,
      request_options: {}
    )
      response = @client.request(
        method: :get,
        path: "/v1/workflows/#{Retab::Util.encode_path(workflow_id)}",
        auth: true,
        request_options: request_options
      )
      result = Retab::Workflow.new(response.body)
      result.last_response = Retab::Types::ApiResponse.new(
        http_status: response.code.to_i,
        http_headers: response.each_header.to_h,
        request_id: response["x-request-id"]
      )
      result
    end

    # Update Workflow
    # @param workflow_id [String]
    # @param name [String, nil] The name of the workflow
    # @param description [String, nil] Description of the workflow
    # @param request_options [Hash] (see Retab::Types::RequestOptions)
    # @return [Retab::Workflow]
    def update(
      workflow_id:,
      name: nil,
      description: nil,
      request_options: {}
    )
      body = {
        "name" => name,
        "description" => description
      }.compact
      response = @client.request(
        method: :patch,
        path: "/v1/workflows/#{Retab::Util.encode_path(workflow_id)}",
        auth: true,
        body: body,
        request_options: request_options
      )
      result = Retab::Workflow.new(response.body)
      result.last_response = Retab::Types::ApiResponse.new(
        http_status: response.code.to_i,
        http_headers: response.each_header.to_h,
        request_id: response["x-request-id"]
      )
      result
    end

    # Delete Workflow
    # @param workflow_id [String]
    # @param request_options [Hash] (see Retab::Types::RequestOptions)
    # @return [void]
    def delete(
      workflow_id:,
      request_options: {}
    )
      @client.request(
        method: :delete,
        path: "/v1/workflows/#{Retab::Util.encode_path(workflow_id)}",
        auth: true,
        request_options: request_options
      )
      nil
    end

    # Discard Draft Workflow
    # @param workflow_id [String]
    # @param request_options [Hash] (see Retab::Types::RequestOptions)
    # @return [Retab::Workflow]
    def discard_draft(
      workflow_id:,
      request_options: {}
    )
      response = @client.request(
        method: :post,
        path: "/v1/workflows/#{Retab::Util.encode_path(workflow_id)}/discard-draft",
        auth: true,
        request_options: request_options
      )
      result = Retab::Workflow.new(response.body)
      result.last_response = Retab::Types::ApiResponse.new(
        http_status: response.code.to_i,
        http_headers: response.each_header.to_h,
        request_id: response["x-request-id"]
      )
      result
    end

    # Publish Workflow
    # @param workflow_id [String]
    # @param description [String, nil] Optional description for this published version
    # @param request_options [Hash] (see Retab::Types::RequestOptions)
    # @return [Retab::Workflow]
    def publish(
      workflow_id:,
      description: nil,
      request_options: {}
    )
      body = {
        "description" => description
      }.compact
      response = @client.request(
        method: :post,
        path: "/v1/workflows/#{Retab::Util.encode_path(workflow_id)}/publish",
        auth: true,
        body: body,
        request_options: request_options
      )
      result = Retab::Workflow.new(response.body)
      result.last_response = Retab::Types::ApiResponse.new(
        http_status: response.code.to_i,
        http_headers: response.each_header.to_h,
        request_id: response["x-request-id"]
      )
      result
    end
  end
end
