# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require "json"

module Retab
  class WorkflowSpec
    def initialize(client)
      @client = client
    end

    # Validate Workflow Spec
    # @param yaml_definition [String] Workflow YAML definition
    # @param project_id [String, nil] Project that should own a workflow created from this spec. Required when applying a spec that creates a new workflow.
    # @param request_options [Hash] (see Retab::Types::RequestOptions)
    # @return [Retab::DeclarativeValidationResponse]
    def validate(
      yaml_definition:,
      project_id: nil,
      request_options: {}
    )
      body = {
        "yaml_definition" => yaml_definition,
        "project_id" => project_id
      }.compact
      response = @client.request(
        method: :post,
        path: "/v1/workflows/spec/validate",
        auth: true,
        body: body,
        request_options: request_options
      )
      result = Retab::DeclarativeValidationResponse.new(response.body)
      result.last_response = Retab::Types::ApiResponse.new(
        http_status: response.code.to_i,
        http_headers: response.each_header.to_h,
        request_id: response["x-request-id"]
      )
      result
    end

    # Export Workflow Spec
    # @param workflow_id [String]
    # @param request_options [Hash] (see Retab::Types::RequestOptions)
    # @return [Retab::DeclarativeExportResponse]
    def get(
      workflow_id:,
      request_options: {}
    )
      response = @client.request(
        method: :get,
        path: "/v1/workflows/#{Retab::Util.encode_path(workflow_id)}/spec",
        auth: true,
        request_options: request_options
      )
      result = Retab::DeclarativeExportResponse.new(response.body)
      result.last_response = Retab::Types::ApiResponse.new(
        http_status: response.code.to_i,
        http_headers: response.each_header.to_h,
        request_id: response["x-request-id"]
      )
      result
    end
  end
end
