// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AllItemsMatchCondition {
    /// Defaults to `all_items_match`.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub kind: Option<String>,
    pub condition: AllItemsMatchConditionConditionOneOf,
}
impl AllItemsMatchCondition {
    /// Construct a new `AllItemsMatchCondition` with the required fields set.
    #[allow(deprecated)]
    pub fn new(condition: AllItemsMatchConditionConditionOneOf) -> Self {
        Self {
            kind: Default::default(),
            condition,
        }
    }
}
