// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
/// Run started programmatically via the public API.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ApiTrigger {
    /// Defaults to `api`.
    #[serde(rename = "type")]
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub type_: Option<String>,
    /// API key id used to start the run, when known
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub api_key_id: Option<String>,
}
