// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
/// POST /workflows/reviews/{review_id}/approve body.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApproveReviewRequest {
    /// Exact content-addressed key of the version to approve.
    pub version_id: String,
}
