// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
/// Block-test assertion against one declared output handle.
/// ``target`` is the only supported shape: an output handle id and an
/// optional relative path inside that handle's payload.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AssertionSpec {
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub id: Option<String>,
    pub target: OutputTarget,
    pub condition: AllItemsMatchConditionConditionOneOf,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub label: Option<String>,
}
