// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BetweenCondition {
    /// Defaults to `between`.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub kind: Option<String>,
    pub lower: BetweenConditionLowerOneOf,
    pub upper: BetweenConditionLowerOneOf,
    /// Defaults to `true`.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub inclusive: Option<bool>,
}
impl BetweenCondition {
    /// Construct a new `BetweenCondition` with the required fields set.
    #[allow(deprecated)]
    pub fn new(lower: BetweenConditionLowerOneOf, upper: BetweenConditionLowerOneOf) -> Self {
        Self {
            kind: Default::default(),
            lower,
            upper,
            inclusive: Default::default(),
        }
    }
}
