// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
/// The execution was intentionally stopped before completion.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CancelledBlockExecutionLifecycle {
    /// Defaults to `cancelled`.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub status: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub reason: Option<serde_json::Value>,
}
