// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ClassificationWorkflowArtifact {
    /// Unique identifier of the classification
    pub id: String,
    /// Information about the classified file
    pub file: FileRef,
    /// Model used for classification
    pub model: String,
    /// Categories the document was classified against
    pub categories: Vec<Category>,
    /// Number of consensus votes used
    ///
    /// Defaults to `1`.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub n_consensus: Option<i64>,
    /// Free-form instructions supplied with the classification request.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub instructions: Option<String>,
    /// The classification result with reasoning
    pub output: ClassificationDecision,
    /// Consensus metadata for multi-vote classification runs
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub consensus: Option<ClassificationConsensus>,
    /// Usage information for the classification
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub usage: Option<RetabUsage>,
    /// Timestamp when this artifact was created.
    pub created_at: String,
    /// Artifact operation that determines the backing record type
    ///
    /// Defaults to `classification`.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub operation: Option<String>,
}
impl ClassificationWorkflowArtifact {
    /// Construct a new `ClassificationWorkflowArtifact` with the required fields set.
    #[allow(deprecated)]
    pub fn new(
        id: impl Into<String>,
        file: FileRef,
        model: impl Into<String>,
        categories: Vec<Category>,
        output: ClassificationDecision,
        created_at: impl Into<String>,
    ) -> Self {
        Self {
            id: id.into(),
            file,
            model: model.into(),
            categories,
            n_consensus: Default::default(),
            instructions: Default::default(),
            output,
            consensus: Default::default(),
            usage: Default::default(),
            created_at: created_at.into(),
            operation: Default::default(),
        }
    }
}
