// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
/// Run one saved workflow test by test id.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateWorkflowTestRunForTestRequest {
    pub test_id: String,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub workflow_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub n_consensus: Option<i64>,
}
impl CreateWorkflowTestRunForTestRequest {
    /// Construct a new `CreateWorkflowTestRunForTestRequest` with the required fields set.
    #[allow(deprecated)]
    pub fn new(test_id: impl Into<String>) -> Self {
        Self {
            test_id: test_id.into(),
            workflow_id: Default::default(),
            n_consensus: Default::default(),
        }
    }
}
