// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct File {
    /// Defaults to `file`.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub object: Option<String>,
    /// The unique identifier of the file
    pub id: String,
    /// The name of the file
    pub filename: String,
    /// When the file was created
    pub created_at: String,
    /// When the file was last updated
    pub updated_at: String,
    /// Number of pages in the file
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub page_count: Option<i64>,
}
