// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GenerateSchemaRequest {
    pub documents: Vec<MimeDataInput>,
    /// Defaults to `retab-small`.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub model: Option<String>,
    /// Defaults to `minimal`.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub reasoning_effort: Option<GenerateSchemaRequestReasoningEffort>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub instructions: Option<String>,
    /// Resolution of the image sent to the LLM
    ///
    /// Defaults to `192`.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub image_resolution_dpi: Option<i64>,
    /// Defaults to `false`.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub stream: Option<bool>,
}
impl GenerateSchemaRequest {
    /// Construct a new `GenerateSchemaRequest` with the required fields set.
    #[allow(deprecated)]
    pub fn new(documents: Vec<MimeDataInput>) -> Self {
        Self {
            documents,
            model: Default::default(),
            reasoning_effort: Default::default(),
            instructions: Default::default(),
            image_resolution_dpi: Default::default(),
            stream: Default::default(),
        }
    }
}
