// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MimeDataInput {
    /// The filename of the file
    pub filename: String,
    /// The URL of the file in base64 format
    pub url: String,
}
impl MimeDataInput {
    /// Construct a new `MimeDataInput` with the required fields set.
    #[allow(deprecated)]
    pub fn new(filename: impl Into<String>, url: impl Into<String>) -> Self {
        Self {
            filename: filename.into(),
            url: url.into(),
        }
    }
}
