// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NotContainsCondition {
    /// Defaults to `not_contains`.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub kind: Option<String>,
    pub expected: serde_json::Value,
}
