// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
/// Public create-parse request body.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ParseRequest {
    /// The document to parse
    pub document: MimeData,
    /// The model to use for parsing
    ///
    /// Defaults to `retab-small`.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub model: Option<String>,
    /// Format used to render tables extracted from the document
    ///
    /// Defaults to `html`.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub table_parsing_format: Option<ParseRequestTableParsingFormat>,
    /// DPI used when rasterizing pages for the parser
    ///
    /// Defaults to `192`.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub image_resolution_dpi: Option<i64>,
    /// Free-form instructions appended to the system prompt to steer the parse.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub instructions: Option<String>,
    /// If true, skip the LLM cache and force a fresh completion
    ///
    /// Defaults to `false`.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub bust_cache: Option<bool>,
    /// If true, run asynchronously: returns immediately with status 'queued' and an empty output. Poll GET /v1/<primitive>/{id} until status is terminal. Mutually exclusive with stream.
    ///
    /// Defaults to `false`.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub background: Option<bool>,
}
impl ParseRequest {
    /// Construct a new `ParseRequest` with the required fields set.
    #[allow(deprecated)]
    pub fn new<D: Into<crate::MimeData>>(document: D) -> Self {
        Self {
            document: document.into(),
            model: Default::default(),
            table_parsing_format: Default::default(),
            image_resolution_dpi: Default::default(),
            instructions: Default::default(),
            bust_cache: Default::default(),
            background: Default::default(),
        }
    }
}
