// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PartitionWorkflowArtifact {
    /// Unique identifier of the partition
    pub id: String,
    /// Information about the partitioned file
    pub file: FileRef,
    /// Model used for the partition operation
    pub model: String,
    /// Partition key used for the run
    pub key: String,
    /// Free-form instructions supplied with the partition request
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub instructions: Option<String>,
    /// Number of consensus votes used
    ///
    /// Defaults to `1`.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub n_consensus: Option<i64>,
    /// Whether pages were allowed to appear in more than one partition chunk
    ///
    /// Defaults to `true`.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub allow_overlap: Option<bool>,
    /// The list of partition chunks with their assigned pages
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub output: Option<Vec<PartitionChunk>>,
    /// Consensus metadata for multi-vote partition runs
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub consensus: Option<PartitionConsensus>,
    /// Usage information for the partition operation
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub usage: Option<RetabUsage>,
    /// When this artifact was written by the orchestrator.
    pub created_at: String,
    /// Artifact operation that determines the backing record type
    ///
    /// Defaults to `partition`.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub operation: Option<String>,
}
