// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
/// Optional request body for publishing a workflow.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct PublishWorkflowRequest {
    /// Optional description for this published version
    ///
    /// Defaults to ``.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub description: Option<String>,
}
