// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReconstructEnrichedRow {
    pub cells: Vec<String>,
}
impl ReconstructEnrichedRow {
    /// Construct a new `ReconstructEnrichedRow` with the required fields set.
    #[allow(deprecated)]
    pub fn new(cells: Vec<String>) -> Self {
        Self { cells }
    }
}
