// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
/// Gate fires if ANY child predicate fires. Evaluated in list order;
/// `triggered_by` reports the first match (decision: first-match wins).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReviewAnyOf {
    /// Defaults to `any_of`.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub kind: Option<String>,
    pub predicates: Vec<ReviewAllOfPredicatesOneOf>,
}
