// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
/// Gate when the predicted category is in `categories` (e.g., review fraud alerts).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReviewCategoryIn {
    /// Defaults to `category_in`.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub kind: Option<String>,
    pub categories: Vec<String>,
}
