// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
/// The step was skipped.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SkippedStepLifecycle {
    /// Defaults to `skipped`.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub status: Option<String>,
    /// Reason the step was skipped
    pub reason: String,
}
impl SkippedStepLifecycle {
    /// Construct a new `SkippedStepLifecycle` with the required fields set.
    #[allow(deprecated)]
    pub fn new(reason: impl Into<String>) -> Self {
        Self {
            status: Default::default(),
            reason: reason.into(),
        }
    }
}
