// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorkflowTableAggregationRequest {
    pub function: WorkflowTableAggregationFunction,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub column: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub alias: Option<String>,
}
impl WorkflowTableAggregationRequest {
    /// Construct a new `WorkflowTableAggregationRequest` with the required fields set.
    #[allow(deprecated)]
    pub fn new(function: WorkflowTableAggregationFunction) -> Self {
        Self {
            function,
            column: Default::default(),
            alias: Default::default(),
        }
    }
}
