// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorkflowTestRunTiming {
    /// When the workflow-test run was created.
    pub created_at: String,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub started_at: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub completed_at: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub duration_ms: Option<i64>,
}
impl WorkflowTestRunTiming {
    /// Construct a new `WorkflowTestRunTiming` with the required fields set.
    #[allow(deprecated)]
    pub fn new(created_at: impl Into<String>) -> Self {
        Self {
            created_at: created_at.into(),
            started_at: Default::default(),
            completed_at: Default::default(),
            duration_ms: Default::default(),
        }
    }
}
