// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorkflowTableListResponse {
    pub tables: Vec<WorkflowTable>,
}
impl WorkflowTableListResponse {
    /// Construct a new `WorkflowTableListResponse` with the required fields set.
    #[allow(deprecated)]
    pub fn new(tables: Vec<WorkflowTable>) -> Self {
        Self { tables }
    }
}
