// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
/// Dereferenced workflow artifact with operation-specific fields preserved.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorkflowArtifact {
    /// The operation that produced this artifact
    pub operation: WorkflowArtifactOperation,
    /// Resource identifier
    pub id: String,
    /// Additional properties not captured by named fields
    #[serde(rename = "additionalProperties")]
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub additional_properties: Option<std::collections::HashMap<String, serde_json::Value>>,
}
impl WorkflowArtifact {
    /// Construct a new `WorkflowArtifact` with the required fields set.
    #[allow(deprecated)]
    pub fn new(operation: WorkflowArtifactOperation, id: impl Into<String>) -> Self {
        Self {
            operation,
            id: id.into(),
            additional_properties: Default::default(),
        }
    }
}
