// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorkflowTableSchemaResponse {
    pub table_id: String,
    pub columns: Vec<WorkflowTableColumn>,
}
impl WorkflowTableSchemaResponse {
    /// Construct a new `WorkflowTableSchemaResponse` with the required fields set.
    #[allow(deprecated)]
    pub fn new(table_id: impl Into<String>, columns: Vec<WorkflowTableColumn>) -> Self {
        Self {
            table_id: table_id.into(),
            columns,
        }
    }
}
