// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
/// Reference to the workflow and immutable version that drove the run.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorkflowSnapshotRef {
    /// ID of the workflow that was run
    pub workflow_id: String,
    /// Content-addressed workflow version used for this run.
    pub version_id: String,
}
impl WorkflowSnapshotRef {
    /// Construct a new `WorkflowSnapshotRef` with the required fields set.
    #[allow(deprecated)]
    pub fn new(workflow_id: impl Into<String>, version_id: impl Into<String>) -> Self {
        Self {
            workflow_id: workflow_id.into(),
            version_id: version_id.into(),
        }
    }
}
