// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorkflowTableSortRule {
    pub column: String,
    /// Defaults to `asc`.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub direction: Option<WorkflowTableSortDirection>,
}
impl WorkflowTableSortRule {
    /// Construct a new `WorkflowTableSortRule` with the required fields set.
    #[allow(deprecated)]
    pub fn new(column: impl Into<String>) -> Self {
        Self {
            column: column.into(),
            direction: Default::default(),
        }
    }
}
