// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorkflowBlockVersionDiff {
    pub from_block_version_id: String,
    pub to_block_version_id: String,
    pub block_id: String,
    /// Defaults to `[]`.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub changes: Option<Vec<WorkflowVersionFieldDiff>>,
}
impl WorkflowBlockVersionDiff {
    /// Construct a new `WorkflowBlockVersionDiff` with the required fields set.
    #[allow(deprecated)]
    pub fn new(
        from_block_version_id: impl Into<String>,
        to_block_version_id: impl Into<String>,
        block_id: impl Into<String>,
    ) -> Self {
        Self {
            from_block_version_id: from_block_version_id.into(),
            to_block_version_id: to_block_version_id.into(),
            block_id: block_id.into(),
            changes: Default::default(),
        }
    }
}
