# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module Retab
  class ValidateWorkflowBlockConfigRequest < Retab::Types::BaseModel

    HASH_ATTRS = {
      config: :config,
      config_mode: :config_mode
    }.freeze

    attr_accessor(
      :config,
      :config_mode
    )

    def initialize(json)
      super()
      hash = self.class.normalize(json)
      @config = hash[:config] || {}
      @config_mode = hash[:config_mode].nil? ? "replace" : hash[:config_mode]
    end
  end
end
