# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module Retab
  class WorkflowBlockCreateRequest < Retab::Types::BaseModel

    HASH_ATTRS = {
      workflow_id: :workflow_id,
      id: :id,
      type: :type,
      label: :label,
      position_x: :position_x,
      position_y: :position_y,
      width: :width,
      height: :height,
      config: :config,
      parent_id: :parent_id
    }.freeze

    attr_accessor(
      :workflow_id,
      :id,
      :type,
      :label,
      :position_x,
      :position_y,
      :width,
      :height,
      :config,
      :parent_id
    )

    def initialize(json)
      super()
      hash = self.class.normalize(json)
      @workflow_id = hash[:workflow_id]
      @id = hash[:id]
      @type = hash[:type]
      @label = hash[:label]
      @position_x = hash[:position_x]
      @position_y = hash[:position_y]
      @width = hash[:width]
      @height = hash[:height]
      @config = hash[:config] || {}
      @parent_id = hash[:parent_id]
    end
  end
end
