// This file is auto-generated by the Retab oagen emitter. Do not edit by hand.

import { z } from 'zod';
import type { ReviewAlways, ReviewAlwaysResponse } from './review-always.interface.js';
import {
  ZReviewAlways,
  deserializeReviewAlways,
  serializeReviewAlways,
} from './review-always.interface.js';
import type { ReviewAnyOf, ReviewAnyOfResponse } from './review-any-of.interface.js';
import {
  ZReviewAnyOf,
  deserializeReviewAnyOf,
  serializeReviewAnyOf,
} from './review-any-of.interface.js';
import type {
  ReviewAnyRequiredFieldNull,
  ReviewAnyRequiredFieldNullResponse,
} from './review-any-required-field-null.interface.js';
import {
  ZReviewAnyRequiredFieldNull,
  deserializeReviewAnyRequiredFieldNull,
  serializeReviewAnyRequiredFieldNull,
} from './review-any-required-field-null.interface.js';
import type {
  ReviewAnySplitPagesLt,
  ReviewAnySplitPagesLtResponse,
} from './review-any-split-pages-lt.interface.js';
import {
  ZReviewAnySplitPagesLt,
  deserializeReviewAnySplitPagesLt,
  serializeReviewAnySplitPagesLt,
} from './review-any-split-pages-lt.interface.js';
import type {
  ReviewBoundaryConfidenceLt,
  ReviewBoundaryConfidenceLtResponse,
} from './review-boundary-confidence-lt.interface.js';
import {
  ZReviewBoundaryConfidenceLt,
  deserializeReviewBoundaryConfidenceLt,
  serializeReviewBoundaryConfidenceLt,
} from './review-boundary-confidence-lt.interface.js';
import type { ReviewBranchIn, ReviewBranchInResponse } from './review-branch-in.interface.js';
import {
  ZReviewBranchIn,
  deserializeReviewBranchIn,
  serializeReviewBranchIn,
} from './review-branch-in.interface.js';
import type { ReviewCategoryIn, ReviewCategoryInResponse } from './review-category-in.interface.js';
import {
  ZReviewCategoryIn,
  deserializeReviewCategoryIn,
  serializeReviewCategoryIn,
} from './review-category-in.interface.js';
import type {
  ReviewConfidenceLt,
  ReviewConfidenceLtResponse,
} from './review-confidence-lt.interface.js';
import {
  ZReviewConfidenceLt,
  deserializeReviewConfidenceLt,
  serializeReviewConfidenceLt,
} from './review-confidence-lt.interface.js';
import type {
  ReviewFieldConfidenceLt,
  ReviewFieldConfidenceLtResponse,
} from './review-field-confidence-lt.interface.js';
import {
  ZReviewFieldConfidenceLt,
  deserializeReviewFieldConfidenceLt,
  serializeReviewFieldConfidenceLt,
} from './review-field-confidence-lt.interface.js';
import type {
  ReviewJsonCondition,
  ReviewJsonConditionResponse,
} from './review-json-condition.interface.js';
import {
  ZReviewJsonCondition,
  deserializeReviewJsonCondition,
  serializeReviewJsonCondition,
} from './review-json-condition.interface.js';
import type {
  ReviewSplitCountNeq,
  ReviewSplitCountNeqResponse,
} from './review-split-count-neq.interface.js';
import {
  ZReviewSplitCountNeq,
  deserializeReviewSplitCountNeq,
  serializeReviewSplitCountNeq,
} from './review-split-count-neq.interface.js';
import type {
  ReviewTopMarginLt,
  ReviewTopMarginLtResponse,
} from './review-top-margin-lt.interface.js';
import {
  ZReviewTopMarginLt,
  deserializeReviewTopMarginLt,
  serializeReviewTopMarginLt,
} from './review-top-margin-lt.interface.js';
import type {
  ReviewValidationFailed,
  ReviewValidationFailedResponse,
} from './review-validation-failed.interface.js';
import {
  ZReviewValidationFailed,
  deserializeReviewValidationFailed,
  serializeReviewValidationFailed,
} from './review-validation-failed.interface.js';

/** Gate fires only if ALL child predicates fire. */
export interface ReviewAllOf {
  /** @default "all_of" */
  kind: 'all_of';
  predicates: (
    | ReviewAlways
    | ReviewValidationFailed
    | ReviewConfidenceLt
    | ReviewCategoryIn
    | ReviewTopMarginLt
    | ReviewSplitCountNeq
    | ReviewAnySplitPagesLt
    | ReviewBoundaryConfidenceLt
    | ReviewAnyRequiredFieldNull
    | ReviewFieldConfidenceLt
    | ReviewJsonCondition
    | ReviewBranchIn
    | ReviewAnyOf
    | ReviewAllOf
  )[];
}

export interface ReviewAllOfResponse {
  kind: 'all_of';
  predicates: (
    | ReviewAlwaysResponse
    | ReviewValidationFailedResponse
    | ReviewConfidenceLtResponse
    | ReviewCategoryInResponse
    | ReviewTopMarginLtResponse
    | ReviewSplitCountNeqResponse
    | ReviewAnySplitPagesLtResponse
    | ReviewBoundaryConfidenceLtResponse
    | ReviewAnyRequiredFieldNullResponse
    | ReviewFieldConfidenceLtResponse
    | ReviewJsonConditionResponse
    | ReviewBranchInResponse
    | ReviewAnyOfResponse
    | ReviewAllOfResponse
  )[];
}

export const ZReviewAllOf = z.lazy(() =>
  z.object({
    kind: z.literal('all_of'),
    predicates: z
      .union([
        ZReviewAlways,
        ZReviewValidationFailed,
        ZReviewConfidenceLt,
        ZReviewCategoryIn,
        ZReviewTopMarginLt,
        ZReviewSplitCountNeq,
        ZReviewAnySplitPagesLt,
        ZReviewBoundaryConfidenceLt,
        ZReviewAnyRequiredFieldNull,
        ZReviewFieldConfidenceLt,
        ZReviewJsonCondition,
        ZReviewBranchIn,
        ZReviewAnyOf,
        z.lazy(() => ZReviewAllOf),
      ])
      .array(),
  })
) as z.ZodType<ReviewAllOf>;

export function deserializeReviewAllOf(wire: ReviewAllOfResponse): ReviewAllOf {
  return {
    kind: wire['kind'],
    predicates: wire['predicates'].map(
      (__i) =>
        (
          ({
            all_of: () => deserializeReviewAllOf(__i as ReviewAllOfResponse),
            always: () => deserializeReviewAlways(__i as ReviewAlwaysResponse),
            any_of: () => deserializeReviewAnyOf(__i as ReviewAnyOfResponse),
            any_required_field_null: () =>
              deserializeReviewAnyRequiredFieldNull(__i as ReviewAnyRequiredFieldNullResponse),
            any_split_pages_lt: () =>
              deserializeReviewAnySplitPagesLt(__i as ReviewAnySplitPagesLtResponse),
            boundary_confidence_lt: () =>
              deserializeReviewBoundaryConfidenceLt(__i as ReviewBoundaryConfidenceLtResponse),
            branch_in: () => deserializeReviewBranchIn(__i as ReviewBranchInResponse),
            category_in: () => deserializeReviewCategoryIn(__i as ReviewCategoryInResponse),
            confidence_lt: () => deserializeReviewConfidenceLt(__i as ReviewConfidenceLtResponse),
            field_confidence_lt: () =>
              deserializeReviewFieldConfidenceLt(__i as ReviewFieldConfidenceLtResponse),
            json_condition: () =>
              deserializeReviewJsonCondition(__i as ReviewJsonConditionResponse),
            split_count_neq: () =>
              deserializeReviewSplitCountNeq(__i as ReviewSplitCountNeqResponse),
            top_margin_lt: () => deserializeReviewTopMarginLt(__i as ReviewTopMarginLtResponse),
            validation_failed: () =>
              deserializeReviewValidationFailed(__i as ReviewValidationFailedResponse),
          }) as Record<
            string,
            () =>
              | ReviewAlways
              | ReviewValidationFailed
              | ReviewConfidenceLt
              | ReviewCategoryIn
              | ReviewTopMarginLt
              | ReviewSplitCountNeq
              | ReviewAnySplitPagesLt
              | ReviewBoundaryConfidenceLt
              | ReviewAnyRequiredFieldNull
              | ReviewFieldConfidenceLt
              | ReviewJsonCondition
              | ReviewBranchIn
              | ReviewAnyOf
              | ReviewAllOf
          >
        )[(__i as unknown as Record<string, string>)['kind']]?.() ??
        (__i as unknown as
          | ReviewAlways
          | ReviewValidationFailed
          | ReviewConfidenceLt
          | ReviewCategoryIn
          | ReviewTopMarginLt
          | ReviewSplitCountNeq
          | ReviewAnySplitPagesLt
          | ReviewBoundaryConfidenceLt
          | ReviewAnyRequiredFieldNull
          | ReviewFieldConfidenceLt
          | ReviewJsonCondition
          | ReviewBranchIn
          | ReviewAnyOf
          | ReviewAllOf)
    ),
  };
}

export function serializeReviewAllOf(domain: ReviewAllOf): ReviewAllOfResponse {
  return {
    kind: domain['kind'],
    predicates: domain['predicates'].map(
      (__i) =>
        (
          ({
            all_of: () => serializeReviewAllOf(__i as ReviewAllOf),
            always: () => serializeReviewAlways(__i as ReviewAlways),
            any_of: () => serializeReviewAnyOf(__i as ReviewAnyOf),
            any_required_field_null: () =>
              serializeReviewAnyRequiredFieldNull(__i as ReviewAnyRequiredFieldNull),
            any_split_pages_lt: () => serializeReviewAnySplitPagesLt(__i as ReviewAnySplitPagesLt),
            boundary_confidence_lt: () =>
              serializeReviewBoundaryConfidenceLt(__i as ReviewBoundaryConfidenceLt),
            branch_in: () => serializeReviewBranchIn(__i as ReviewBranchIn),
            category_in: () => serializeReviewCategoryIn(__i as ReviewCategoryIn),
            confidence_lt: () => serializeReviewConfidenceLt(__i as ReviewConfidenceLt),
            field_confidence_lt: () =>
              serializeReviewFieldConfidenceLt(__i as ReviewFieldConfidenceLt),
            json_condition: () => serializeReviewJsonCondition(__i as ReviewJsonCondition),
            split_count_neq: () => serializeReviewSplitCountNeq(__i as ReviewSplitCountNeq),
            top_margin_lt: () => serializeReviewTopMarginLt(__i as ReviewTopMarginLt),
            validation_failed: () => serializeReviewValidationFailed(__i as ReviewValidationFailed),
          }) as Record<
            string,
            () =>
              | ReviewAlwaysResponse
              | ReviewValidationFailedResponse
              | ReviewConfidenceLtResponse
              | ReviewCategoryInResponse
              | ReviewTopMarginLtResponse
              | ReviewSplitCountNeqResponse
              | ReviewAnySplitPagesLtResponse
              | ReviewBoundaryConfidenceLtResponse
              | ReviewAnyRequiredFieldNullResponse
              | ReviewFieldConfidenceLtResponse
              | ReviewJsonConditionResponse
              | ReviewBranchInResponse
              | ReviewAnyOfResponse
              | ReviewAllOfResponse
          >
        )[(__i as unknown as Record<string, string>)['kind']]?.() ??
        (__i as unknown as
          | ReviewAlwaysResponse
          | ReviewValidationFailedResponse
          | ReviewConfidenceLtResponse
          | ReviewCategoryInResponse
          | ReviewTopMarginLtResponse
          | ReviewSplitCountNeqResponse
          | ReviewAnySplitPagesLtResponse
          | ReviewBoundaryConfidenceLtResponse
          | ReviewAnyRequiredFieldNullResponse
          | ReviewFieldConfidenceLtResponse
          | ReviewJsonConditionResponse
          | ReviewBranchInResponse
          | ReviewAnyOfResponse
          | ReviewAllOfResponse)
    ),
  };
}
