// This file is auto-generated by the Retab oagen emitter. Do not edit by hand.

import { z } from 'zod';
/** Gate when any required field in the extract schema has no answer: null, missing, or an empty/whitespace-only string (extraction reports a string field it could not find as "", not null). Zero, false, and empty arrays/objects are real answers and do not gate. */
export interface ReviewAnyRequiredFieldNull {
  /** @default "any_required_field_null" */
  kind: 'any_required_field_null';
}

export interface ReviewAnyRequiredFieldNullResponse {
  kind: 'any_required_field_null';
}

export const ZReviewAnyRequiredFieldNull = z.object({
  kind: z.literal('any_required_field_null'),
}) as z.ZodType<ReviewAnyRequiredFieldNull>;

export function deserializeReviewAnyRequiredFieldNull(
  wire: ReviewAnyRequiredFieldNullResponse
): ReviewAnyRequiredFieldNull {
  return {
    kind: wire['kind'],
  };
}

export function serializeReviewAnyRequiredFieldNull(
  domain: ReviewAnyRequiredFieldNull
): ReviewAnyRequiredFieldNullResponse {
  return {
    kind: domain['kind'],
  };
}
