// Code generated by oagen. DO NOT EDIT.

package retab

import (
	"context"
	"fmt"
	"net/url"
)

// EditService handles Edits operations.
type EditService struct {
	client    *Client
	Templates *EditTemplateService
}

// EditsListParams contains the parameters for List.
type EditsListParams struct {
	PaginationParams
	Filename   *string `url:"filename,omitempty" json:"-"`
	TemplateID *string `url:"template_id,omitempty" json:"-"`
	FromDate   *string `url:"from_date,omitempty" json:"-"`
	ToDate     *string `url:"to_date,omitempty" json:"-"`
}

// List edits
// List edits.
// Returns a paginated list of edits. Filter by `filename` (case-insensitive
// prefix match), `template_id`, and a `from_date`/`to_date` creation range
// (each `YYYY-MM-DD`). Page with `before`/`after` cursors, `limit`, and
// `order`; an invalid date format responds with `400`.
func (s *EditService) List(ctx context.Context, params *EditsListParams, opts ...RequestOption) (*PaginatedList[Edit], error) {
	return doPaginated[Edit](ctx, s.client, "GET", "/v1/edits", params, nil, opts...)
}

// EditsCreateParams contains the parameters for Create.
type EditsCreateParams struct {
	// Instructions is instructions describing how to fill the form fields.
	Instructions string `json:"instructions" url:"-"`
	// Document is input document (PDF, DOCX, XLSX, or PPTX). Mutually exclusive with template_id.
	Document any `json:"document,omitempty" url:"-"`
	// TemplateID is editTemplate id to fill. When provided, uses the template's pre-defined form fields and empty PDF. Mutually exclusive with document.
	TemplateID *string `json:"template_id,omitempty" url:"-"`
	// Model is the model to use for edit inference.
	Model *string `json:"model,omitempty" url:"-"`
	// Config is edit configuration (rendering options).
	Config *EditConfig `json:"config,omitempty" url:"-"`
	// BustCache is if true, skip the LLM cache and force a fresh completion.
	BustCache *bool `json:"bust_cache,omitempty" url:"-"`
}

// Create edit
// Create an edit.
// Fills the form fields of a document according to `instructions` and renders
// the values into a PDF. Provide exactly one of `document` (a PDF, DOCX, XLSX,
// or PPTX) or `template_id` (an existing edit template) — supplying both or
// neither responds with `400`. Returns the created edit with the filled form
// data and rendered document; responds with `201`.
func (s *EditService) Create(ctx context.Context, params *EditsCreateParams, opts ...RequestOption) (*Edit, error) {
	if params == nil {
		return nil, fmt.Errorf("retab: instructions is required")
	}
	if params.Instructions == "" {
		return nil, fmt.Errorf("retab: instructions is required")
	}
	type createWireBody struct {
		Instructions string      `json:"instructions"`
		Document     *MIMEData   `json:"document,omitempty"`
		TemplateID   *string     `json:"template_id,omitempty"`
		Model        *string     `json:"model,omitempty"`
		Config       *EditConfig `json:"config,omitempty"`
		BustCache    *bool       `json:"bust_cache,omitempty"`
	}
	if params == nil {
		return nil, fmt.Errorf("retab: params is required")
	}
	var coercedDocument *MIMEData
	if params.Document != nil {
		mime, err := InferMIMEData(params.Document)
		if err != nil {
			return nil, fmt.Errorf("retab: invalid document: %w", err)
		}
		coercedDocument = &mime
	}
	body := createWireBody{
		Instructions: params.Instructions,
		Document:     coercedDocument,
		TemplateID:   params.TemplateID,
		Model:        params.Model,
		Config:       params.Config,
		BustCache:    params.BustCache,
	}
	var result Edit
	_, err := s.client.request(ctx, "POST", "/v1/edits", nil, body, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Get edit
// Retrieve an edit.
// Fetches a single edit by its `edit_id`. Returns the edit with its filled
// form data and rendered document; responds with `404` if no edit with that
// id exists.
func (s *EditService) Get(ctx context.Context, editID string, opts ...RequestOption) (*Edit, error) {
	if editID == "" {
		return nil, fmt.Errorf("retab: edit_id is required")
	}
	var result Edit
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/v1/edits/%s", url.PathEscape(editID)), nil, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Delete edit
// Delete an edit.
// Permanently deletes the edit identified by `edit_id`. Returns `204` on
// success, or `404` if no edit with that id exists.
func (s *EditService) Delete(ctx context.Context, editID string, opts ...RequestOption) error {
	if editID == "" {
		return fmt.Errorf("retab: edit_id is required")
	}
	_, err := s.client.request(ctx, "DELETE", fmt.Sprintf("/v1/edits/%s", url.PathEscape(editID)), nil, nil, nil, opts)
	return err
}
