// Code generated by oagen. DO NOT EDIT.

package retab

import (
	"context"
	"fmt"
	"net/url"
)

// ExtractionSourceService handles ExtractionSources operations.
type ExtractionSourceService struct {
	client *Client
}

// ExtractionSourcesGetParams contains the parameters for Get.
type ExtractionSourcesGetParams struct {
	// Mode is opt into progressive sources for this mode. Omit to retain the legacy synchronous response.
	Mode *ExtractionSourcesMode `url:"mode,omitempty" json:"-"`
	// JobID is expected job identity returned by POST. A changed extraction returns 409.
	JobID *string `url:"job_id,omitempty" json:"-"`
}

// Get extraction Sources
// Return the extraction result enriched with per-leaf source provenance.
// Each extracted leaf value is wrapped as {value, source} where source
// contains citation content, surrounding context, and a format-specific
// anchor (bbox for PDFs, cell ref for spreadsheets, text span for plain text, etc.).
func (s *ExtractionSourceService) Get(ctx context.Context, extractionID string, params *ExtractionSourcesGetParams, opts ...RequestOption) (*SourcesResponse, error) {
	if extractionID == "" {
		return nil, fmt.Errorf("retab: extraction_id is required")
	}
	var result SourcesResponse
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/v1/extractions/%s/sources", url.PathEscape(extractionID)), params, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// ExtractionSourcesCreateParams contains the parameters for Create.
type ExtractionSourcesCreateParams struct {
	// Background is return immediately when true. Otherwise wait up to 20 seconds, then return 202 with Location while the same durable job continues.
	Background *bool `json:"background,omitempty" url:"-"`
	// JobID is optional expected sources job identity. Returns 409 if the extraction changed.
	JobID *string                   `json:"job_id,omitempty" url:"-"`
	Mode  *CreateSourcesRequestMode `json:"mode,omitempty" url:"-"`
	// Retry is retry a terminal failed or incomplete computation. Concurrent requests join the current attempt; billing remains once per extraction.
	Retry *bool `json:"retry,omitempty" url:"-"`
}

// Create extraction Sources
// Create or join a durable sources computation. Located finds printed answers; cited also seeks supporting inputs. Background requests return immediately; synchronous requests wait up to 20 seconds before returning 202 with a version-pinned Location. Repeated requests reuse work and never bill twice. Processing completion does not guarantee evidence for every field. A cited request during a located-only computation returns 409; retry after that computation finishes.
func (s *ExtractionSourceService) Create(ctx context.Context, extractionID string, params *ExtractionSourcesCreateParams, opts ...RequestOption) (*SourcesResponse, error) {
	if extractionID == "" {
		return nil, fmt.Errorf("retab: extraction_id is required")
	}
	var result SourcesResponse
	_, err := s.client.request(ctx, "POST", fmt.Sprintf("/v1/extractions/%s/sources", url.PathEscape(extractionID)), nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}
