// Code generated by oagen. DO NOT EDIT.

package retab

import (
	"context"
	"fmt"
	"net/http"
	"os"
	"strings"
	"time"
)

const defaultBaseURL = "https://api.retab.com"

// Client is the root Retab API client. Services hang off the struct as
// exported fields — callers reach an endpoint via e.g.
// `client.Extractions.Create(ctx, params)`.
type Client struct {
	apiKey     string
	baseURL    string
	httpClient *http.Client
	headers    map[string]string

	// tokenProvider, when set, returns a Bearer token at request time.
	// Takes precedence over apiKey: requests use this Bearer token instead
	// of the API key. Called on every request so callers can
	// implement transparent refresh without rebuilding the Client.
	tokenProvider func(context.Context) (string, error)

	Classifications *ClassificationService
	Edits           *EditService
	Extractions     *ExtractionService
	Files           *FileService
	Parses          *ParseService
	Partitions      *PartitionService
	Schemas         *SchemaService
	Secrets         *SecretService
	Splits          *SplitService
	Tables          *TableService
	Usage           *UsageService
	Workflows       *WorkflowService
}

// Option customizes a Retab client.
type Option func(*Client)

// WithBaseURL overrides the default Retab API base URL. A trailing
// `/v<N>` segment is stripped automatically for back-compat with older
// SDKs that baked the version into the base URL — the current SDK keeps
// /v<N> in per-operation paths instead.
func WithBaseURL(baseURL string) Option {
	return func(c *Client) {
		trimmed := strings.TrimRight(baseURL, "/")
		if idx := strings.LastIndex(trimmed, "/v"); idx >= 0 {
			suffix := trimmed[idx+2:]
			allDigits := suffix != ""
			for _, r := range suffix {
				if r < '0' || r > '9' {
					allDigits = false
					break
				}
			}
			if allDigits {
				trimmed = trimmed[:idx]
			}
		}
		c.baseURL = trimmed
	}
}

// WithHTTPClient overrides the HTTP client used for requests.
func WithHTTPClient(httpClient *http.Client) Option {
	return func(c *Client) {
		if httpClient != nil {
			c.httpClient = httpClient
		}
	}
}

// WithHeader adds a header sent on every request.
func WithHeader(key string, value string) Option {
	return func(c *Client) {
		c.headers[key] = value
	}
}

// WithBearerToken authenticates as the given Bearer token. The Client will
// send `Authorization: Bearer <token>` on every request.
// For tokens that need to be refreshed transparently, use
// WithBearerTokenProvider instead.
func WithBearerToken(token string) Option {
	return func(c *Client) {
		t := token
		c.tokenProvider = func(context.Context) (string, error) { return t, nil }
	}
}

// WithBearerTokenProvider authenticates with a Bearer token resolved at
// request time. Called once per outgoing request; if it returns an error
// the request fails before any network IO.
func WithBearerTokenProvider(provider func(context.Context) (string, error)) Option {
	return func(c *Client) {
		c.tokenProvider = provider
	}
}

// NewClient creates a Retab client. By default it authenticates with an API
// key — pass one in, or set RETAB_API_KEY. Pass an empty string AND
// WithBearerToken / WithBearerTokenProvider to authenticate with an OAuth
// access token instead. Exactly one auth mode must end up configured.
func NewClient(apiKey string, opts ...Option) (*Client, error) {
	if apiKey == "" {
		apiKey = os.Getenv("RETAB_API_KEY")
	}
	c := &Client{
		apiKey:  apiKey,
		baseURL: defaultBaseURL,
		httpClient: &http.Client{
			Timeout: 30 * time.Minute,
		},
		headers: map[string]string{},
	}
	for _, opt := range opts {
		opt(c)
	}
	if c.apiKey == "" && c.tokenProvider == nil {
		return nil, fmt.Errorf("retab: no credentials; pass an API key, set RETAB_API_KEY, or use WithBearerToken/WithBearerTokenProvider")
	}
	c.Classifications = &ClassificationService{client: c}
	c.Edits = &EditService{client: c}
	editTemplates := &EditTemplateService{client: c}
	c.Extractions = &ExtractionService{client: c}
	c.Files = &FileService{client: c}
	c.Parses = &ParseService{client: c}
	c.Partitions = &PartitionService{client: c}
	c.Schemas = &SchemaService{client: c}
	c.Secrets = &SecretService{client: c}
	c.Splits = &SplitService{client: c}
	c.Tables = &TableService{client: c}
	c.Usage = &UsageService{client: c}
	c.Workflows = &WorkflowService{client: c}
	workflowArtifacts := &WorkflowArtifactService{client: c}
	workflowBlocks := &WorkflowBlockService{client: c}
	workflowBlockExecutions := &WorkflowBlockExecutionService{client: c}
	workflowEdges := &WorkflowEdgeService{client: c}
	workflowEvals := &WorkflowEvalService{client: c}
	workflowEvalRunResults := &WorkflowEvalRunResultService{client: c}
	workflowEvalRuns := &WorkflowEvalRunService{client: c}
	workflowExperiments := &WorkflowExperimentService{client: c}
	experimentRunMetrics := &ExperimentRunMetricService{client: c}
	experimentRunResults := &ExperimentRunResultService{client: c}
	experimentRuns := &ExperimentRunService{client: c}
	workflowReviews := &WorkflowReviewService{client: c}
	workflowReviewVersions := &WorkflowReviewVersionService{client: c}
	workflowRuns := &WorkflowRunService{client: c}
	workflowSpec := &WorkflowSpecService{client: c}
	workflowSteps := &WorkflowStepService{client: c}
	c.Edits.Templates = editTemplates
	workflowBlocks.Executions = workflowBlockExecutions
	workflowEvals.Results = workflowEvalRunResults
	workflowEvals.Runs = workflowEvalRuns
	workflowExperiments.Metrics = experimentRunMetrics
	workflowExperiments.Results = experimentRunResults
	workflowExperiments.Runs = experimentRuns
	workflowReviews.Versions = workflowReviewVersions
	c.Workflows.Artifacts = workflowArtifacts
	c.Workflows.Blocks = workflowBlocks
	c.Workflows.Edges = workflowEdges
	c.Workflows.Evals = workflowEvals
	c.Workflows.Experiments = workflowExperiments
	c.Workflows.Reviews = workflowReviews
	c.Workflows.Runs = workflowRuns
	c.Workflows.Spec = workflowSpec
	c.Workflows.Steps = workflowSteps
	return c, nil
}
