// Code generated by oagen. DO NOT EDIT.

package retab

import (
	"context"
	"fmt"
	"net/url"
)

// SecretService handles Secrets operations.
type SecretService struct {
	client *Client
}

// List secrets
func (s *SecretService) List(ctx context.Context, opts ...RequestOption) (*SecretListResponse, error) {
	var result SecretListResponse
	_, err := s.client.request(ctx, "GET", "/v1/secrets", nil, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// SecretsCreateParams contains the parameters for Create.
type SecretsCreateParams struct {
	Name  string `json:"name" url:"-"`
	Value string `json:"value" url:"-"`
}

// Create secret
func (s *SecretService) Create(ctx context.Context, params *SecretsCreateParams, opts ...RequestOption) (*SecretResponse, error) {
	var result SecretResponse
	_, err := s.client.request(ctx, "POST", "/v1/secrets", nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Get secret
func (s *SecretService) Get(ctx context.Context, name string, opts ...RequestOption) (*SecretResponse, error) {
	if name == "" {
		return nil, fmt.Errorf("retab: name is required")
	}
	var result SecretResponse
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/v1/secrets/%s", url.PathEscape(name)), nil, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// SecretsUpdateParams contains the parameters for Update.
type SecretsUpdateParams struct {
	Value string `json:"value" url:"-"`
}

// Update set Secret
func (s *SecretService) Update(ctx context.Context, name string, params *SecretsUpdateParams, opts ...RequestOption) (*SecretResponse, error) {
	if name == "" {
		return nil, fmt.Errorf("retab: name is required")
	}
	var result SecretResponse
	_, err := s.client.request(ctx, "PUT", fmt.Sprintf("/v1/secrets/%s", url.PathEscape(name)), nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Delete secret
func (s *SecretService) Delete(ctx context.Context, name string, opts ...RequestOption) error {
	if name == "" {
		return fmt.Errorf("retab: name is required")
	}
	_, err := s.client.request(ctx, "DELETE", fmt.Sprintf("/v1/secrets/%s", url.PathEscape(name)), nil, nil, nil, opts)
	return err
}
