// Code generated by oagen. DO NOT EDIT.

package retab

import (
	"context"
	"fmt"
	"net/url"
)

// TableService handles Tables operations.
type TableService struct {
	client *Client
}

// TablesListParams contains the parameters for List.
type TablesListParams struct {
	// ProjectID is only return tables belonging to this project.
	ProjectID *string `url:"project_id,omitempty" json:"-"`
}

// List table.List
func (s *TableService) List(ctx context.Context, params *TablesListParams, opts ...RequestOption) (*WorkflowTableListResponse, error) {
	var result WorkflowTableListResponse
	_, err := s.client.request(ctx, "GET", "/v1/tables", params, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// TablesCreateParams contains the parameters for Create.
type TablesCreateParams struct {
	Name                  string  `json:"name" url:"-"`
	File                  string  `json:"file" url:"-"`
	ColumnSchemaOverrides *string `json:"column_schema_overrides,omitempty" url:"-"`
	ProjectID             *string `json:"project_id,omitempty" url:"-"`
}

// Create table.Create
func (s *TableService) Create(ctx context.Context, params *TablesCreateParams, opts ...RequestOption) (*WorkflowTableListResponse, error) {
	var result WorkflowTableListResponse
	_, err := s.client.request(ctx, "POST", "/v1/tables", nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Get table.Get
func (s *TableService) Get(ctx context.Context, tableID string, opts ...RequestOption) (*WorkflowTableResponse, error) {
	if tableID == "" {
		return nil, fmt.Errorf("retab: table_id is required")
	}
	var result WorkflowTableResponse
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/v1/tables/%s", url.PathEscape(tableID)), nil, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// TablesReplaceParams contains the parameters for Replace.
type TablesReplaceParams struct {
	File                  string  `json:"file" url:"-"`
	ColumnSchemaOverrides *string `json:"column_schema_overrides,omitempty" url:"-"`
}

// Replace table.Replace
func (s *TableService) Replace(ctx context.Context, tableID string, params *TablesReplaceParams, opts ...RequestOption) (*WorkflowTableListResponse, error) {
	if tableID == "" {
		return nil, fmt.Errorf("retab: table_id is required")
	}
	var result WorkflowTableListResponse
	_, err := s.client.request(ctx, "PUT", fmt.Sprintf("/v1/tables/%s", url.PathEscape(tableID)), nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// TablesUpdateParams contains the parameters for Update.
type TablesUpdateParams struct {
	Name     *string                 `json:"name,omitempty" url:"-"`
	Metadata *map[string]interface{} `json:"metadata,omitempty" url:"-"`
}

// Update table.Update
func (s *TableService) Update(ctx context.Context, tableID string, params *TablesUpdateParams, opts ...RequestOption) (*WorkflowTableListResponse, error) {
	if tableID == "" {
		return nil, fmt.Errorf("retab: table_id is required")
	}
	var result WorkflowTableListResponse
	_, err := s.client.request(ctx, "PATCH", fmt.Sprintf("/v1/tables/%s", url.PathEscape(tableID)), nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Delete table.Delete
func (s *TableService) Delete(ctx context.Context, tableID string, opts ...RequestOption) error {
	if tableID == "" {
		return fmt.Errorf("retab: table_id is required")
	}
	_, err := s.client.request(ctx, "DELETE", fmt.Sprintf("/v1/tables/%s", url.PathEscape(tableID)), nil, nil, nil, opts)
	return err
}

// Download table.Download
func (s *TableService) Download(ctx context.Context, tableID string, opts ...RequestOption) error {
	if tableID == "" {
		return fmt.Errorf("retab: table_id is required")
	}
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/v1/tables/%s/download", url.PathEscape(tableID)), nil, nil, nil, opts)
	return err
}

// TablesProfileParams contains the parameters for Profile.
type TablesProfileParams struct {
	// Defaults to [].
	Select []string `url:"select,omitempty" json:"-"`
}

// Profile table.Get Profile
func (s *TableService) Profile(ctx context.Context, tableID string, params *TablesProfileParams, opts ...RequestOption) (*WorkflowTableProfileResponse, error) {
	if tableID == "" {
		return nil, fmt.Errorf("retab: table_id is required")
	}
	var result WorkflowTableProfileResponse
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/v1/tables/%s/profile", url.PathEscape(tableID)), params, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// TablesQueryParams contains the parameters for Query.
type TablesQueryParams struct {
	Body interface{} `json:"-"`
}

// Query table.Query
func (s *TableService) Query(ctx context.Context, tableID string, params *TablesQueryParams, opts ...RequestOption) (*WorkflowTableRowsResponse, error) {
	if tableID == "" {
		return nil, fmt.Errorf("retab: table_id is required")
	}
	var result WorkflowTableRowsResponse
	_, err := s.client.request(ctx, "POST", fmt.Sprintf("/v1/tables/%s/query", url.PathEscape(tableID)), nil, params.Body, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Schema table.Get Schema
func (s *TableService) Schema(ctx context.Context, tableID string, opts ...RequestOption) (*WorkflowTableSchemaResponse, error) {
	if tableID == "" {
		return nil, fmt.Errorf("retab: table_id is required")
	}
	var result WorkflowTableSchemaResponse
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/v1/tables/%s/schema", url.PathEscape(tableID)), nil, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// TablesValidateParams contains the parameters for Validate.
type TablesValidateParams struct {
	RequiredColumns []string                                       `json:"required_columns,omitempty" url:"-"`
	Columns         *map[string]*WorkflowTableValidationColumnRule `json:"columns,omitempty" url:"-"`
	Unique          [][]string                                     `json:"unique,omitempty" url:"-"`
}

// Validate table.Validate
func (s *TableService) Validate(ctx context.Context, tableID string, params *TablesValidateParams, opts ...RequestOption) (*WorkflowTableValidationResponse, error) {
	if tableID == "" {
		return nil, fmt.Errorf("retab: table_id is required")
	}
	var result WorkflowTableValidationResponse
	_, err := s.client.request(ctx, "POST", fmt.Sprintf("/v1/tables/%s/validate", url.PathEscape(tableID)), nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}
