// Code generated by oagen. DO NOT EDIT.

package retab

import (
	"context"
	"fmt"
	"net/url"
)

// WorkflowBlockService handles WorkflowBlocks operations.
type WorkflowBlockService struct {
	client     *Client
	Executions *WorkflowBlockExecutionService
}

// WorkflowBlocksListParams contains the parameters for List.
type WorkflowBlocksListParams struct {
	PaginationParams
	WorkflowID string `url:"workflow_id" json:"-"`
}

// List blocks
// List blocks for a workflow with keyset cursor pagination.
// Sorted by “updated_at“ descending with “id“ as the tiebreaker. Pass
// “after“ (the previous response's “list_metadata.after“) for the next
// page, “before“ for the previous page. They are mutually exclusive; the
// 400 cleanly tells the caller which to drop.
func (s *WorkflowBlockService) List(ctx context.Context, params *WorkflowBlocksListParams, opts ...RequestOption) (*PaginatedList[WorkflowBlock], error) {
	if params == nil {
		return nil, fmt.Errorf("retab: workflow_id is required")
	}
	if params.WorkflowID == "" {
		return nil, fmt.Errorf("retab: workflow_id is required")
	}
	return doPaginated[WorkflowBlock](ctx, s.client, "GET", "/v1/workflows/blocks", params, nil, opts...)
}

// WorkflowBlocksCreateParams contains the parameters for Create.
type WorkflowBlocksCreateParams struct {
	// WorkflowID is workflow to create the block in.
	WorkflowID string `json:"workflow_id" url:"-"`
	// ID is if omitted, the server generates an opaque ``blk_<nanoid>``. Opaque block ID. Omit to let the server generate one. Block IDs are unique per ORGANIZATION (not per workflow) — reusing a human-friendly id like 'block_extract' across multiple workflows in the same org will fail with 409. Prefer the server-generated ``blk_<nanoid>`` form for predictability.
	ID *string `json:"id,omitempty" url:"-"`
	// Type is block type
	Type WorkflowBlockCreateRequestType `json:"type" url:"-"`
	// Label is display label
	Label *string `json:"label,omitempty" url:"-"`
	// PositionX is x position
	PositionX *float64 `json:"position_x,omitempty" url:"-"`
	// PositionY is y position
	PositionY *float64 `json:"position_y,omitempty" url:"-"`
	// Width is block width
	Width *float64 `json:"width,omitempty" url:"-"`
	// Height is block height
	Height *float64 `json:"height,omitempty" url:"-"`
	// Config is block configuration
	Config map[string]interface{} `json:"config,omitempty" url:"-"`
	// ParentID is id of parent container block (while_loop, for_each)
	ParentID *string `json:"parent_id,omitempty" url:"-"`
}

// Create block
// Create a new block in a workflow.
// This creates a block in the live workflow_blocks collection.
func (s *WorkflowBlockService) Create(ctx context.Context, params *WorkflowBlocksCreateParams, opts ...RequestOption) (*WorkflowBlock, error) {
	var result WorkflowBlock
	_, err := s.client.request(ctx, "POST", "/v1/workflows/blocks", nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// WorkflowBlocksGetParams contains the parameters for Get.
type WorkflowBlocksGetParams struct {
	// WorkflowID is optional disambiguator for legacy duplicate block IDs. Required only when the block id is not unique within the org — in that case the unqualified call returns 409 listing the colliding workflow_ids. Newly-created blocks use server-generated opaque IDs and never need this.
	WorkflowID *string `url:"workflow_id,omitempty" json:"-"`
}

// Get block
// Get a single block by ID.
func (s *WorkflowBlockService) Get(ctx context.Context, blockID string, params *WorkflowBlocksGetParams, opts ...RequestOption) (*WorkflowBlock, error) {
	if blockID == "" {
		return nil, fmt.Errorf("retab: block_id is required")
	}
	var result WorkflowBlock
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/v1/workflows/blocks/%s", url.PathEscape(blockID)), params, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// WorkflowBlocksUpdateParams contains the parameters for Update.
type WorkflowBlocksUpdateParams struct {
	Label     *string                `json:"label,omitempty" url:"-"`
	PositionX *float64               `json:"position_x,omitempty" url:"-"`
	PositionY *float64               `json:"position_y,omitempty" url:"-"`
	Width     *float64               `json:"width,omitempty" url:"-"`
	Height    *float64               `json:"height,omitempty" url:"-"`
	Config    map[string]interface{} `json:"config,omitempty" url:"-"`
	ParentID  *string                `json:"parent_id,omitempty" url:"-"`
	// ConfigMode is how to apply the ``config`` field. 'merge' (default) deep-merges the patch into the existing config with null-as-delete; 'replace' uses the patch as the full new config. Not persisted.
	ConfigMode *UpdateWorkflowBlockRequestConfigMode `json:"config_mode,omitempty" url:"-"`
	// WorkflowID is optional disambiguator for legacy duplicate block IDs. See ``GET /blocks/{block_id}`` for the full rationale.
	WorkflowID *string `url:"workflow_id,omitempty" json:"-"`
}

// Update block
// Update a block with partial data.
// Only the provided fields are updated. This enables targeted updates
// like position changes without affecting other block properties.
func (s *WorkflowBlockService) Update(ctx context.Context, blockID string, params *WorkflowBlocksUpdateParams, opts ...RequestOption) (*WorkflowBlock, error) {
	if blockID == "" {
		return nil, fmt.Errorf("retab: block_id is required")
	}
	var result WorkflowBlock
	_, err := s.client.request(ctx, "PATCH", fmt.Sprintf("/v1/workflows/blocks/%s", url.PathEscape(blockID)), params, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// WorkflowBlocksDeleteParams contains the parameters for Delete.
type WorkflowBlocksDeleteParams struct {
	// WorkflowID is optional disambiguator for legacy duplicate block IDs. See ``GET /blocks/{block_id}`` for the full rationale.
	WorkflowID *string `url:"workflow_id,omitempty" json:"-"`
}

// Delete block
// Delete a block from a workflow.
// This also deletes any edges connected to this block.
func (s *WorkflowBlockService) Delete(ctx context.Context, blockID string, params *WorkflowBlocksDeleteParams, opts ...RequestOption) error {
	if blockID == "" {
		return fmt.Errorf("retab: block_id is required")
	}
	_, err := s.client.request(ctx, "DELETE", fmt.Sprintf("/v1/workflows/blocks/%s", url.PathEscape(blockID)), params, nil, nil, opts)
	return err
}
