// Code generated by oagen. DO NOT EDIT.

package retab

import (
	"context"
	"fmt"
	"net/url"
)

// WorkflowReviewService handles WorkflowReviews operations.
type WorkflowReviewService struct {
	client *Client
}

// WorkflowReviewsListParams contains the parameters for List.
type WorkflowReviewsListParams struct {
	PaginationParams
	WorkflowID   *string `url:"workflow_id,omitempty" json:"-"`
	RunID        *string `url:"run_id,omitempty" json:"-"`
	BlockID      *string `url:"block_id,omitempty" json:"-"`
	StepID       *string `url:"step_id,omitempty" json:"-"`
	IterationKey *string `url:"iteration_key,omitempty" json:"-"`
	// DecisionStatus is filter by decision state: pending, approved, rejected, decided, or all.
	// Defaults to "pending".
	DecisionStatus *ReviewDecisionStatus `url:"decision_status,omitempty" json:"-"`
}

// List reviews Route
// List reviews — the review queue, oldest first by “created_at“.
func (s *WorkflowReviewService) List(ctx context.Context, params *WorkflowReviewsListParams, opts ...RequestOption) (*PaginatedList[Review], error) {
	return doPaginated[Review](ctx, s.client, "GET", "/v1/workflows/reviews", params, nil, opts...)
}

// Get review Route
// Read one review's metadata + decision. Versions are fetched separately.
func (s *WorkflowReviewService) Get(ctx context.Context, reviewID string, opts ...RequestOption) (*Review, error) {
	if reviewID == "" {
		return nil, fmt.Errorf("retab: review_id is required")
	}
	var result Review
	_, err := s.client.request(ctx, "GET", fmt.Sprintf("/v1/workflows/reviews/%s", url.PathEscape(reviewID)), nil, nil, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// WorkflowReviewsApproveParams contains the parameters for Approve.
type WorkflowReviewsApproveParams struct {
	// VersionID is exact content-addressed key of the version to approve.
	VersionID string `json:"version_id" url:"-"`
}

// Approve review Route
// Approve one exact review version and resume the Temporal run.
// Earns its action-verb shape per the four criteria in
// “meta-pattern-blueprint.md“ §2: precondition (“decision is None“),
// side-effect dominates (Temporal resume signal), divergent request body vs
// “/reject“, divergent response (carries “resume_status“).
func (s *WorkflowReviewService) Approve(ctx context.Context, reviewID string, params *WorkflowReviewsApproveParams, opts ...RequestOption) (*SubmitDecisionResponse, error) {
	if reviewID == "" {
		return nil, fmt.Errorf("retab: review_id is required")
	}
	var result SubmitDecisionResponse
	_, err := s.client.request(ctx, "POST", fmt.Sprintf("/v1/workflows/reviews/%s/approve", url.PathEscape(reviewID)), nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// WorkflowReviewsRejectParams contains the parameters for Reject.
type WorkflowReviewsRejectParams struct {
	// VersionID is exact content-addressed key of the version to reject.
	VersionID string `json:"version_id" url:"-"`
	// Reason is required, non-empty rejection reason.
	Reason string `json:"reason" url:"-"`
}

// Reject review Route
// Reject one exact review version and resume the Temporal run.
// “reason“ is required by the request shape — "rejected without reason"
// is unrepresentable on the wire.
func (s *WorkflowReviewService) Reject(ctx context.Context, reviewID string, params *WorkflowReviewsRejectParams, opts ...RequestOption) (*SubmitDecisionResponse, error) {
	if reviewID == "" {
		return nil, fmt.Errorf("retab: review_id is required")
	}
	var result SubmitDecisionResponse
	_, err := s.client.request(ctx, "POST", fmt.Sprintf("/v1/workflows/reviews/%s/reject", url.PathEscape(reviewID)), nil, params, &result, opts)
	if err != nil {
		return nil, err
	}
	return &result, nil
}
