# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module Retab
  class ClassificationConsensus < Retab::Types::BaseModel

    HASH_ATTRS = {
      choices: :choices,
      likelihoods: :likelihoods
    }.freeze

    attr_accessor(
      :choices,
      :likelihoods
    )

    def initialize(json)
      super()
      hash = self.class.normalize(json)
      @choices = (hash[:choices] || []).map { |item| item ? Retab::ClassificationDecision.new(item) : nil }
      @likelihoods = hash[:likelihoods]
    end
  end
end
