// This file is auto-generated by the Retab oagen emitter. Do not edit by hand.

import type { Retab } from '../../../retab.js';
import { PaginatedList } from '../../../_pagination.js';
import type { StoredBlockExecution, StoredBlockExecutionResponse } from '../../../workflows/blocks/executions/interfaces/index.js';
import { deserializeStoredBlockExecution } from '../../../workflows/blocks/executions/interfaces/index.js';

export class WorkflowBlockExecutions {

  constructor(private readonly client: Retab) {
  }

  /** List Block Executions */
  async list(options: { runId: string; blockId: string; limit?: number; before?: string; after?: string; order?: 'asc' | 'desc' }): Promise<PaginatedList<StoredBlockExecution>> {
    return this.client._fetchPage(deserializeStoredBlockExecution, { method: 'GET', path: "/v1/workflows/blocks/executions", query: { "run_id": options?.runId, "block_id": options?.blockId, limit: options?.limit, before: options?.before, after: options?.after, order: options?.order }, body: undefined });
  }

  /** Create Block Execution */
  async create(runId: string, blockId: string, stepId?: string | null, nConsensus?: number | null, checkEligibility?: boolean): Promise<StoredBlockExecution> {
    const body = {
      "run_id": runId,
      "block_id": blockId,
      "step_id": stepId,
      "n_consensus": nConsensus,
      "check_eligibility": checkEligibility,
    };
    const __wire = await this.client.request<StoredBlockExecutionResponse>({ method: 'POST', path: "/v1/workflows/blocks/executions", query: undefined, body: body });
    return deserializeStoredBlockExecution(__wire);
  }
}
