# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# @oagen-ignore-file

require "test_helper"

class ClientConfigurationTest < Minitest::Test
  def test_client_accepts_base_url_alias
    client = Retab::Client.new(
      api_key: "sk_test_123",
      base_url: "http://localhost:4000/v1"
    )

    assert_equal("http://localhost:4000/v1", client.api_host)
  end

  def test_configuration_prefers_api_host_when_both_host_options_are_given
    client = Retab::Client.new(
      api_key: "sk_test_123",
      api_host: "http://localhost:4000/v1",
      base_url: "http://ignored.example/v1"
    )

    assert_equal("http://localhost:4000/v1", client.api_host)
  end
end
