// This file is auto-generated by oagen. Do not edit.

package com.retab;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import com.retab.classifications.ClassificationsApi;
import com.retab.edits.EditsApi;
import com.retab.extractions.ExtractionsApi;
import com.retab.files.FilesApi;
import com.retab.parses.ParsesApi;
import com.retab.partitions.PartitionsApi;
import com.retab.schemas.SchemasApi;
import com.retab.secrets.SecretsApi;
import com.retab.splits.SplitsApi;
import com.retab.tables.TablesApi;
import com.retab.usage.UsageApi;
import com.retab.workflows.WorkflowsApi;
import java.net.http.HttpClient;

public final class RetabClient {
  public static final String DEFAULT_BASE_URL = "https://api.retab.com";

  private final String apiKey;
  private final String baseUrl;
  private final HttpClient httpClient;
  private final ObjectMapper objectMapper;
  private final ClassificationsApi classifications;
  private final EditsApi edits;
  private final ExtractionsApi extractions;
  private final FilesApi files;
  private final ParsesApi parses;
  private final PartitionsApi partitions;
  private final SchemasApi schemas;
  private final SecretsApi secrets;
  private final SplitsApi splits;
  private final TablesApi tables;
  private final UsageApi usage;
  private final WorkflowsApi workflows;

  public RetabClient(String apiKey) {
    this(apiKey, DEFAULT_BASE_URL, defaultHttpClient(), defaultObjectMapper());
  }

  public RetabClient(String apiKey, String baseUrl) {
    this(apiKey, baseUrl, defaultHttpClient(), defaultObjectMapper());
  }

  public RetabClient(
      String apiKey, String baseUrl, HttpClient httpClient, ObjectMapper objectMapper) {
    this.apiKey = apiKey;
    this.baseUrl = baseUrl;
    this.httpClient = httpClient;
    this.objectMapper = objectMapper;
    this.classifications = new ClassificationsApi(this);
    this.edits = new EditsApi(this);
    this.extractions = new ExtractionsApi(this);
    this.files = new FilesApi(this);
    this.parses = new ParsesApi(this);
    this.partitions = new PartitionsApi(this);
    this.schemas = new SchemasApi(this);
    this.secrets = new SecretsApi(this);
    this.splits = new SplitsApi(this);
    this.tables = new TablesApi(this);
    this.usage = new UsageApi(this);
    this.workflows = new WorkflowsApi(this);
  }

  public String getApiKey() {
    return apiKey;
  }

  public String getBaseUrl() {
    return baseUrl;
  }

  public HttpClient getHttpClient() {
    return httpClient;
  }

  public ObjectMapper getObjectMapper() {
    return objectMapper;
  }

  public ClassificationsApi classifications() {
    return classifications;
  }

  public EditsApi edits() {
    return edits;
  }

  public ExtractionsApi extractions() {
    return extractions;
  }

  public FilesApi files() {
    return files;
  }

  public ParsesApi parses() {
    return parses;
  }

  public PartitionsApi partitions() {
    return partitions;
  }

  public SchemasApi schemas() {
    return schemas;
  }

  public SecretsApi secrets() {
    return secrets;
  }

  public SplitsApi splits() {
    return splits;
  }

  public TablesApi tables() {
    return tables;
  }

  public UsageApi usage() {
    return usage;
  }

  public WorkflowsApi workflows() {
    return workflows;
  }

  private static HttpClient defaultHttpClient() {
    return HttpClient.newBuilder().version(HttpClient.Version.HTTP_1_1).build();
  }

  private static ObjectMapper defaultObjectMapper() {
    return new ObjectMapper().registerModule(new JavaTimeModule());
  }
}
