// This file is auto-generated by the Retab oagen emitter. Do not edit by hand.

import { z } from 'zod';
/** The execution row exists but has not been dispatched. */
export interface PendingBlockExecutionLifecycle {
  /** @default "pending" */
  status: 'pending';
}

export interface PendingBlockExecutionLifecycleResponse {
  status: 'pending';
}

export const ZPendingBlockExecutionLifecycle = z.object({
  status: z.literal('pending'),
}) as z.ZodType<PendingBlockExecutionLifecycle>;

export function deserializePendingBlockExecutionLifecycle(
  wire: PendingBlockExecutionLifecycleResponse
): PendingBlockExecutionLifecycle {
  return {
    status: wire['status'],
  };
}

export function serializePendingBlockExecutionLifecycle(
  domain: PendingBlockExecutionLifecycle
): PendingBlockExecutionLifecycleResponse {
  return {
    status: domain['status'],
  };
}
