// This file is auto-generated by the Retab oagen emitter. Do not edit by hand.

import { z } from 'zod';
import type { FileRef, FileRefResponse } from './file-ref.interface.js';
import { ZFileRef } from './file-ref.interface.js';
import type { MIMEData, MIMEDataResponse } from '../../schemas/interfaces/mime-data.interface.js';
import { ZMIMEData } from '../../schemas/interfaces/mime-data.interface.js';

export interface ExtractionRequest {
  document: MIMEData | FileRef;
  /** JSON schema describing the structured output */
  jsonSchema: Record<string, unknown>;
  /**
   * The model to use for the extraction
   * @default "retab-small"
   */
  model?: string;
  /**
   * Resolution of the image sent to the LLM
   * @default 192
   */
  imageResolutionDpi?: number;
  /** Free-form instructions appended to the system prompt to steer the extraction. */
  instructions?: string | null;
  /**
   * Number of consensus extraction runs to perform. Uses deterministic single-pass when set to 1.
   * @default 1
   */
  nConsensus?: number;
  /** User-defined metadata to associate with this extraction */
  metadata?: Record<string, string> | null;
  /** Additional chat messages forwarded to the extraction model. */
  additionalMessages?: Record<string, unknown>[] | null;
  /**
   * If true, skip the LLM cache and force a fresh completion
   * @default false
   */
  bustCache?: boolean;
  /** @default false */
  stream?: boolean;
  chunkingKeys?: Record<string, string> | null;
}

export interface ExtractionRequestResponse {
  document: MIMEDataResponse | FileRefResponse;
  json_schema: Record<string, unknown>;
  model?: string;
  image_resolution_dpi?: number;
  instructions?: string | null;
  n_consensus?: number;
  metadata?: Record<string, string> | null;
  additional_messages?: Record<string, unknown>[] | null;
  bust_cache?: boolean;
  stream?: boolean;
  chunking_keys?: Record<string, string> | null;
}

export const ZExtractionRequest = z.object({
  document: z.union([ZMIMEData, ZFileRef]),
  jsonSchema: z.record(z.string(), z.unknown()),
  model: z.string().optional(),
  imageResolutionDpi: z.number().int().optional(),
  instructions: z.string().nullable().optional(),
  nConsensus: z.number().int().optional(),
  metadata: z.record(z.string(), z.string()).nullable().optional(),
  additionalMessages: z.record(z.string(), z.unknown()).array().nullable().optional(),
  bustCache: z.boolean().optional(),
  stream: z.boolean().optional(),
  chunkingKeys: z.record(z.string(), z.string()).nullable().optional(),
}) as z.ZodType<ExtractionRequest>;

export function deserializeExtractionRequest(wire: ExtractionRequestResponse): ExtractionRequest {
  return {
    document: wire['document'] as unknown as MIMEData | FileRef,
    jsonSchema: wire['json_schema'],
    model: wire['model'],
    imageResolutionDpi: wire['image_resolution_dpi'],
    instructions: wire['instructions'],
    nConsensus: wire['n_consensus'],
    metadata: wire['metadata'],
    additionalMessages: wire['additional_messages'],
    bustCache: wire['bust_cache'],
    stream: wire['stream'],
    chunkingKeys: wire['chunking_keys'],
  };
}
