// This file is auto-generated by the Retab oagen emitter. Do not edit by hand.

import { z } from 'zod';
import type {
  ExtractionConsensus,
  ExtractionConsensusResponse,
} from './extraction-consensus.interface.js';
import {
  ZExtractionConsensus,
  deserializeExtractionConsensus,
  serializeExtractionConsensus,
} from './extraction-consensus.interface.js';
import type {
  FileRef,
  FileRefResponse,
} from '../../classifications/interfaces/file-ref.interface.js';
import {
  ZFileRef,
  deserializeFileRef,
  serializeFileRef,
} from '../../classifications/interfaces/file-ref.interface.js';
import type {
  PrimitiveError,
  PrimitiveErrorResponse,
} from '../../classifications/interfaces/primitive-error.interface.js';
import {
  ZPrimitiveError,
  deserializePrimitiveError,
  serializePrimitiveError,
} from '../../classifications/interfaces/primitive-error.interface.js';
import type {
  RetabUsage,
  RetabUsageResponse,
} from '../../classifications/interfaces/retab-usage.interface.js';
import {
  ZRetabUsage,
  deserializeRetabUsage,
  serializeRetabUsage,
} from '../../classifications/interfaces/retab-usage.interface.js';
import type { ExtractionStatus } from './extraction-status.interface.js';
import { ZExtractionStatus } from './extraction-status.interface.js';

/** A stored extraction record from the Retab API. */
export interface Extraction {
  /** Unique identifier of the extraction */
  id: string;
  /** Information about the extracted file */
  file: FileRef;
  /** Model used for the extraction */
  model: string;
  /** JSON schema used for the extraction */
  jsonSchema: Record<string, unknown>;
  /**
   * Number of consensus votes used
   * @default 1
   */
  nConsensus?: number;
  /** Legacy stored DPI value, retained only for compatibility. */
  imageResolutionDpi?: number;
  /** Free-form instructions supplied with the extraction request. */
  instructions?: string | null;
  /** The extracted structured data */
  output: Record<string, unknown>;
  /**
   * Lifecycle status. The synchronous path returns 'completed'. Background runs progress pending -> queued -> in_progress -> completed | failed | cancelled.
   * @default "pending"
   */
  status?: ExtractionStatus;
  /** Error details when a background run fails; null otherwise. Always present so consumers can read it without an existence check. */
  error?: PrimitiveError | null;
  /** Consensus metadata for multi-vote extraction runs */
  consensus?: ExtractionConsensus | null;
  metadata?: Record<string, string> | null;
  /** Usage information for the extraction */
  usage?: RetabUsage | null;
  createdAt?: Date | null;
}

export interface ExtractionResponse {
  id: string;
  file: FileRefResponse;
  model: string;
  json_schema: Record<string, unknown>;
  n_consensus?: number;
  image_resolution_dpi?: number;
  instructions?: string | null;
  output: Record<string, unknown>;
  status?: ExtractionStatus;
  error?: PrimitiveErrorResponse | null;
  consensus?: ExtractionConsensusResponse | null;
  metadata?: Record<string, string> | null;
  usage?: RetabUsageResponse | null;
  created_at?: string | null;
}

export const ZExtraction = z.object({
  id: z.string(),
  file: ZFileRef,
  model: z.string(),
  jsonSchema: z.record(z.string(), z.unknown()),
  nConsensus: z.number().int().optional(),
  imageResolutionDpi: z.number().int().optional(),
  instructions: z.string().nullable().optional(),
  output: z.record(z.string(), z.unknown()),
  status: ZExtractionStatus.optional(),
  error: ZPrimitiveError.nullable().optional(),
  consensus: ZExtractionConsensus.nullable().optional(),
  metadata: z.record(z.string(), z.string()).nullable().optional(),
  usage: ZRetabUsage.nullable().optional(),
  createdAt: z.coerce.date().nullable().optional(),
}) as z.ZodType<Extraction>;

export function deserializeExtraction(wire: ExtractionResponse): Extraction {
  return {
    id: wire['id'],
    file: deserializeFileRef(wire['file']),
    model: wire['model'],
    jsonSchema: wire['json_schema'],
    nConsensus: wire['n_consensus'],
    imageResolutionDpi: wire['image_resolution_dpi'],
    instructions: wire['instructions'],
    output: wire['output'],
    status: wire['status'],
    error:
      wire['error'] == null
        ? (wire['error'] as undefined)
        : wire['error'] == null
          ? wire['error']
          : deserializePrimitiveError(wire['error']),
    consensus:
      wire['consensus'] == null
        ? (wire['consensus'] as undefined)
        : wire['consensus'] == null
          ? wire['consensus']
          : deserializeExtractionConsensus(wire['consensus']),
    metadata: wire['metadata'],
    usage:
      wire['usage'] == null
        ? (wire['usage'] as undefined)
        : wire['usage'] == null
          ? wire['usage']
          : deserializeRetabUsage(wire['usage']),
    createdAt:
      wire['created_at'] == null
        ? (wire['created_at'] as undefined)
        : wire['created_at'] == null
          ? wire['created_at']
          : new Date(wire['created_at']),
  };
}

export function serializeExtraction(domain: Extraction): ExtractionResponse {
  return {
    id: domain['id'],
    file: serializeFileRef(domain['file']),
    model: domain['model'],
    json_schema: domain['jsonSchema'],
    n_consensus: domain['nConsensus'],
    image_resolution_dpi: domain['imageResolutionDpi'],
    instructions: domain['instructions'],
    output: domain['output'],
    status: domain['status'],
    error:
      domain['error'] == null
        ? (domain['error'] as undefined)
        : domain['error'] == null
          ? domain['error']
          : serializePrimitiveError(domain['error']),
    consensus:
      domain['consensus'] == null
        ? (domain['consensus'] as undefined)
        : domain['consensus'] == null
          ? domain['consensus']
          : serializeExtractionConsensus(domain['consensus']),
    metadata: domain['metadata'],
    usage:
      domain['usage'] == null
        ? (domain['usage'] as undefined)
        : domain['usage'] == null
          ? domain['usage']
          : serializeRetabUsage(domain['usage']),
    created_at:
      domain['createdAt'] == null
        ? (domain['createdAt'] as undefined)
        : domain['createdAt'] == null
          ? domain['createdAt']
          : domain['createdAt'].toISOString(),
  };
}
