// This file is auto-generated by the Retab oagen emitter. Do not edit by hand.

import { z } from 'zod';
/** Usage information for document processing. */
export interface RetabUsage {
  /** Credits consumed for processing */
  credits: number;
}

export interface RetabUsageResponse {
  credits: number;
}

export const ZRetabUsage = z.object({
  credits: z.number(),
}) as z.ZodType<RetabUsage>;

export function deserializeRetabUsage(wire: RetabUsageResponse): RetabUsage {
  return {
    credits: wire['credits'],
  };
}
