// This file is auto-generated by the Retab oagen emitter. Do not edit by hand.

import { z } from 'zod';

export type SourceOptionsMode = 'located' | 'cited';

export const ZSourceOptionsMode = z.enum(['located', 'cited'] as const);
