// This file is auto-generated by the Retab oagen emitter. Do not edit by hand.

import { z } from 'zod';

export type SourceJobMode = 'located' | 'cited';

export const ZSourceJobMode = z.enum(['located', 'cited'] as const);
