// This file is auto-generated by the Retab oagen emitter. Do not edit by hand.

import { z } from 'zod';
import type {
  FileRef,
  FileRefResponse,
} from '../../classifications/interfaces/file-ref.interface.js';
import {
  ZFileRef,
  deserializeFileRef,
  serializeFileRef,
} from '../../classifications/interfaces/file-ref.interface.js';
import type { SourcesResponseDocumentType } from './sources-response-document-type.interface.js';
import { ZSourcesResponseDocumentType } from './sources-response-document-type.interface.js';

/** An extraction's output annotated with the source that backs each value. */
export interface SourcesResponse {
  /** @default "extraction.sources" */
  object: 'extraction.sources';
  /** ID of the extraction */
  extractionId: string;
  /** Detected document type of the source document */
  documentType: SourcesResponseDocumentType;
  /** Compatibility alias for source_document. */
  file: FileRef;
  /** Canonical source document metadata (id, filename, mime_type). */
  sourceDocument: FileRef;
  /** Original extraction output */
  extraction: Record<string, unknown>;
  /** Same shape as extraction but leaves are {value, source} objects. Non-null source entries include file_id. */
  sources: Record<string, unknown>;
}

export interface SourcesResponseResponse {
  object: 'extraction.sources';
  extraction_id: string;
  document_type: SourcesResponseDocumentType;
  file: FileRefResponse;
  source_document: FileRefResponse;
  extraction: Record<string, unknown>;
  sources: Record<string, unknown>;
}

export const ZSourcesResponse = z.object({
  object: z.literal('extraction.sources'),
  extractionId: z.string(),
  documentType: ZSourcesResponseDocumentType,
  file: ZFileRef,
  sourceDocument: ZFileRef,
  extraction: z.record(z.string(), z.unknown()),
  sources: z.record(z.string(), z.unknown()),
}) as z.ZodType<SourcesResponse>;

export function deserializeSourcesResponse(wire: SourcesResponseResponse): SourcesResponse {
  return {
    object: wire['object'],
    extractionId: wire['extraction_id'],
    documentType: wire['document_type'],
    file: deserializeFileRef(wire['file']),
    sourceDocument: deserializeFileRef(wire['source_document']),
    extraction: wire['extraction'],
    sources: wire['sources'],
  };
}

export function serializeSourcesResponse(domain: SourcesResponse): SourcesResponseResponse {
  return {
    object: domain['object'],
    extraction_id: domain['extractionId'],
    document_type: domain['documentType'],
    file: serializeFileRef(domain['file']),
    source_document: serializeFileRef(domain['sourceDocument']),
    extraction: domain['extraction'],
    sources: domain['sources'],
  };
}
