// This file is auto-generated by the Retab oagen emitter. Do not edit by hand.

import { z } from 'zod';
/** Public response returned when job completes successfully. */
export interface JobResponse {
  statusCode: number;
  body: Record<string, unknown>;
}

export interface JobResponseResponse {
  status_code: number;
  body: Record<string, unknown>;
}

export const ZJobResponse = z.object({
  statusCode: z.number().int(),
  body: z.record(z.string(), z.unknown()),
}) as z.ZodType<JobResponse>;

export function deserializeJobResponse(wire: JobResponseResponse): JobResponse {
  return {
    statusCode: wire['status_code'],
    body: wire['body'],
  };
}

export function serializeJobResponse(domain: JobResponse): JobResponseResponse {
  return {
    status_code: domain['statusCode'],
    body: domain['body'],
  };
}
