// This file is auto-generated by the Retab oagen emitter. Do not edit by hand.

import { z } from 'zod';
import type { SecretValue, SecretValueWire } from './secret-value.interface.js';
import {
  ZSecretValue,
  deserializeSecretValue,
  serializeSecretValue,
} from './secret-value.interface.js';

export interface SecretValueResponse {
  secret: SecretValue;
}

export interface SecretValueResponseResponse {
  secret: SecretValueWire;
}

export const ZSecretValueResponse = z.object({
  secret: ZSecretValue,
}) as z.ZodType<SecretValueResponse>;

export function deserializeSecretValueResponse(
  wire: SecretValueResponseResponse
): SecretValueResponse {
  return {
    secret: deserializeSecretValue(wire['secret']),
  };
}

export function serializeSecretValueResponse(
  domain: SecretValueResponse
): SecretValueResponseResponse {
  return {
    secret: serializeSecretValue(domain['secret']),
  };
}
