// This file is auto-generated by the Retab oagen emitter. Do not edit by hand.

import { z } from 'zod';
import type {
  AuthStatusEnvironment,
  AuthStatusEnvironmentResponse,
} from './auth-status-environment.interface.js';
import {
  ZAuthStatusEnvironment,
  deserializeAuthStatusEnvironment,
} from './auth-status-environment.interface.js';
import type { AuthStatusKey, AuthStatusKeyResponse } from './auth-status-key.interface.js';
import { ZAuthStatusKey, deserializeAuthStatusKey } from './auth-status-key.interface.js';

export interface AuthStatus {
  /** @default true */
  authenticated?: boolean;
  authMethod: string;
  environment?: AuthStatusEnvironment | null;
  key?: AuthStatusKey | null;
}

export interface AuthStatusResponse {
  authenticated?: boolean;
  auth_method: string;
  environment?: AuthStatusEnvironmentResponse | null;
  key?: AuthStatusKeyResponse | null;
}

export const ZAuthStatus = z.object({
  authenticated: z.boolean().optional(),
  authMethod: z.string(),
  environment: ZAuthStatusEnvironment.nullable().optional(),
  key: ZAuthStatusKey.nullable().optional(),
}) as z.ZodType<AuthStatus>;

export function deserializeAuthStatus(wire: AuthStatusResponse): AuthStatus {
  return {
    authenticated: wire['authenticated'],
    authMethod: wire['auth_method'],
    environment:
      wire['environment'] == null
        ? (wire['environment'] as undefined)
        : wire['environment'] == null
          ? wire['environment']
          : deserializeAuthStatusEnvironment(wire['environment']),
    key:
      wire['key'] == null
        ? (wire['key'] as undefined)
        : wire['key'] == null
          ? wire['key']
          : deserializeAuthStatusKey(wire['key']),
  };
}
