// This file is auto-generated by the Retab oagen emitter. Do not edit by hand.

import type { Retab } from '../retab.js';
import { coerceMimeData, type DocumentInput } from '../runtime/mime.js';
import type { SchemaGeneration, SchemaGenerationResponse } from '../schemas/interfaces/index.js';
import { deserializeSchemaGeneration } from '../schemas/interfaces/index.js';

export class Schemas {
  constructor(private readonly client: Retab) {}

  /** Generate Schema From Examples */
  async generate(
    documents: DocumentInput[],
    model?: string,
    instructions?: string | null,
    background?: boolean,
    imageResolutionDpi?: number
  ): Promise<SchemaGeneration> {
    const documentsCoerced = await Promise.all(
      documents.map((__d) =>
        coerceMimeData(__d, (__id) => this.client.files.get_download_link(__id))
      )
    );
    const body = {
      documents: documentsCoerced,
      model: model,
      instructions: instructions,
      background: background,
      image_resolution_dpi: imageResolutionDpi,
    };
    const __wire = await this.client.request<SchemaGenerationResponse>({
      method: 'POST',
      path: '/v1/schemas/generate',
      query: undefined,
      body: body,
    });
    return deserializeSchemaGeneration(__wire);
  }
}
