# This file is auto-generated by the Retab oagen emitter. Do not edit by hand.
from __future__ import annotations

from typing import Any
from io import IOBase
from pathlib import Path
import PIL.Image
from pydantic import HttpUrl

from retab._resource import AsyncAPIResource, SyncAPIResource
from retab.types.standards import PreparedRequest
from retab.types.pagination import AsyncPaginatedList, PaginatedList, PaginationOrder
from retab.utils.mime import prepare_mime_document
from retab.types.classifications import Category, Classification, ClassificationRequest
from retab.types.mime import FileRef, MIMEData


def _coerce_mime_document_input(document: Path | str | bytes | IOBase | FileRef | MIMEData | PIL.Image.Image | HttpUrl) -> FileRef | dict[str, Any]:
    if isinstance(document, FileRef):
        return document
    mime_data = prepare_mime_document(document)
    return {
        "filename": mime_data.filename,
        "url": mime_data.url,
        "mime_type": mime_data.mime_type,
    }


class ClassificationsMixin:
    def prepare_list(
        self,
        before: str | None = None,
        after: str | None = None,
        limit: int | None = 10,
        order: PaginationOrder | None = "desc",
        filename: str | None = None,
        from_date: str | None = None,
        to_date: str | None = None,
        **extra_params: Any,
    ) -> PreparedRequest:
        """List Classifications"""
        params: dict[str, Any] = {
            "before": before,
            "after": after,
            "limit": limit,
            "order": order,
            "filename": filename,
            "from_date": from_date,
            "to_date": to_date,
        }
        if extra_params:
            params.update(extra_params)
        params = {k: v for k, v in params.items() if v is not None}
        data = None
        return PreparedRequest(method="GET", url="/v1/classifications", params=params or None, data=data)

    def prepare_create(
        self,
        document: Path | str | bytes | IOBase | FileRef | MIMEData | PIL.Image.Image | HttpUrl,
        categories: list[Category],
        model: str = "retab-small",
        first_n_pages: int | None = None,
        instructions: str | None = None,
        n_consensus: int = 1,
        bust_cache: bool = False,
        **extra_params: Any,
    ) -> PreparedRequest:
        """Create Classification"""
        params: dict[str, Any] = {}
        if extra_params:
            params.update(extra_params)
        params = {k: v for k, v in params.items() if v is not None}
        if document is not None:
            document = _coerce_mime_document_input(document)
        payload = ClassificationRequest(
            document=document, categories=categories, model=model, first_n_pages=first_n_pages, instructions=instructions, n_consensus=n_consensus, bust_cache=bust_cache
        )
        data = payload.model_dump(mode="json", exclude_none=True, by_alias=True) if payload is not None else None
        return PreparedRequest(method="POST", url="/v1/classifications", params=params or None, data=data)

    def prepare_get(self, classification_id: str, **extra_params: Any) -> PreparedRequest:
        """Get Classification"""
        params: dict[str, Any] = {}
        if extra_params:
            params.update(extra_params)
        params = {k: v for k, v in params.items() if v is not None}
        data = None
        return PreparedRequest(method="GET", url=f"/v1/classifications/{classification_id}", params=params or None, data=data)

    def prepare_delete(self, classification_id: str, **extra_params: Any) -> PreparedRequest:
        """Delete Classification"""
        params: dict[str, Any] = {}
        if extra_params:
            params.update(extra_params)
        params = {k: v for k, v in params.items() if v is not None}
        data = None
        return PreparedRequest(method="DELETE", url=f"/v1/classifications/{classification_id}", params=params or None, data=data)


class Classifications(SyncAPIResource, ClassificationsMixin):
    """Classifications API wrapper."""

    def list(
        self,
        before: str | None = None,
        after: str | None = None,
        limit: int | None = 10,
        order: PaginationOrder | None = "desc",
        filename: str | None = None,
        from_date: str | None = None,
        to_date: str | None = None,
        **extra_params: Any,
    ) -> PaginatedList[Classification]:
        """List Classifications"""
        request = self.prepare_list(before=before, after=after, limit=limit, order=order, filename=filename, from_date=from_date, to_date=to_date, **extra_params)
        return self.request_page(request, model=Classification)

    def create(
        self,
        document: Path | str | bytes | IOBase | FileRef | MIMEData | PIL.Image.Image | HttpUrl,
        categories: list[Category],
        model: str = "retab-small",
        first_n_pages: int | None = None,
        instructions: str | None = None,
        n_consensus: int = 1,
        bust_cache: bool = False,
        **extra_params: Any,
    ) -> Classification:
        """Create Classification"""
        request = self.prepare_create(
            document=document,
            categories=categories,
            model=model,
            first_n_pages=first_n_pages,
            instructions=instructions,
            n_consensus=n_consensus,
            bust_cache=bust_cache,
            **extra_params,
        )
        response = self._client._prepared_request(request)
        return Classification.model_validate(response)

    def get(self, classification_id: str, **extra_params: Any) -> Classification:
        """Get Classification"""
        request = self.prepare_get(classification_id, **extra_params)
        response = self._client._prepared_request(request)
        return Classification.model_validate(response)

    def delete(self, classification_id: str, **extra_params: Any) -> None:
        """Delete Classification"""
        request = self.prepare_delete(classification_id, **extra_params)
        response = self._client._prepared_request(request)
        return None


class AsyncClassifications(AsyncAPIResource, ClassificationsMixin):
    """Async Classifications API wrapper."""

    async def list(
        self,
        before: str | None = None,
        after: str | None = None,
        limit: int | None = 10,
        order: PaginationOrder | None = "desc",
        filename: str | None = None,
        from_date: str | None = None,
        to_date: str | None = None,
        **extra_params: Any,
    ) -> AsyncPaginatedList[Classification]:
        """List Classifications"""
        request = self.prepare_list(before=before, after=after, limit=limit, order=order, filename=filename, from_date=from_date, to_date=to_date, **extra_params)
        return await self.request_page(request, model=Classification)

    async def create(
        self,
        document: Path | str | bytes | IOBase | FileRef | MIMEData | PIL.Image.Image | HttpUrl,
        categories: list[Category],
        model: str = "retab-small",
        first_n_pages: int | None = None,
        instructions: str | None = None,
        n_consensus: int = 1,
        bust_cache: bool = False,
        **extra_params: Any,
    ) -> Classification:
        """Create Classification"""
        request = self.prepare_create(
            document=document,
            categories=categories,
            model=model,
            first_n_pages=first_n_pages,
            instructions=instructions,
            n_consensus=n_consensus,
            bust_cache=bust_cache,
            **extra_params,
        )
        response = await self._client._prepared_request(request)
        return Classification.model_validate(response)

    async def get(self, classification_id: str, **extra_params: Any) -> Classification:
        """Get Classification"""
        request = self.prepare_get(classification_id, **extra_params)
        response = await self._client._prepared_request(request)
        return Classification.model_validate(response)

    async def delete(self, classification_id: str, **extra_params: Any) -> None:
        """Delete Classification"""
        request = self.prepare_delete(classification_id, **extra_params)
        response = await self._client._prepared_request(request)
        return None


__all__ = ["Classifications", "AsyncClassifications", "ClassificationsMixin"]
