# This file is auto-generated by the Retab oagen emitter. Do not edit by hand.
from __future__ import annotations
# ruff: noqa: F401

from typing import Any, cast

from retab._resource import AsyncAPIResource, SyncAPIResource
from retab.types.standards import PreparedRequest
from retab.types.consensus import CreateConsensusRequest, ReconciliationResult


class ConsensusMixin:
    _client: Any

    def prepare_create(
        self, inputs: list[dict[str, Any]] | None, include_alignment: bool | None = None, json_schema: dict[str, Any] | None = None, **extra_params: Any
    ) -> PreparedRequest:
        """Create Consensus Reconcile several objects into one. Takes a list of `inputs` that describe the same thing — typically the outputs of repeated extractions — and returns a single `consensus` object plus a `likelihoods` map giving the agreement score for every leaf path. Inputs are always aligned before the vote, so items in a list are matched across inputs by content rather than by position; a…"""
        params: dict[str, Any] = {}
        if extra_params:
            params.update(extra_params)
        params = {k: v for k, v in params.items() if v is not None}
        payload = CreateConsensusRequest(include_alignment=cast(Any, include_alignment), inputs=cast(Any, inputs), json_schema=cast(Any, json_schema))
        data = payload.model_dump(mode="json", exclude_none=True, by_alias=True) if payload is not None else None
        return PreparedRequest(method="POST", url="/v1/consensus", params=params or None, data=data)


class Consensus(SyncAPIResource, ConsensusMixin):
    """Consensus API wrapper."""

    def create(
        self, inputs: list[dict[str, Any]] | None, include_alignment: bool | None = None, json_schema: dict[str, Any] | None = None, **extra_params: Any
    ) -> ReconciliationResult:
        """Create Consensus Reconcile several objects into one. Takes a list of `inputs` that describe the same thing — typically the outputs of repeated extractions — and returns a single `consensus` object plus a `likelihoods` map giving the agreement score for every leaf path. Inputs are always aligned before the vote, so items in a list are matched across inputs by content rather than by position; a…"""
        prepared_request = self.prepare_create(include_alignment=include_alignment, inputs=inputs, json_schema=json_schema, **extra_params)
        response = self._client._prepared_request(prepared_request)
        return ReconciliationResult.model_validate(response)


class AsyncConsensus(AsyncAPIResource, ConsensusMixin):
    """Async Consensus API wrapper."""

    async def create(
        self, inputs: list[dict[str, Any]] | None, include_alignment: bool | None = None, json_schema: dict[str, Any] | None = None, **extra_params: Any
    ) -> ReconciliationResult:
        """Create Consensus Reconcile several objects into one. Takes a list of `inputs` that describe the same thing — typically the outputs of repeated extractions — and returns a single `consensus` object plus a `likelihoods` map giving the agreement score for every leaf path. Inputs are always aligned before the vote, so items in a list are matched across inputs by content rather than by position; a…"""
        prepared_request = self.prepare_create(include_alignment=include_alignment, inputs=inputs, json_schema=json_schema, **extra_params)
        response = await self._client._prepared_request(prepared_request)
        return ReconciliationResult.model_validate(response)


__all__ = ["Consensus", "AsyncConsensus", "ConsensusMixin"]
