# This file is auto-generated by the Retab oagen emitter. Do not edit by hand.
from __future__ import annotations

from typing import Any

from retab._resource import AsyncAPIResource, SyncAPIResource
from retab.types.standards import PreparedRequest
from retab.types.pagination import AsyncPaginatedList, PaginatedList, PaginationOrder
from retab.types.jobs import CreateJobRequest, CreateJobRequestEndpoint, Job
from retab.types.schemas import JobsEndpoint, JobsSource, JobsStatus


class JobsMixin:
    def prepare_list(
        self,
        before: str | None = None,
        after: str | None = None,
        limit: int | None = 20,
        order: PaginationOrder | None = "desc",
        job_id: str | None = None,
        status: JobsStatus | None = None,
        endpoint: JobsEndpoint | None = None,
        source: JobsSource | None = None,
        project_id: str | None = None,
        workflow_id: str | None = None,
        workflow_block_id: str | None = None,
        model: str | None = None,
        filename_regex: str | None = None,
        filename_contains: str | None = None,
        document_type: list[str] | None = None,
        from_date: str | None = None,
        to_date: str | None = None,
        metadata: str | None = None,
        include_request: bool | None = False,
        include_response: bool | None = False,
        **extra_params: Any,
    ) -> PreparedRequest:
        """List Jobs List jobs with pagination and optional status filtering."""
        params: dict[str, Any] = {
            "before": before,
            "after": after,
            "limit": limit,
            "order": order,
            "job_id": job_id,
            "status": status,
            "endpoint": endpoint,
            "source": source,
            "project_id": project_id,
            "workflow_id": workflow_id,
            "workflow_block_id": workflow_block_id,
            "model": model,
            "filename_regex": filename_regex,
            "filename_contains": filename_contains,
            "document_type": document_type,
            "from_date": from_date,
            "to_date": to_date,
            "metadata": metadata,
            "include_request": include_request,
            "include_response": include_response,
        }
        if extra_params:
            params.update(extra_params)
        params = {k: v for k, v in params.items() if v is not None}
        data = None
        return PreparedRequest(method="GET", url="/v1/jobs", params=params or None, data=data)

    def prepare_create(self, endpoint: CreateJobRequestEndpoint, request: dict[str, Any], metadata: dict[str, str] | None = None, **extra_params: Any) -> PreparedRequest:
        """Create Job Create a new asynchronous job. The job will be queued for processing and can be polled for status using the retrieve endpoint."""
        params: dict[str, Any] = {}
        if extra_params:
            params.update(extra_params)
        params = {k: v for k, v in params.items() if v is not None}
        payload = CreateJobRequest(endpoint=endpoint, request=request, metadata=metadata)
        data = payload.model_dump(mode="json", exclude_none=True, by_alias=True) if payload is not None else None
        return PreparedRequest(method="POST", url="/v1/jobs", params=params or None, data=data)

    def prepare_get(self, job_id: str, include_request: bool | None = False, include_response: bool | None = False, **extra_params: Any) -> PreparedRequest:
        """Retrieve Job"""
        params: dict[str, Any] = {
            "include_request": include_request,
            "include_response": include_response,
        }
        if extra_params:
            params.update(extra_params)
        params = {k: v for k, v in params.items() if v is not None}
        data = None
        return PreparedRequest(method="GET", url=f"/v1/jobs/{job_id}", params=params or None, data=data)

    def prepare_cancel(self, job_id: str, **extra_params: Any) -> PreparedRequest:
        """Cancel Job Cancel an in-progress or queued job. Returns the updated job with status 'cancelled'."""
        params: dict[str, Any] = {}
        if extra_params:
            params.update(extra_params)
        params = {k: v for k, v in params.items() if v is not None}
        data = None
        return PreparedRequest(method="POST", url=f"/v1/jobs/{job_id}/cancel", params=params or None, data=data)

    def prepare_retry(self, job_id: str, **extra_params: Any) -> PreparedRequest:
        """Retry Job Retry a failed/cancelled/expired job in-place (same job ID). The job is reset to queued and processed again."""
        params: dict[str, Any] = {}
        if extra_params:
            params.update(extra_params)
        params = {k: v for k, v in params.items() if v is not None}
        data = None
        return PreparedRequest(method="POST", url=f"/v1/jobs/{job_id}/retry", params=params or None, data=data)


class Jobs(SyncAPIResource, JobsMixin):
    """Jobs API wrapper."""

    def list(
        self,
        before: str | None = None,
        after: str | None = None,
        limit: int | None = 20,
        order: PaginationOrder | None = "desc",
        job_id: str | None = None,
        status: JobsStatus | None = None,
        endpoint: JobsEndpoint | None = None,
        source: JobsSource | None = None,
        project_id: str | None = None,
        workflow_id: str | None = None,
        workflow_block_id: str | None = None,
        model: str | None = None,
        filename_regex: str | None = None,
        filename_contains: str | None = None,
        document_type: list[str] | None = None,
        from_date: str | None = None,
        to_date: str | None = None,
        metadata: str | None = None,
        include_request: bool | None = False,
        include_response: bool | None = False,
        **extra_params: Any,
    ) -> PaginatedList[Job]:
        """List Jobs List jobs with pagination and optional status filtering."""
        request = self.prepare_list(
            before=before,
            after=after,
            limit=limit,
            order=order,
            job_id=job_id,
            status=status,
            endpoint=endpoint,
            source=source,
            project_id=project_id,
            workflow_id=workflow_id,
            workflow_block_id=workflow_block_id,
            model=model,
            filename_regex=filename_regex,
            filename_contains=filename_contains,
            document_type=document_type,
            from_date=from_date,
            to_date=to_date,
            metadata=metadata,
            include_request=include_request,
            include_response=include_response,
            **extra_params,
        )
        return self.request_page(request, model=Job)

    def create(self, endpoint: CreateJobRequestEndpoint, request: dict[str, Any], metadata: dict[str, str] | None = None, **extra_params: Any) -> Job:
        """Create Job Create a new asynchronous job. The job will be queued for processing and can be polled for status using the retrieve endpoint."""
        request = self.prepare_create(endpoint=endpoint, request=request, metadata=metadata, **extra_params)
        response = self._client._prepared_request(request)
        return Job.model_validate(response)

    def get(self, job_id: str, include_request: bool | None = False, include_response: bool | None = False, **extra_params: Any) -> Job:
        """Retrieve Job"""
        request = self.prepare_get(job_id, include_request=include_request, include_response=include_response, **extra_params)
        response = self._client._prepared_request(request)
        return Job.model_validate(response)

    def cancel(self, job_id: str, **extra_params: Any) -> Job:
        """Cancel Job Cancel an in-progress or queued job. Returns the updated job with status 'cancelled'."""
        request = self.prepare_cancel(job_id, **extra_params)
        response = self._client._prepared_request(request)
        return Job.model_validate(response)

    def retry(self, job_id: str, **extra_params: Any) -> Job:
        """Retry Job Retry a failed/cancelled/expired job in-place (same job ID). The job is reset to queued and processed again."""
        request = self.prepare_retry(job_id, **extra_params)
        response = self._client._prepared_request(request)
        return Job.model_validate(response)


class AsyncJobs(AsyncAPIResource, JobsMixin):
    """Async Jobs API wrapper."""

    async def list(
        self,
        before: str | None = None,
        after: str | None = None,
        limit: int | None = 20,
        order: PaginationOrder | None = "desc",
        job_id: str | None = None,
        status: JobsStatus | None = None,
        endpoint: JobsEndpoint | None = None,
        source: JobsSource | None = None,
        project_id: str | None = None,
        workflow_id: str | None = None,
        workflow_block_id: str | None = None,
        model: str | None = None,
        filename_regex: str | None = None,
        filename_contains: str | None = None,
        document_type: list[str] | None = None,
        from_date: str | None = None,
        to_date: str | None = None,
        metadata: str | None = None,
        include_request: bool | None = False,
        include_response: bool | None = False,
        **extra_params: Any,
    ) -> AsyncPaginatedList[Job]:
        """List Jobs List jobs with pagination and optional status filtering."""
        request = self.prepare_list(
            before=before,
            after=after,
            limit=limit,
            order=order,
            job_id=job_id,
            status=status,
            endpoint=endpoint,
            source=source,
            project_id=project_id,
            workflow_id=workflow_id,
            workflow_block_id=workflow_block_id,
            model=model,
            filename_regex=filename_regex,
            filename_contains=filename_contains,
            document_type=document_type,
            from_date=from_date,
            to_date=to_date,
            metadata=metadata,
            include_request=include_request,
            include_response=include_response,
            **extra_params,
        )
        return await self.request_page(request, model=Job)

    async def create(self, endpoint: CreateJobRequestEndpoint, request: dict[str, Any], metadata: dict[str, str] | None = None, **extra_params: Any) -> Job:
        """Create Job Create a new asynchronous job. The job will be queued for processing and can be polled for status using the retrieve endpoint."""
        request = self.prepare_create(endpoint=endpoint, request=request, metadata=metadata, **extra_params)
        response = await self._client._prepared_request(request)
        return Job.model_validate(response)

    async def get(self, job_id: str, include_request: bool | None = False, include_response: bool | None = False, **extra_params: Any) -> Job:
        """Retrieve Job"""
        request = self.prepare_get(job_id, include_request=include_request, include_response=include_response, **extra_params)
        response = await self._client._prepared_request(request)
        return Job.model_validate(response)

    async def cancel(self, job_id: str, **extra_params: Any) -> Job:
        """Cancel Job Cancel an in-progress or queued job. Returns the updated job with status 'cancelled'."""
        request = self.prepare_cancel(job_id, **extra_params)
        response = await self._client._prepared_request(request)
        return Job.model_validate(response)

    async def retry(self, job_id: str, **extra_params: Any) -> Job:
        """Retry Job Retry a failed/cancelled/expired job in-place (same job ID). The job is reset to queued and processed again."""
        request = self.prepare_retry(job_id, **extra_params)
        response = await self._client._prepared_request(request)
        return Job.model_validate(response)


__all__ = ["Jobs", "AsyncJobs", "JobsMixin"]
