// This file is auto-generated by the Retab oagen emitter. Do not edit by hand.

import type { Retab } from '../../retab.js';
import { PaginatedList } from '../../_pagination.js';
import { coerceMimeData, type DocumentInput } from '../../runtime/mime.js';
import type { FormField } from '../../edits/interfaces/index.js';
import type { EditTemplate, EditTemplateResponse } from '../../edits/templates/interfaces/index.js';
import { serializeFormField } from '../../edits/interfaces/index.js';
import { deserializeEditTemplate } from '../../edits/templates/interfaces/index.js';

export class EditTemplates {
  constructor(private readonly client: Retab) {}

  /** List Templates */
  async list(options?: {
    name?: string | null | undefined;
    sortBy?: string | undefined;
    limit?: number;
    before?: string;
    after?: string;
    order?: 'asc' | 'desc';
  }): Promise<PaginatedList<EditTemplate>> {
    return this.client._fetchPage(deserializeEditTemplate, {
      method: 'GET',
      path: '/v1/edits/templates',
      query: {
        name: options?.name,
        sort_by: options?.sortBy,
        limit: options?.limit,
        before: options?.before,
        after: options?.after,
        order: options?.order,
      },
      body: undefined,
    });
  }

  /** Create Template */
  async create(
    name: string,
    document: DocumentInput,
    formFields: FormField[]
  ): Promise<EditTemplate> {
    const documentCoerced = await coerceMimeData(document);
    const body = {
      name: name,
      document: documentCoerced,
      form_fields: formFields.map((__i) => serializeFormField(__i)),
    };
    const __wire = await this.client.request<EditTemplateResponse>({
      method: 'POST',
      path: '/v1/edits/templates',
      query: undefined,
      body: body,
    });
    return deserializeEditTemplate(__wire);
  }

  /** Get Template */
  async get(templateId: string): Promise<EditTemplate> {
    const __wire = await this.client.request<EditTemplateResponse>({
      method: 'GET',
      path: `/v1/edits/templates/${templateId}`,
      query: undefined,
      body: undefined,
    });
    return deserializeEditTemplate(__wire);
  }

  /** Update Template */
  async update(
    templateId: string,
    name?: string | null,
    formFields?: FormField[] | null
  ): Promise<EditTemplate> {
    const body = {
      name: name,
      form_fields:
        formFields === undefined
          ? undefined
          : formFields == null
            ? formFields
            : formFields.map((__i) => serializeFormField(__i)),
    };
    const __wire = await this.client.request<EditTemplateResponse>({
      method: 'PATCH',
      path: `/v1/edits/templates/${templateId}`,
      query: undefined,
      body: body,
    });
    return deserializeEditTemplate(__wire);
  }

  /** Delete Template */
  async delete(templateId: string): Promise<void> {
    await this.client.request<unknown>({
      method: 'DELETE',
      path: `/v1/edits/templates/${templateId}`,
      query: undefined,
      body: undefined,
    });
  }
}
