// This file is auto-generated by the Retab oagen emitter. Do not edit by hand.

// Exception hierarchy for the Retab SDK. Emitted by the oagen Node emitter
// — do not hand-edit. Consumers can subclass these to add their own error
// envelope, or wrap fetch via `RetabOptions.fetch` to translate errors.

export class RetabError extends Error {
  constructor(
    message: string,
    public readonly status: number,
    public readonly responseBody: string,
  ) {
    super(message);
    this.name = 'RetabError';
  }
}

export class RetabAuthenticationError extends RetabError {
  constructor(status: number, body: string) {
    super('Retab authentication failed', status, body);
    this.name = 'RetabAuthenticationError';
  }
}

export class RetabPermissionError extends RetabError {
  constructor(status: number, body: string) {
    super('Retab request not permitted', status, body);
    this.name = 'RetabPermissionError';
  }
}

export class RetabNotFoundError extends RetabError {
  constructor(status: number, body: string) {
    super('Retab resource not found', status, body);
    this.name = 'RetabNotFoundError';
  }
}

export class RetabRateLimitError extends RetabError {
  constructor(status: number, body: string) {
    super('Retab rate limit exceeded', status, body);
    this.name = 'RetabRateLimitError';
  }
}

export function parseRetabError(status: number, body: string): RetabError {
  if (status === 401) return new RetabAuthenticationError(status, body);
  if (status === 403) return new RetabPermissionError(status, body);
  if (status === 404) return new RetabNotFoundError(status, body);
  if (status === 429) return new RetabRateLimitError(status, body);
  return new RetabError(`Retab API error (${status})`, status, body);
}
