// This file is auto-generated by oagen. Do not edit.

namespace Retab
{
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents sources response document type values.</summary>
    [JsonConverter(typeof(RetabNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(RetabStringEnumConverterFactory))]
    public enum SourcesResponseDocumentType
    {
        [EnumMember(Value = "unknown")]
        Unknown,

        [EnumMember(Value = "pdf")]
        Pdf,
        [EnumMember(Value = "image")]
        Image,
        [EnumMember(Value = "csv")]
        Csv,
        [EnumMember(Value = "xlsx")]
        Xlsx,
        [EnumMember(Value = "docx")]
        Docx,
        [EnumMember(Value = "txt")]
        Txt,
    }
}
