// This file is auto-generated by the Retab oagen emitter. Do not edit by hand.

import { z } from 'zod';
/** Request body for POST /v1/workflows/tests/runs. Use exactly one of the single-test, target, or all-tests shapes. */
export type CreateWorkflowTestRunRequest = object;

export type CreateWorkflowTestRunRequestResponse = object;

export const ZCreateWorkflowTestRunRequest = z.object(
  {}
) as z.ZodType<CreateWorkflowTestRunRequest>;

export function deserializeCreateWorkflowTestRunRequest(
  wire: CreateWorkflowTestRunRequestResponse
): CreateWorkflowTestRunRequest {
  return wire as CreateWorkflowTestRunRequest;
}
