// This file is auto-generated by the Retab oagen emitter. Do not edit by hand.

import { z } from 'zod';
/** Run every workflow test for one block in the workflow. */
export interface WorkflowTestRunBlockScope {
  type: 'block';
  blockId: string;
}

export interface WorkflowTestRunBlockScopeResponse {
  type: 'block';
  block_id: string;
}

export const ZWorkflowTestRunBlockScope = z.object({
  type: z.literal('block'),
  blockId: z.string(),
}) as z.ZodType<WorkflowTestRunBlockScope>;

export function deserializeWorkflowTestRunBlockScope(
  wire: WorkflowTestRunBlockScopeResponse
): WorkflowTestRunBlockScope {
  return {
    type: wire['type'],
    blockId: wire['block_id'],
  };
}
