// This file is auto-generated by oagen. Do not edit.

package com.retab.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

@JsonIgnoreProperties(ignoreUnknown = true)
public final class AllItemsMatchCondition {
  private final String kind;
  private final ExistCondition condition;

  @JsonCreator
  public AllItemsMatchCondition(
      @JsonProperty(value = "kind", required = false) String kind,
      @JsonProperty(value = "condition", required = true) ExistCondition condition) {
    this.kind = kind;
    this.condition = condition;
  }

  @JsonProperty("kind")
  public String getKind() {
    return kind;
  }

  @JsonProperty("condition")
  public ExistCondition getCondition() {
    return condition;
  }
}
