// This file is auto-generated by oagen. Do not edit.

package com.retab.models;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

/**
 * Discriminated union over BlockExecutionLifecycle variants, selected by the {@code status}
 * discriminator.
 *
 * <p>Jackson deserializes the wire JSON into the correct concrete variant, so all variant-specific
 * fields round-trip losslessly. Branch on the concrete type to read variant data:
 *
 * <pre>{@code
 * BlockExecutionLifecycle value = api.get(...);
 * if (value instanceof CancelledBlockExecutionLifecycle v) {
 *     handle(v);
 * }
 * }</pre>
 */
@JsonTypeInfo(
    use = JsonTypeInfo.Id.NAME,
    include = JsonTypeInfo.As.EXISTING_PROPERTY,
    property = "status",
    visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = CancelledBlockExecutionLifecycle.class, name = "cancelled"),
  @JsonSubTypes.Type(value = CompletedBlockExecutionLifecycle.class, name = "completed"),
  @JsonSubTypes.Type(value = ErrorBlockExecutionLifecycle.class, name = "error"),
  @JsonSubTypes.Type(value = PendingBlockExecutionLifecycle.class, name = "pending"),
  @JsonSubTypes.Type(value = QueuedBlockExecutionLifecycle.class, name = "queued"),
  @JsonSubTypes.Type(value = RunningBlockExecutionLifecycle.class, name = "running"),
  @JsonSubTypes.Type(value = SkippedBlockExecutionLifecycle.class, name = "skipped")
})
public sealed interface BlockExecutionLifecycle
    permits CancelledBlockExecutionLifecycle,
        CompletedBlockExecutionLifecycle,
        ErrorBlockExecutionLifecycle,
        PendingBlockExecutionLifecycle,
        QueuedBlockExecutionLifecycle,
        RunningBlockExecutionLifecycle,
        SkippedBlockExecutionLifecycle {}
