// This file is auto-generated by oagen. Do not edit.

package com.retab.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

@JsonIgnoreProperties(ignoreUnknown = true)
public final class CancelWorkflowExperimentRunResponse {
  private final String id;
  private final PendingWorkflowExperimentRun lifecycle;

  @JsonCreator
  public CancelWorkflowExperimentRunResponse(
      @JsonProperty(value = "id", required = true) String id,
      @JsonProperty(value = "lifecycle", required = true) PendingWorkflowExperimentRun lifecycle) {
    this.id = id;
    this.lifecycle = lifecycle;
  }

  @JsonProperty("id")
  public String getId() {
    return id;
  }

  @JsonProperty("lifecycle")
  public PendingWorkflowExperimentRun getLifecycle() {
    return lifecycle;
  }
}
