// This file is auto-generated by oagen. Do not edit.

package com.retab.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

@JsonIgnoreProperties(ignoreUnknown = true)
public final class CancelledStepLifecycle {
  private final String status;
  private final String reason;

  @JsonCreator
  public CancelledStepLifecycle(
      @JsonProperty(value = "status", required = false) String status,
      @JsonProperty(value = "reason", required = true) String reason) {
    this.status = status;
    this.reason = reason;
  }

  @JsonProperty("status")
  public String getStatus() {
    return status;
  }

  @JsonProperty("reason")
  public String getReason() {
    return reason;
  }
}
