// This file is auto-generated by oagen. Do not edit.

package com.retab.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

@JsonIgnoreProperties(ignoreUnknown = true)
public final class DeclarativeWorkflowRequest {
  private final String yamlDefinition;

  @JsonCreator
  public DeclarativeWorkflowRequest(
      @JsonProperty(value = "yaml_definition", required = true) String yamlDefinition) {
    this.yamlDefinition = yamlDefinition;
  }

  @JsonProperty("yaml_definition")
  public String getYamlDefinition() {
    return yamlDefinition;
  }
}
