// This file is auto-generated by oagen. Do not edit.

package com.retab.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

@JsonIgnoreProperties(ignoreUnknown = true)
public final class EditConfig {
  private final String color;

  @JsonCreator
  public EditConfig(@JsonProperty(value = "color", required = false) String color) {
    this.color = color != null ? color : "#000080";
  }

  @JsonProperty("color")
  public String getColor() {
    return color;
  }
}
