// This file is auto-generated by oagen. Do not edit.

package com.retab.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

@JsonIgnoreProperties(ignoreUnknown = true)
public final class ExperimentByDocumentMetricsResponse implements Experiment {
  private final String runId;
  private final String kind;
  private final String view;
  private final ExperimentMetricDocumentRef document;
  private final Double score;
  private final Double priorScore;
  private final ExperimentDocumentConfusionMetric confusion;
  private final List<ExperimentByDocumentTargetMetric> targets;

  @JsonCreator
  public ExperimentByDocumentMetricsResponse(
      @JsonProperty(value = "run_id", required = true) String runId,
      @JsonProperty(value = "kind", required = false) String kind,
      @JsonProperty(value = "view", required = false) String view,
      @JsonProperty(value = "document", required = true) ExperimentMetricDocumentRef document,
      @JsonProperty(value = "score", required = false) Double score,
      @JsonProperty(value = "prior_score", required = false) Double priorScore,
      @JsonProperty(value = "confusion", required = false)
          ExperimentDocumentConfusionMetric confusion,
      @JsonProperty(value = "targets", required = false)
          List<ExperimentByDocumentTargetMetric> targets) {
    this.runId = runId;
    this.kind = kind;
    this.view = view;
    this.document = document;
    this.score = score;
    this.priorScore = priorScore;
    this.confusion = confusion;
    this.targets = targets;
  }

  @JsonProperty("run_id")
  public String getRunId() {
    return runId;
  }

  @JsonProperty("kind")
  public String getKind() {
    return kind;
  }

  @JsonProperty("view")
  public String getView() {
    return view;
  }

  @JsonProperty("document")
  public ExperimentMetricDocumentRef getDocument() {
    return document;
  }

  @JsonProperty("score")
  public Double getScore() {
    return score;
  }

  @JsonProperty("prior_score")
  public Double getPriorScore() {
    return priorScore;
  }

  @JsonProperty("confusion")
  public ExperimentDocumentConfusionMetric getConfusion() {
    return confusion;
  }

  @JsonProperty("targets")
  public List<ExperimentByDocumentTargetMetric> getTargets() {
    return targets;
  }
}
