// This file is auto-generated by oagen. Do not edit.

package com.retab.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.Map;

@JsonIgnoreProperties(ignoreUnknown = true)
public final class ExtractionRequest {
  private final MimeData document;
  private final Map<String, Object> jsonSchema;
  private final String model;
  private final String instructions;
  private final Long nConsensus;
  private final Map<String, String> metadata;
  private final List<Map<String, Object>> additionalMessages;
  private final Boolean bustCache;
  private final Boolean stream;
  private final Boolean background;
  private final Boolean deepExtraction;
  private final SourceOptions sources;

  @JsonCreator
  public ExtractionRequest(
      @JsonProperty(value = "document", required = true) MimeData document,
      @JsonProperty(value = "json_schema", required = true) Map<String, Object> jsonSchema,
      @JsonProperty(value = "model", required = false) String model,
      @JsonProperty(value = "instructions", required = false) String instructions,
      @JsonProperty(value = "n_consensus", required = false) Long nConsensus,
      @JsonProperty(value = "metadata", required = false) Map<String, String> metadata,
      @JsonProperty(value = "additional_messages", required = false)
          List<Map<String, Object>> additionalMessages,
      @JsonProperty(value = "bust_cache", required = false) Boolean bustCache,
      @JsonProperty(value = "stream", required = false) Boolean stream,
      @JsonProperty(value = "background", required = false) Boolean background,
      @JsonProperty(value = "deep_extraction", required = false) Boolean deepExtraction,
      @JsonProperty(value = "sources", required = false) SourceOptions sources) {
    this.document = document;
    this.jsonSchema = jsonSchema;
    this.model = model != null ? model : "retab-small";
    this.instructions = instructions;
    this.nConsensus = nConsensus;
    this.metadata = metadata;
    this.additionalMessages = additionalMessages;
    this.bustCache = bustCache != null ? bustCache : false;
    this.stream = stream != null ? stream : false;
    this.background = background != null ? background : false;
    this.deepExtraction = deepExtraction != null ? deepExtraction : false;
    this.sources = sources;
  }

  public ExtractionRequest(
      MimeData document,
      Map<String, Object> jsonSchema,
      String model,
      String instructions,
      Long nConsensus,
      Map<String, String> metadata,
      List<Map<String, Object>> additionalMessages,
      Boolean bustCache,
      Boolean stream,
      Boolean background,
      Boolean deepExtraction) {
    this(
        document,
        jsonSchema,
        model,
        instructions,
        nConsensus,
        metadata,
        additionalMessages,
        bustCache,
        stream,
        background,
        deepExtraction,
        null);
  }

  @JsonProperty("document")
  public MimeData getDocument() {
    return document;
  }

  @JsonProperty("json_schema")
  public Map<String, Object> getJsonSchema() {
    return jsonSchema;
  }

  @JsonProperty("model")
  public String getModel() {
    return model;
  }

  @JsonProperty("instructions")
  public String getInstructions() {
    return instructions;
  }

  @JsonProperty("n_consensus")
  public Long getNConsensus() {
    return nConsensus;
  }

  @JsonProperty("metadata")
  public Map<String, String> getMetadata() {
    return metadata;
  }

  @JsonProperty("additional_messages")
  public List<Map<String, Object>> getAdditionalMessages() {
    return additionalMessages;
  }

  @JsonProperty("bust_cache")
  public Boolean isBustCache() {
    return bustCache;
  }

  @JsonProperty("stream")
  public Boolean isStream() {
    return stream;
  }

  @JsonProperty("background")
  public Boolean isBackground() {
    return background;
  }

  @JsonProperty("deep_extraction")
  public Boolean isDeepExtraction() {
    return deepExtraction;
  }

  @JsonProperty("sources")
  public SourceOptions getSources() {
    return sources;
  }
}
