// This file is auto-generated by oagen. Do not edit.

package com.retab.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

@JsonIgnoreProperties(ignoreUnknown = true)
public final class LlmJudgedAsCondition implements Condition {
  private final String kind;
  private final String rubric;
  private final String expectedLabel;

  @JsonCreator
  public LlmJudgedAsCondition(
      @JsonProperty(value = "kind", required = false) String kind,
      @JsonProperty(value = "rubric", required = true) String rubric,
      @JsonProperty(value = "expected_label", required = false) String expectedLabel) {
    this.kind = kind;
    this.rubric = rubric;
    this.expectedLabel = expectedLabel;
  }

  @JsonProperty("kind")
  public String getKind() {
    return kind;
  }

  @JsonProperty("rubric")
  public String getRubric() {
    return rubric;
  }

  @JsonProperty("expected_label")
  public String getExpectedLabel() {
    return expectedLabel;
  }
}
