// This file is auto-generated by oagen. Do not edit.

package com.retab.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

@JsonIgnoreProperties(ignoreUnknown = true)
public final class ManualTrigger {
  private final String type;
  private final String userId;

  @JsonCreator
  public ManualTrigger(
      @JsonProperty(value = "type", required = false) String type,
      @JsonProperty(value = "user_id", required = false) String userId) {
    this.type = type;
    this.userId = userId;
  }

  @JsonProperty("type")
  public String getType() {
    return type;
  }

  @JsonProperty("user_id")
  public String getUserId() {
    return userId;
  }
}
