// This file is auto-generated by oagen. Do not edit.

package com.retab.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;

@JsonIgnoreProperties(ignoreUnknown = true)
public final class MetricsStaleErrorLastRun {
  private final String runId;
  private final String blockExecutionFingerprint;
  private final Double score;
  private final OffsetDateTime createdAt;

  @JsonCreator
  public MetricsStaleErrorLastRun(
      @JsonProperty(value = "run_id", required = true) String runId,
      @JsonProperty(value = "block_execution_fingerprint", required = false)
          String blockExecutionFingerprint,
      @JsonProperty(value = "score", required = false) Double score,
      @JsonProperty(value = "created_at", required = false) OffsetDateTime createdAt) {
    this.runId = runId;
    this.blockExecutionFingerprint = blockExecutionFingerprint;
    this.score = score;
    this.createdAt = createdAt;
  }

  @JsonProperty("run_id")
  public String getRunId() {
    return runId;
  }

  @JsonProperty("block_execution_fingerprint")
  public String getBlockExecutionFingerprint() {
    return blockExecutionFingerprint;
  }

  @JsonProperty("score")
  public Double getScore() {
    return score;
  }

  @JsonProperty("created_at")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }
}
