// This file is auto-generated by oagen. Do not edit.

package com.retab.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

@JsonIgnoreProperties(ignoreUnknown = true)
public final class PartitionChunkLikelihood {
  private final Double key;
  private final List<Double> pages;

  @JsonCreator
  public PartitionChunkLikelihood(
      @JsonProperty(value = "key", required = false) Double key,
      @JsonProperty(value = "pages", required = false) List<Double> pages) {
    this.key = key;
    this.pages = pages;
  }

  @JsonProperty("key")
  public Double getKey() {
    return key;
  }

  @JsonProperty("pages")
  public List<Double> getPages() {
    return pages;
  }
}
