// This file is auto-generated by oagen. Do not edit.

package com.retab.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.Map;

@JsonIgnoreProperties(ignoreUnknown = true)
public final class ReconciliationResult {
  private final ReconciliationAlignment alignment;
  private final Map<String, Object> consensus;
  private final List<ReconciliationField> fields;
  private final Map<String, Double> likelihoods;

  @JsonCreator
  public ReconciliationResult(
      @JsonProperty(value = "alignment", required = true) ReconciliationAlignment alignment,
      @JsonProperty(value = "consensus", required = true) Map<String, Object> consensus,
      @JsonProperty(value = "fields", required = true) List<ReconciliationField> fields,
      @JsonProperty(value = "likelihoods", required = true) Map<String, Double> likelihoods) {
    this.alignment = alignment;
    this.consensus = consensus;
    this.fields = fields;
    this.likelihoods = likelihoods;
  }

  @JsonProperty("alignment")
  public ReconciliationAlignment getAlignment() {
    return alignment;
  }

  @JsonProperty("consensus")
  public Map<String, Object> getConsensus() {
    return consensus;
  }

  @JsonProperty("fields")
  public List<ReconciliationField> getFields() {
    return fields;
  }

  @JsonProperty("likelihoods")
  public Map<String, Double> getLikelihoods() {
    return likelihoods;
  }
}
