// This file is auto-generated by oagen. Do not edit.

package com.retab.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

@JsonIgnoreProperties(ignoreUnknown = true)
public final class ReconstructEnrichedTable {
  private final String csv;
  private final List<String> header;
  private final String label;
  private final List<ReconstructEnrichedRow> rows;

  @JsonCreator
  public ReconstructEnrichedTable(
      @JsonProperty(value = "csv", required = true) String csv,
      @JsonProperty(value = "header", required = true) List<String> header,
      @JsonProperty(value = "label", required = true) String label,
      @JsonProperty(value = "rows", required = true) List<ReconstructEnrichedRow> rows) {
    this.csv = csv;
    this.header = header;
    this.label = label;
    this.rows = rows;
  }

  @JsonProperty("csv")
  public String getCsv() {
    return csv;
  }

  @JsonProperty("header")
  public List<String> getHeader() {
    return header;
  }

  @JsonProperty("label")
  public String getLabel() {
    return label;
  }

  @JsonProperty("rows")
  public List<ReconstructEnrichedRow> getRows() {
    return rows;
  }
}
