// This file is auto-generated by oagen. Do not edit.

package com.retab.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

@JsonIgnoreProperties(ignoreUnknown = true)
public final class ReviewTopMarginLt implements ReviewKind {
  private final String kind;
  private final Double margin;

  @JsonCreator
  public ReviewTopMarginLt(
      @JsonProperty(value = "kind", required = false) String kind,
      @JsonProperty(value = "margin", required = true) Double margin) {
    this.kind = kind != null ? kind : "top_margin_lt";
    this.margin = margin;
  }

  @JsonProperty("kind")
  public String getKind() {
    return kind;
  }

  @JsonProperty("margin")
  public Double getMargin() {
    return margin;
  }
}
