// This file is auto-generated by oagen. Do not edit.

package com.retab.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

@JsonIgnoreProperties(ignoreUnknown = true)
public final class ReviewAnyPagesUnassigned implements ReviewKind {
  private final String kind;

  @JsonCreator
  public ReviewAnyPagesUnassigned(@JsonProperty(value = "kind", required = false) String kind) {
    this.kind = kind != null ? kind : "any_pages_unassigned";
  }

  @JsonProperty("kind")
  public String getKind() {
    return kind;
  }
}
