// This file is auto-generated by oagen. Do not edit.

package com.retab.models;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

/**
 * Discriminated union over Scope variants, selected by the {@code type} discriminator.
 *
 * <p>Jackson deserializes the wire JSON into the correct concrete variant, so all variant-specific
 * fields round-trip losslessly. Branch on the concrete type to read variant data:
 *
 * <pre>{@code
 * Scope value = api.get(...);
 * if (value instanceof WorkflowEvalRunBlockScope v) {
 *     handle(v);
 * }
 * }</pre>
 */
@JsonTypeInfo(
    use = JsonTypeInfo.Id.NAME,
    include = JsonTypeInfo.As.EXISTING_PROPERTY,
    property = "type",
    visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = WorkflowEvalRunBlockScope.class, name = "block"),
  @JsonSubTypes.Type(value = WorkflowEvalRunSingleScope.class, name = "single"),
  @JsonSubTypes.Type(value = WorkflowEvalRunWorkflowScope.class, name = "workflow")
})
public sealed interface Scope
    permits WorkflowEvalRunBlockScope, WorkflowEvalRunSingleScope, WorkflowEvalRunWorkflowScope {}
