// This file is auto-generated by oagen. Do not edit.

package com.retab.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

@JsonIgnoreProperties(ignoreUnknown = true)
public final class UpdateEditTemplateRequest {
  private final String name;
  private final List<FormField> formFields;

  @JsonCreator
  public UpdateEditTemplateRequest(
      @JsonProperty(value = "name", required = false) String name,
      @JsonProperty(value = "form_fields", required = false) List<FormField> formFields) {
    this.name = name;
    this.formFields = formFields;
  }

  @JsonProperty("name")
  public String getName() {
    return name;
  }

  @JsonProperty("form_fields")
  public List<FormField> getFormFields() {
    return formFields;
  }
}
