// This file is auto-generated by oagen. Do not edit.

package com.retab.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

@JsonIgnoreProperties(ignoreUnknown = true)
public final class UpdateWorkflowTestRequest {
  private final String name;
  private final AssertionSpec assertion;
  private final WorkflowTestSource source;

  @JsonCreator
  public UpdateWorkflowTestRequest(
      @JsonProperty(value = "name", required = false) String name,
      @JsonProperty(value = "assertion", required = false) AssertionSpec assertion,
      @JsonProperty(value = "source", required = false) WorkflowTestSource source) {
    this.name = name;
    this.assertion = assertion;
    this.source = source;
  }

  @JsonProperty("name")
  public String getName() {
    return name;
  }

  @JsonProperty("assertion")
  public AssertionSpec getAssertion() {
    return assertion;
  }

  @JsonProperty("source")
  public WorkflowTestSource getSource() {
    return source;
  }
}
