// This file is auto-generated by oagen. Do not edit.

package com.retab.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

@JsonIgnoreProperties(ignoreUnknown = true)
public final class UsagePrimitiveTriggeredBy {
  private final String accessTokenId;
  private final String apiKeyId;
  private final String authMethod;
  private final String keyName;
  private final String keyPrefix;
  private final String userId;

  @JsonCreator
  public UsagePrimitiveTriggeredBy(
      @JsonProperty(value = "access_token_id", required = true) String accessTokenId,
      @JsonProperty(value = "api_key_id", required = true) String apiKeyId,
      @JsonProperty(value = "auth_method", required = true) String authMethod,
      @JsonProperty(value = "key_name", required = true) String keyName,
      @JsonProperty(value = "key_prefix", required = true) String keyPrefix,
      @JsonProperty(value = "user_id", required = true) String userId) {
    this.accessTokenId = accessTokenId;
    this.apiKeyId = apiKeyId;
    this.authMethod = authMethod;
    this.keyName = keyName;
    this.keyPrefix = keyPrefix;
    this.userId = userId;
  }

  @JsonProperty("access_token_id")
  public String getAccessTokenId() {
    return accessTokenId;
  }

  @JsonProperty("api_key_id")
  public String getApiKeyId() {
    return apiKeyId;
  }

  @JsonProperty("auth_method")
  public String getAuthMethod() {
    return authMethod;
  }

  @JsonProperty("key_name")
  public String getKeyName() {
    return keyName;
  }

  @JsonProperty("key_prefix")
  public String getKeyPrefix() {
    return keyPrefix;
  }

  @JsonProperty("user_id")
  public String getUserId() {
    return userId;
  }
}
