// This file is auto-generated by oagen. Do not edit.

package com.retab.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

@JsonIgnoreProperties(ignoreUnknown = true)
public final class WorkflowTableSampleRequest {
  private final Long size;

  @JsonCreator
  public WorkflowTableSampleRequest(@JsonProperty(value = "size", required = true) Long size) {
    this.size = size;
  }

  @JsonProperty("size")
  public Long getSize() {
    return size;
  }
}
