// This file is auto-generated by oagen. Do not edit.

package com.retab.models;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

/**
 * Discriminated union over WorkflowEvalSource variants, selected by the {@code type} discriminator.
 *
 * <p>Jackson deserializes the wire JSON into the correct concrete variant, so all variant-specific
 * fields round-trip losslessly. Branch on the concrete type to read variant data:
 *
 * <pre>{@code
 * WorkflowEvalSource value = api.get(...);
 * if (value instanceof ManualWorkflowEvalSource v) {
 *     handle(v);
 * }
 * }</pre>
 */
@JsonTypeInfo(
    use = JsonTypeInfo.Id.NAME,
    include = JsonTypeInfo.As.EXISTING_PROPERTY,
    property = "type",
    visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = ManualWorkflowEvalSource.class, name = "manual"),
  @JsonSubTypes.Type(value = RunStepWorkflowEvalSource.class, name = "run_step")
})
public sealed interface WorkflowEvalSource
    permits ManualWorkflowEvalSource, RunStepWorkflowEvalSource {}
