// This file is auto-generated by oagen. Do not edit.

package com.retab.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

@JsonIgnoreProperties(ignoreUnknown = true)
public final class WorkflowTableProfileResponse {
  private final String tableId;
  private final Long rowCount;
  private final List<WorkflowTableProfileColumn> columns;

  @JsonCreator
  public WorkflowTableProfileResponse(
      @JsonProperty(value = "table_id", required = true) String tableId,
      @JsonProperty(value = "row_count", required = true) Long rowCount,
      @JsonProperty(value = "columns", required = false) List<WorkflowTableProfileColumn> columns) {
    this.tableId = tableId;
    this.rowCount = rowCount;
    this.columns = columns;
  }

  @JsonProperty("table_id")
  public String getTableId() {
    return tableId;
  }

  @JsonProperty("row_count")
  public Long getRowCount() {
    return rowCount;
  }

  @JsonProperty("columns")
  public List<WorkflowTableProfileColumn> getColumns() {
    return columns;
  }
}
