// This file is auto-generated by the Retab oagen emitter. Do not edit by hand.

import { z } from 'zod';
import type {
  EditConfig,
  EditConfigResponse,
} from '../../../edits/interfaces/edit-config.interface.js';
import {
  ZEditConfig,
  deserializeEditConfig,
  serializeEditConfig,
} from '../../../edits/interfaces/edit-config.interface.js';
import type {
  EditResult,
  EditResultResponse,
} from '../../../edits/interfaces/edit-result.interface.js';
import {
  ZEditResult,
  deserializeEditResult,
  serializeEditResult,
} from '../../../edits/interfaces/edit-result.interface.js';
import type {
  FileRef,
  FileRefResponse,
} from '../../../classifications/interfaces/file-ref.interface.js';
import {
  ZFileRef,
  deserializeFileRef,
  serializeFileRef,
} from '../../../classifications/interfaces/file-ref.interface.js';
import type {
  PrimitiveError,
  PrimitiveErrorResponse,
} from '../../../classifications/interfaces/primitive-error.interface.js';
import {
  ZPrimitiveError,
  deserializePrimitiveError,
  serializePrimitiveError,
} from '../../../classifications/interfaces/primitive-error.interface.js';
import type {
  RetabUsage,
  RetabUsageResponse,
} from '../../../classifications/interfaces/retab-usage.interface.js';
import {
  ZRetabUsage,
  deserializeRetabUsage,
  serializeRetabUsage,
} from '../../../classifications/interfaces/retab-usage.interface.js';
import type { EditWorkflowArtifactStatus } from './edit-workflow-artifact-status.interface.js';
import { ZEditWorkflowArtifactStatus } from './edit-workflow-artifact-status.interface.js';

/** An edit produced by a workflow run, tagged with its artifact `operation` and creation time. */
export interface EditWorkflowArtifact {
  /** Unique identifier of the edit. */
  id: string;
  /** Information about the source file (input document or template PDF). */
  file: FileRef;
  /** Model used for the edit operation. */
  model: string;
  /** Free-form instructions supplied with the edit request. */
  instructions?: string | null;
  /** Configuration used for the edit operation. */
  config: EditConfig;
  /** Template id used when the edit was created from a template; null for direct-document edits. */
  templateId?: string | null;
  /** The edit result: filled form fields and the rendered PDF. An empty sentinel until status == 'completed'; gate reads on status. */
  output?: EditResult;
  /**
   * Lifecycle status. The synchronous path returns 'completed'. Background runs progress pending -> queued -> in_progress -> completed | failed | cancelled.
   * @default "pending"
   */
  status?: EditWorkflowArtifactStatus;
  /** Error details when a background run fails; null otherwise. Always present so consumers can read it without an existence check. */
  error?: PrimitiveError | null;
  /** Durable file reference for the filled document, when materialized. */
  filledDocumentRef?: FileRef | null;
  /** Usage information for the edit operation. */
  usage?: RetabUsage | null;
  /** Timestamp when this artifact was created. */
  createdAt?: Date;
  /**
   * The operation that produced this artifact
   * @default "edit"
   */
  operation: 'edit';
}

export interface EditWorkflowArtifactResponse {
  id: string;
  file: FileRefResponse;
  model: string;
  instructions?: string | null;
  config: EditConfigResponse;
  template_id?: string | null;
  output?: EditResultResponse;
  status?: EditWorkflowArtifactStatus;
  error?: PrimitiveErrorResponse | null;
  filled_document_ref?: FileRefResponse | null;
  usage?: RetabUsageResponse | null;
  created_at?: string;
  operation: 'edit';
}

export const ZEditWorkflowArtifact = z.object({
  id: z.string(),
  file: ZFileRef,
  model: z.string(),
  instructions: z.string().nullable().optional(),
  config: ZEditConfig,
  templateId: z.string().nullable().optional(),
  output: ZEditResult.optional(),
  status: ZEditWorkflowArtifactStatus.optional(),
  error: ZPrimitiveError.nullable().optional(),
  filledDocumentRef: ZFileRef.nullable().optional(),
  usage: ZRetabUsage.nullable().optional(),
  createdAt: z.coerce.date().optional(),
  operation: z.literal('edit'),
}) as z.ZodType<EditWorkflowArtifact>;

export function deserializeEditWorkflowArtifact(
  wire: EditWorkflowArtifactResponse
): EditWorkflowArtifact {
  return {
    id: wire['id'],
    file: deserializeFileRef(wire['file']),
    model: wire['model'],
    instructions: wire['instructions'],
    config: deserializeEditConfig(wire['config']),
    templateId: wire['template_id'],
    output:
      wire['output'] == null
        ? (wire['output'] as undefined)
        : deserializeEditResult(wire['output']),
    status: wire['status'],
    error:
      wire['error'] == null
        ? (wire['error'] as undefined)
        : wire['error'] == null
          ? wire['error']
          : deserializePrimitiveError(wire['error']),
    filledDocumentRef:
      wire['filled_document_ref'] == null
        ? (wire['filled_document_ref'] as undefined)
        : wire['filled_document_ref'] == null
          ? wire['filled_document_ref']
          : deserializeFileRef(wire['filled_document_ref']),
    usage:
      wire['usage'] == null
        ? (wire['usage'] as undefined)
        : wire['usage'] == null
          ? wire['usage']
          : deserializeRetabUsage(wire['usage']),
    createdAt:
      wire['created_at'] == null ? (wire['created_at'] as undefined) : new Date(wire['created_at']),
    operation: wire['operation'],
  };
}

export function serializeEditWorkflowArtifact(
  domain: EditWorkflowArtifact
): EditWorkflowArtifactResponse {
  return {
    id: domain['id'],
    file: serializeFileRef(domain['file']),
    model: domain['model'],
    instructions: domain['instructions'],
    config: serializeEditConfig(domain['config']),
    template_id: domain['templateId'],
    output:
      domain['output'] == null
        ? (domain['output'] as undefined)
        : serializeEditResult(domain['output']),
    status: domain['status'],
    error:
      domain['error'] == null
        ? (domain['error'] as undefined)
        : domain['error'] == null
          ? domain['error']
          : serializePrimitiveError(domain['error']),
    filled_document_ref:
      domain['filledDocumentRef'] == null
        ? (domain['filledDocumentRef'] as undefined)
        : domain['filledDocumentRef'] == null
          ? domain['filledDocumentRef']
          : serializeFileRef(domain['filledDocumentRef']),
    usage:
      domain['usage'] == null
        ? (domain['usage'] as undefined)
        : domain['usage'] == null
          ? domain['usage']
          : serializeRetabUsage(domain['usage']),
    created_at:
      domain['createdAt'] == null
        ? (domain['createdAt'] as undefined)
        : domain['createdAt'].toISOString(),
    operation: domain['operation'],
  };
}
