// This file is auto-generated by the Retab oagen emitter. Do not edit by hand.

import { z } from 'zod';

export type ParseWorkflowArtifactTableParsingFormat = 'markdown' | 'yaml' | 'html' | 'json';

export const ZParseWorkflowArtifactTableParsingFormat = z.enum([
  'markdown',
  'yaml',
  'html',
  'json',
] as const);
