# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module Retab
  class WebhookTrigger < Retab::Types::BaseModel

    HASH_ATTRS = {
      type: :type,
      webhook_id: :webhook_id
    }.freeze

    attr_accessor(
      :type,
      :webhook_id
    )

    def initialize(json)
      super()
      hash = self.class.normalize(json)
      @type = hash[:type].nil? ? "webhook" : hash[:type]
      @webhook_id = hash[:webhook_id]
    end
  end
end
