# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module Retab
  class WorkflowConfigEdge < Retab::Types::BaseModel

    HASH_ATTRS = {
      id: :id,
      source: :source,
      target: :target,
      source_handle: :source_handle,
      target_handle: :target_handle,
      animated: :animated
    }.freeze

    attr_accessor(
      :id,
      :source,
      :target,
      :source_handle,
      :target_handle,
      :animated
    )

    def initialize(json)
      super()
      hash = self.class.normalize(json)
      @id = hash[:id]
      @source = hash[:source]
      @target = hash[:target]
      @source_handle = hash[:source_handle]
      @target_handle = hash[:target_handle]
      @animated = hash[:animated].nil? ? true : hash[:animated]
    end
  end
end
