// This file is auto-generated by oagen. Do not edit.

namespace Retab
{

    /// <summary>The step is paused on a human review decision.</summary>
    public class AwaitingReviewStepLifecycle
    {
        public string? Status { get; set; }
    }
}
