// This file is auto-generated by oagen. Do not edit.

namespace Retab
{

    /// <summary>Represents an ends with condition.</summary>
    public class EndsWithCondition
    {
        public string? Kind { get; set; }
        public string Expected { get; set; } = default!;
    }
}
