// This file is auto-generated by oagen. Do not edit.

namespace Retab
{

    /// <summary>Workflow execution metadata attached to a captured document.</summary>
    public class ExperimentDocumentProvenance
    {
        public string? WorkflowRunId { get; set; }
        public string? StepId { get; set; }
    }
}
