// This file is auto-generated by oagen. Do not edit.

namespace Retab
{
    using System.Collections.Generic;

    /// <summary>Returned when the latest run's config or document set has drifted</summary>
    /// <remarks>
    /// from the current draft, so its metrics no longer reflect the
    /// experiment's definition.
    /// </remarks>
    public class ExperimentMetricsStaleError
    {
        public string? Kind { get; set; }
        public string? Error { get; set; }
        public string ExperimentId { get; set; } = default!;
        public List<string>? StaleReasons { get; set; }
        public MetricsStaleErrorLastRun LastRun { get; set; } = default!;
        public string? CurrentConfigFingerprint { get; set; }
        public string Message { get; set; } = default!;
    }
}
