// This file is auto-generated by oagen. Do not edit.

namespace Retab
{
    using System.Collections.Generic;

    /// <summary>Represents a partial schema.</summary>
    public class PartialSchema
    {
        public string? Object { get; set; }
        public string? CreatedAt { get; set; }
        public Dictionary<string, object>? JsonSchema { get; set; }
        public bool? Strict { get; set; }

        /// <summary>
        /// Typed accessor for <see cref="JsonSchema"/>. Returns the value stored under
        /// <paramref name="key"/> coerced to <typeparamref name="T"/>, or the default
        /// value when the key is missing or the value is not convertible.
        /// </summary>
        /// <typeparam name="T">Expected value type.</typeparam>
        /// <param name="key">The key to look up.</param>
        public T? GetJsonSchemaAttribute<T>(string key)
        {
            if (this.JsonSchema == null)
            {
                return default;
            }

            if (!this.JsonSchema.TryGetValue(key, out var value))
            {
                return default;
            }

            if (value is T typed)
            {
                return typed;
            }

            if (value is Newtonsoft.Json.Linq.JToken token)
            {
                return token.ToObject<T>();
            }

            if (value is System.Text.Json.JsonElement element)
            {
                return System.Text.Json.JsonSerializer.Deserialize<T>(element.GetRawText());
            }

            return default;
        }
    }
}
