// This file is auto-generated by oagen. Do not edit.

namespace Retab
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a workflow experiment.</summary>
    public class WorkflowExperiment
    {
        public string Id { get; set; } = default!;
        public string WorkflowId { get; set; } = default!;
        public string BlockId { get; set; } = default!;
        [JsonProperty(DefaultValueHandling = DefaultValueHandling.Ignore)]
        [STJS.JsonIgnore(Condition = STJS.JsonIgnoreCondition.WhenWritingDefault)]
        public CreateExperimentRequestNConsensus NConsensus { get; set; }
        public long? DocumentCount { get; set; }
        public string Name { get; set; } = default!;
        public string? LastRunId { get; set; }
        public DateTimeOffset? CreatedAt { get; set; }
        public DateTimeOffset? UpdatedAt { get; set; }
        public ExperimentPublicStatus? Status { get; set; }
        [JsonProperty(DefaultValueHandling = DefaultValueHandling.Ignore)]
        [STJS.JsonIgnore(Condition = STJS.JsonIgnoreCondition.WhenWritingDefault)]
        public ExperimentBlockType BlockType { get; set; }
        public double? Score { get; set; }
        public bool? IsStale { get; set; }
        public ExperimentSchemaDriftStatus? SchemaDrift { get; set; }
        public string? SchemaDriftDetail { get; set; }
    }
}
