// This file is auto-generated by the Retab oagen emitter. Do not edit by hand.

import type { Retab } from '../retab.js';
import { PaginatedList } from '../_pagination.js';
import { coerceMimeData, type DocumentInput } from '../runtime/mime.js';
import type { SplitsStatus } from '../common/interfaces/index.js';
import type {
  ReconstructDocumentRef,
  ReconstructResponse,
  ReconstructResponseResponse,
  ReconstructSubdocument,
  Split,
  SplitResponse,
  Subdocument,
} from '../splits/interfaces/index.js';
import {
  deserializeReconstructResponse,
  deserializeSplit,
  serializeReconstructDocumentRef,
  serializeReconstructSubdocument,
  serializeSubdocument,
} from '../splits/interfaces/index.js';

export class Splits {
  constructor(private readonly client: Retab) {}

  /** List Splits */
  async list(options?: {
    filename?: string | null | undefined;
    status?: SplitsStatus | null | undefined;
    fromDate?: string | null | undefined;
    toDate?: string | null | undefined;
    limit?: number;
    before?: string;
    after?: string;
    order?: 'asc' | 'desc';
  }): Promise<PaginatedList<Split>> {
    return this.client._fetchPage(deserializeSplit, {
      method: 'GET',
      path: '/v1/splits',
      query: {
        filename: options?.filename,
        status: options?.status,
        from_date: options?.fromDate,
        to_date: options?.toDate,
        limit: options?.limit,
        before: options?.before,
        after: options?.after,
        order: options?.order,
      },
      body: undefined,
    });
  }

  /** Create Split */
  async create(
    document: DocumentInput,
    subdocuments: Subdocument[],
    model?: string,
    instructions?: string | null,
    nConsensus?: number,
    bustCache?: boolean,
    background?: boolean
  ): Promise<Split> {
    const documentCoerced = await coerceMimeData(document, (__id) =>
      this.client.files.get_download_link(__id)
    );
    const body = {
      document: documentCoerced,
      subdocuments: subdocuments.map((__i) => serializeSubdocument(__i)),
      model: model,
      instructions: instructions,
      n_consensus: nConsensus,
      bust_cache: bustCache,
      background: background,
    };
    const __wire = await this.client.request<SplitResponse>({
      method: 'POST',
      path: '/v1/splits',
      query: undefined,
      body: body,
    });
    return deserializeSplit(__wire);
  }

  /** Reconstruct Split */
  async create_reconstruct(
    document: ReconstructDocumentRef,
    subdocuments: ReconstructSubdocument[]
  ): Promise<ReconstructResponse> {
    const body = {
      document: serializeReconstructDocumentRef(document),
      subdocuments: subdocuments.map((__i) => serializeReconstructSubdocument(__i)),
    };
    const __wire = await this.client.request<ReconstructResponseResponse>({
      method: 'POST',
      path: '/v1/splits/reconstruct',
      query: undefined,
      body: body,
    });
    return deserializeReconstructResponse(__wire);
  }

  /** Get Split */
  async get(splitId: string, options?: { includeOutput?: boolean | undefined }): Promise<Split> {
    const __wire = await this.client.request<SplitResponse>({
      method: 'GET',
      path: `/v1/splits/${splitId}`,
      query: { include_output: options?.includeOutput },
      body: undefined,
    });
    return deserializeSplit(__wire);
  }

  /** Delete Split */
  async delete(splitId: string): Promise<void> {
    await this.client.request<unknown>({
      method: 'DELETE',
      path: `/v1/splits/${splitId}`,
      query: undefined,
      body: undefined,
    });
  }

  /** Cancel Split */
  async create_split_cancel(splitId: string): Promise<Split> {
    const __wire = await this.client.request<SplitResponse>({
      method: 'POST',
      path: `/v1/splits/${splitId}/cancel`,
      query: undefined,
      body: undefined,
    });
    return deserializeSplit(__wire);
  }
}
