<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Tests\Service;

use PHPUnit\Framework\TestCase;
use Retab\TestHelper;

class ExtractionSourcesTest extends TestCase
{
    use TestHelper;

    public function testGet(): void
    {
        $fixture = $this->loadFixture('sources_response');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->extractions()->sources()->get('test_extraction_id', mode: \Retab\Resource\SourceJobMode::Located, jobId: 'test_value');
        $this->assertInstanceOf(\Retab\Resource\SourcesResponse::class, $result);
        $this->assertSame($fixture['extraction_id'], $result->extractionId);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('GET', $request->getMethod());
        $this->assertStringEndsWith('v1/extractions/test_extraction_id/sources', $request->getUri()->getPath());
        parse_str($request->getUri()->getQuery(), $query);
        $this->assertSame('located', $query['mode']);
        $this->assertSame('test_value', $query['job_id']);
    }

    public function testCreate(): void
    {
        $fixture = $this->loadFixture('sources_response');
        $client = $this->createMockClient([['status' => 200, 'body' => $fixture]]);
        $result = $client->extractions()->sources()->create('test_extraction_id');
        $this->assertInstanceOf(\Retab\Resource\SourcesResponse::class, $result);
        $this->assertSame($fixture['extraction_id'], $result->extractionId);
        $this->assertIsArray($result->toArray());
        $request = $this->getLastRequest();
        $this->assertSame('POST', $request->getMethod());
        $this->assertStringEndsWith('v1/extractions/test_extraction_id/sources', $request->getUri()->getPath());
    }
}
