# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module Retab
  module Types
    class EvidenceAnchorKind
      PDF_BBOX = "pdf_bbox"
      IMAGE_BBOX = "image_bbox"
      TEXT_SPAN = "text_span"
      SPREADSHEET_CELL = "spreadsheet_cell"
      CSV_CELL = "csv_cell"
      DOCX_TEXT_SPAN = "docx_text_span"
      DOCX_TABLE_CELL = "docx_table_cell"
      ALL = [PDF_BBOX, IMAGE_BBOX, TEXT_SPAN, SPREADSHEET_CELL, CSV_CELL, DOCX_TEXT_SPAN, DOCX_TABLE_CELL].freeze
    end
  end
end
