# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module Retab
  module Types
    class GenerateSchemaRequestReasoningEffort
      NONE = "none"
      MINIMAL = "minimal"
      LOW = "low"
      MEDIUM = "medium"
      HIGH = "high"
      XHIGH = "xhigh"
      ALL = [NONE, MINIMAL, LOW, MEDIUM, HIGH, XHIGH].freeze
    end
  end
end
