# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module Retab
  module Types
    class JobsSource
      API = "api"
      PROJECT = "project"
      WORKFLOW = "workflow"
      ALL = [API, PROJECT, WORKFLOW].freeze
    end
  end
end
