# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module Retab
  module Types
    class SourcesResponseDocumentType
      PDF = "pdf"
      IMAGE = "image"
      CSV = "csv"
      XLSX = "xlsx"
      DOCX = "docx"
      TXT = "txt"
      ALL = [PDF, IMAGE, CSV, XLSX, DOCX, TXT].freeze
    end
  end
end
