# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module Retab
  module Types
    class UpdateWorkflowBlockRequestConfigMode
      MERGE = "merge"
      REPLACE = "replace"
      ALL = [MERGE, REPLACE].freeze
    end
  end
end
