# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module Retab
  module Types
    class WorkflowTableFilterOperator
      EQ = "eq"
      NE = "ne"
      GT = "gt"
      GTE = "gte"
      LT = "lt"
      LTE = "lte"
      CONTAINS = "contains"
      NOT_CONTAINS = "not_contains"
      STARTS_WITH = "starts_with"
      ENDS_WITH = "ends_with"
      IN = "in"
      NOT_IN = "not_in"
      BETWEEN = "between"
      IS_EMPTY = "is_empty"
      IS_NOT_EMPTY = "is_not_empty"
      IS_NULL = "is_null"
      IS_NOT_NULL = "is_not_null"
      ALL = [
        EQ,
        NE,
        GT,
        GTE,
        LT,
        LTE,
        CONTAINS,
        NOT_CONTAINS,
        STARTS_WITH,
        ENDS_WITH,
        IN,
        NOT_IN,
        BETWEEN,
        IS_EMPTY,
        IS_NOT_EMPTY,
        IS_NULL,
        IS_NOT_NULL
      ].freeze
    end
  end
end
