# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module Retab
  class DeclarativePlanFieldChange < Retab::Types::BaseModel

    HASH_ATTRS = {
      path: :path,
      path_display: :path_display,
      action: :action,
      before: :before,
      after: :after,
      before_sensitive: :before_sensitive,
      after_sensitive: :after_sensitive,
      unified_diff: :unified_diff
    }.freeze

    attr_accessor(
      :path,
      :path_display,
      :action,
      :before,
      :after,
      :before_sensitive,
      :after_sensitive,
      :unified_diff
    )

    def initialize(json)
      super()
      hash = self.class.normalize(json)
      @path = (hash[:path] || [])
      @path_display = hash[:path_display]
      @action = hash[:action]
      @before = hash[:before]
      @after = hash[:after]
      @before_sensitive = hash[:before_sensitive]
      @after_sensitive = hash[:after_sensitive]
      @unified_diff = hash[:unified_diff]
    end
  end
end
