// This file is auto-generated by the Retab oagen emitter. Do not edit by hand.

import { z } from 'zod';
import type {
  ClassificationDecision,
  ClassificationDecisionResponse,
} from './classification-decision.interface.js';
import {
  ZClassificationDecision,
  deserializeClassificationDecision,
  serializeClassificationDecision,
} from './classification-decision.interface.js';

export interface ClassificationConsensus {
  /** Alternative classification vote outputs used to build the consolidated result. */
  choices?: ClassificationDecision[];
  /**
   * Consensus likelihood score (0.0-1.0) of the winning classification.
   * @default 0
   */
  likelihoods?: number;
}

export interface ClassificationConsensusResponse {
  choices?: ClassificationDecisionResponse[];
  likelihoods?: number;
}

export const ZClassificationConsensus = z.object({
  choices: ZClassificationDecision.array().optional(),
  likelihoods: z.number().optional(),
}) as z.ZodType<ClassificationConsensus>;

export function deserializeClassificationConsensus(
  wire: ClassificationConsensusResponse
): ClassificationConsensus {
  return {
    choices:
      wire['choices'] == null
        ? (wire['choices'] as undefined)
        : wire['choices'].map((__i) => deserializeClassificationDecision(__i)),
    likelihoods: wire['likelihoods'],
  };
}

export function serializeClassificationConsensus(
  domain: ClassificationConsensus
): ClassificationConsensusResponse {
  return {
    choices:
      domain['choices'] == null
        ? (domain['choices'] as undefined)
        : domain['choices'].map((__i) => serializeClassificationDecision(__i)),
    likelihoods: domain['likelihoods'],
  };
}
