// This file is auto-generated by the Retab oagen emitter. Do not edit by hand.

import { z } from 'zod';
export interface WorkflowPublished {
  /** Published content-addressed workflow version ID */
  versionId?: string | null;
  /** When the workflow was last published */
  publishedAt?: Date | null;
  /** Release note attached to the currently published version. Echoes the ``description`` body passed to ``POST /v1/workflows/{id}/publish`` so the caller can confirm it was stored without a separate fetch. */
  description?: string | null;
}

export interface WorkflowPublishedResponse {
  version_id?: string | null;
  published_at?: string | null;
  description?: string | null;
}

export const ZWorkflowPublished = z.object({
  versionId: z.string().nullable().optional(),
  publishedAt: z.coerce.date().nullable().optional(),
  description: z.string().nullable().optional(),
}) as z.ZodType<WorkflowPublished>;

export function deserializeWorkflowPublished(wire: WorkflowPublishedResponse): WorkflowPublished {
  return {
    versionId: wire['version_id'],
    publishedAt:
      wire['published_at'] == null
        ? (wire['published_at'] as undefined)
        : wire['published_at'] == null
          ? wire['published_at']
          : new Date(wire['published_at']),
    description: wire['description'],
  };
}

export function serializeWorkflowPublished(domain: WorkflowPublished): WorkflowPublishedResponse {
  return {
    version_id: domain['versionId'],
    published_at:
      domain['publishedAt'] == null
        ? (domain['publishedAt'] as undefined)
        : domain['publishedAt'] == null
          ? domain['publishedAt']
          : domain['publishedAt'].toISOString(),
    description: domain['description'],
  };
}
