//go:build retab_oagen_cli_prototype && retab_oagen_cli_workflows_blocks

// Code generated by retab-cli-emitter. DO NOT EDIT.

package cmd

import (
	"fmt"
	retab "github.com/retab-dev/retab/clients/go"
	"github.com/spf13/cobra"
	"maps"
	"strings"
)

func parseBlockCreate(obj map[string]any) (retab.WorkflowBlocksCreateParams, error) {
	req := retab.WorkflowBlocksCreateParams{}
	if v, ok := obj["id"].(string); ok && v != "" {
		req.ID = ptr(v)
	}
	if v, ok := obj["type"].(string); ok {
		req.Type = retab.WorkflowBlockCreateRequestType(v)
	}
	if v, ok := obj["label"].(string); ok {
		req.Label = ptr(v)
	}
	if v, ok := obj["position_x"].(float64); ok {
		req.PositionX = ptr(v)
	}
	if v, ok := obj["position_y"].(float64); ok {
		req.PositionY = ptr(v)
	}
	if v, ok := obj["width"].(float64); ok {
		req.Width = &v
	}
	if v, ok := obj["height"].(float64); ok {
		req.Height = &v
	}
	if v, ok := obj["parent_id"].(string); ok {
		req.ParentID = ptr(v)
	}
	if v, ok := obj["config"].(map[string]any); ok {
		req.Config = &v
	}
	if err := rejectLegacyReviewConfig(req.Config); err != nil {
		return req, err
	}
	if req.Type == "" {
		return req, fmt.Errorf("block type is required")
	}
	if req.Type == "hil" {
		return req, fmt.Errorf("legacy hil blocks are no longer supported; add config.review to a reviewable block instead")
	}
	return req, nil
}

func parseBlockCreateForWorkflow(workflowID string, obj map[string]any) (retab.WorkflowBlocksCreateParams, error) {
	if bodyWorkflowID, ok := obj["workflow_id"].(string); ok && bodyWorkflowID != "" && bodyWorkflowID != workflowID {
		return retab.WorkflowBlocksCreateParams{}, fmt.Errorf("block-file workflow_id %q does not match positional workflow id %q", bodyWorkflowID, workflowID)
	}
	return parseBlockCreate(obj)
}

func rejectLegacyReviewConfig(config *map[string]any) error {
	if config == nil {
		return nil
	}
	if _, ok := (*config)["hil"]; ok {
		return fmt.Errorf("legacy config.hil is no longer supported; use config.review instead")
	}
	return nil
}

func mergeWorkflowBlockConfig(existing map[string]any, patch map[string]any) map[string]any {
	merged := make(map[string]any, len(existing)+len(patch))
	maps.Copy(merged, existing)
	for key, patchValue := range patch {
		existingChild, existingIsMap := merged[key].(map[string]any)
		patchChild, patchIsMap := patchValue.(map[string]any)
		if existingIsMap && patchIsMap {
			merged[key] = mergeWorkflowBlockConfig(existingChild, patchChild)
			continue
		}
		merged[key] = patchValue
	}
	return merged
}

func workflowBlocksListParams(cmd *cobra.Command, workflowID string) *retab.WorkflowBlocksListParams {
	return &retab.WorkflowBlocksListParams{
		PaginationParams: collectListParams(cmd),
		WorkflowID:       workflowID,
	}
}

func workflowBlockLookupWorkflowID(cmd *cobra.Command) *string {
	workflowID, _ := cmd.Flags().GetString("workflow-id")
	workflowID = strings.TrimSpace(workflowID)
	if workflowID == "" {
		return nil
	}
	return ptr(workflowID)
}

func resolveBlockPositionalWorkflowID(cmd *cobra.Command, args []string) (*string, string, error) {
	flagWorkflowID := workflowBlockLookupWorkflowID(cmd)
	switch len(args) {
	case 1:
		return flagWorkflowID, args[0], nil
	case 2:
		positionalWorkflowID := strings.TrimSpace(args[0])
		blockID := args[1]
		if positionalWorkflowID == "" {
			return nil, "", fmt.Errorf("workflow-id positional argument is empty")
		}
		if flagWorkflowID != nil && *flagWorkflowID != positionalWorkflowID {
			return nil, "", fmt.Errorf("conflicting workflow id: positional %q vs --workflow-id %q", positionalWorkflowID, *flagWorkflowID)
		}
		return ptr(positionalWorkflowID), blockID, nil
	default:
		return nil, "", fmt.Errorf("expected 1 or 2 positional arguments, got %d", len(args))
	}
}

var workflowsBlocksCmd = &cobra.Command{
	Use:     "blocks",
	Short:   "Manage workflow blocks",
	Long:    "Add, configure, and inspect the nodes of a workflow graph.\n\nA block is one processing step - `extract`, `split`, `classifier`, `edit`,\n`conditional`, `api_call`, `function`, etc. Each block has a typed input,\ntyped output, and a JSON config blob shaped by its type.\n\nThe workhorse here is update. Once a block is on the graph, swap its full\nconfig with workflows blocks update --config-file ./cfg.json (REPLACE) or\npatch a slice with `--merge-config-file` ./patch.json (deep merge, RFC 7396)\nrather than deleting and re-creating. Configure review inside supported\nblock configs.",
	Example: "  # List blocks\n  retab workflows blocks list wf_abc123\n\n  # Add a block from a JSON definition\n  retab workflows blocks create wf_abc123 --block-file ./extract.json\n\n  # Tune just the config of an existing block\n  retab workflows blocks update blk_def456 \\\n    --config-file ./new-config.json",
}

var workflowsBlocksCreateCmd = &cobra.Command{
	Use:     "create <workflow-id>",
	Short:   "Create a workflow block from --block-file",
	Long:    "Add a block to a workflow's draft graph. The block file is a JSON\nobject with id, type, label, position_x, position_y, width, height,\nparent_id, and config.\n\nBlock IDs are unique per ORGANIZATION, not per workflow. Reusing a\nhuman-friendly id like block_extract across two workflows in the same org\nwill fail with 409. Prefer the server-generated blk_<nanoid> form by\nomitting id unless you have a reason to pin a stable name.\n\nReview is configured inside the block's typed config as\nconfig.review.predicate. Reviewable block types are extract, split,\nclassifier, and for_each only when config.map_method is split_by_key and\nconfig.key is set. Common review predicates are always and\nvalidation_failed. Extract also supports any_required_field_null and\nfield_confidence_lt; split and split-by-key for_each support\nsplit_count_neq, any_split_pages_lt, and boundary_confidence_lt; classifier\nsupports category_in and top_margin_lt.\n\nReview is not a standalone block type.",
	Example: "  # Add one block from a JSON file\n  retab workflows blocks create wf_abc123 --block-file ./extract.json\n\n  # Minimal extract block with review\n  cat > extract-review.json <<'JSON'\n  {\n    \"type\": \"extract\",\n    \"label\": \"Extract with review\",\n    \"config\": {\n      \"model\": \"retab-small\",\n      \"inputs\": [{\"name\": \"document\", \"type\": \"file\", \"is_primary\": true}],\n      \"json_schema\": {\"type\": \"object\", \"properties\": {}, \"additionalProperties\": false},\n      \"review\": {\"predicate\": {\"kind\": \"always\"}}\n    }\n  }\n  JSON\n  retab workflows blocks create wf_abc123 --block-file ./extract-review.json",
	Args:    cobra.ExactArgs(1),
	RunE: runE(func(cmd *cobra.Command, args []string) error {
		path, _ := cmd.Flags().GetString("block-file")
		if path == "" {
			return fmt.Errorf("--block-file is required")
		}
		obj, err := readJSONMap(path)
		if err != nil {
			return err
		}
		req, err := parseBlockCreateForWorkflow(args[0], obj)
		if err != nil {
			return err
		}
		req.WorkflowID = args[0]
		client, err := newClient(cmd)
		if err != nil {
			return err
		}
		ctx, cancel := ctxFor(cmd)
		defer cancel()
		result, err := client.Workflows.Blocks.Create(ctx, &req)
		if err != nil {
			return err
		}
		return printResult(cmd, result)
	}),
}

var workflowsBlocksDeleteCmd = &cobra.Command{
	Use:     "delete [<workflow-id>] <block-id>",
	Short:   "Delete a workflow block",
	Long:    "Remove a block from the draft graph. Edges that referenced this\nblock are also deleted. Past runs that used this block remain intact.\n\nThis is destructive. Pass --yes to skip the confirmation prompt in scripts\nand CI - otherwise the command refuses to delete when stdin is not a\nterminal.\n\nBlock IDs are unique per organization, so the canonical form is delete\n<block-id>. You can also pass delete <workflow-id> <block-id>.",
	Example: "  # Remove a block\n  retab workflows blocks delete blk_def456\n\n  # Two-positional convenience form\n  retab workflows blocks delete wf_abc123 blk_def456\n\n  # Skip the prompt in scripts\n  retab workflows blocks delete blk_def456 --yes",
	Args:    cobra.RangeArgs(1, 2),
	RunE: runE(func(cmd *cobra.Command, args []string) error {
		workflowID, blockID, err := resolveBlockPositionalWorkflowID(cmd, args)
		if err != nil {
			return err
		}
		if err := confirmDestructive(cmd, "block", blockID); err != nil {
			return err
		}
		client, err := newClient(cmd)
		if err != nil {
			return err
		}
		ctx, cancel := ctxFor(cmd)
		defer cancel()
		params := &retab.WorkflowBlocksDeleteParams{WorkflowID: workflowID}
		if err := client.Workflows.Blocks.Delete(ctx, blockID, params); err != nil {
			return err
		}
		confirmDeleted("block", blockID)
		return nil
	}),
}

var workflowsBlocksGetCmd = &cobra.Command{
	Use:     "get [<workflow-id>] <block-id>",
	Short:   "Get a workflow block",
	Long:    "Fetch a single block's full definition: type, label, position,\nparent group, and the typed config blob.\n\nBlock IDs are unique per organization, so the canonical form is get\n<block-id>. As a convenience you can also pass get <workflow-id> <block-id>.\nPass --workflow-id only when the block id is not unique within your\norganization.",
	Example: "  # Inspect a block\n  retab workflows blocks get blk_def456\n\n  # Two-positional convenience form\n  retab workflows blocks get wf_abc123 blk_def456\n\n  # Disambiguate a legacy duplicate id\n  retab workflows blocks get block_split --workflow-id wf_abc123\n\n  # Save a block's config for offline editing\n  retab workflows blocks get blk_def456 \\\n    | jq '.config' > cfg.json",
	Args:    cobra.RangeArgs(1, 2),
	RunE: runE(func(cmd *cobra.Command, args []string) error {
		workflowID, blockID, err := resolveBlockPositionalWorkflowID(cmd, args)
		if err != nil {
			return err
		}
		client, err := newClient(cmd)
		if err != nil {
			return err
		}
		ctx, cancel := ctxFor(cmd)
		defer cancel()
		params := &retab.WorkflowBlocksGetParams{WorkflowID: workflowID}
		result, err := client.Workflows.Blocks.Get(ctx, blockID, params)
		if err != nil {
			return err
		}
		return printResult(cmd, result)
	}),
}

var workflowsBlocksListCmd = &cobra.Command{
	Use:     "list [workflow-id]",
	Short:   "List blocks in a workflow",
	Long:    "List every block in a workflow's draft graph, including id, type,\nlabel, position, and config.\n\nName the workflow either positionally (`list <workflow-id>`) or with\nthe `--workflow-id` flag - the two forms are equivalent. Passing both\nis accepted when they agree; an error is raised only when they disagree, so a\ntypo isn't silently masked. The workflow id is required: blocks have no\norg-wide listing.\n\nPaginate by passing the cursor from a previous response's list_metadata:\n--after for the next page, --before for the previous one. The two are\nmutually exclusive.",
	Example: "  # List all blocks (positional)\n  retab workflows blocks list wf_abc123\n\n  # Same, with the flag form\n  retab workflows blocks list --workflow-id wf_abc123\n\n  # First page of 50\n  retab workflows blocks list wf_abc123 --limit 50\n\n  # Next page, using the cursor from the previous response\n  retab workflows blocks list wf_abc123 --limit 50 \\\n    --after $(retab workflows blocks list wf_abc123 --limit 50 --output json | jq -r '.list_metadata.after')\n\n  # Get the ids only\n  retab workflows blocks list wf_abc123 | jq -r '.data[].id'",
	Args:    cobra.MaximumNArgs(1),
	RunE: runE(func(cmd *cobra.Command, args []string) error {
		// Workflow id positionally OR via --workflow-id (co-equal forms);
		// required here — blocks have no org-wide listing.
		workflowID, err := resolveWorkflowScope(cmd, args, true)
		if err != nil {
			return err
		}
		client, err := newClient(cmd)
		if err != nil {
			return err
		}
		params := workflowBlocksListParams(cmd, workflowID)
		ctx, cancel := ctxFor(cmd)
		defer cancel()
		result, err := client.Workflows.Blocks.List(ctx, params)
		if err != nil {
			return err
		}
		return printResult(cmd, result)
	}),
}

var workflowsBlocksUpdateCmd = &cobra.Command{
	Use:     "update [<workflow-id>] <block-id>",
	Short:   "Update a workflow block",
	Long:    "Tune an existing block in place.\n\n--config-file REPLACES the typed config. The file is treated as the full\nnew config and any existing key not in the file is dropped. Only use\n--config-file for review changes when replacing the whole typed config.\n\n--merge-config-file DEEP-MERGES a patch into the existing config (RFC\n7396 JSON Merge Patch). Dicts recurse, arrays/scalars replace, null\ndeletes the key. Use this when you only want to touch a slice of the\nconfig, for example adding review.\n\nPass {\"review\":null} to remove review without touching anything else. The\nflags are mutually exclusive. Layout fields only affect the visual editor.\nBlock IDs are unique per organization, so the canonical form is update\n<block-id>. You can also pass update <workflow-id> <block-id>.",
	Example: "  # Swap the config blob\n  retab workflows blocks update blk_def456 \\\n    --config-file ./new-config.json\n\n  # Two-positional convenience form\n  retab workflows blocks update wf_abc123 blk_def456 \\\n    --config-file ./new-config.json\n\n  # Add review to an existing block\n  printf '{\"review\":{\"predicate\":{\"kind\":\"always\"}}}' |\n    retab workflows blocks update blk_def456 --merge-config-file -\n\n  # Rename a block's label\n  retab workflows blocks update blk_def456 \\\n    --label \"Extract line items\"",
	Args:    cobra.RangeArgs(1, 2),
	RunE: runE(func(cmd *cobra.Command, args []string) error {
		workflowID, blockID, err := resolveBlockPositionalWorkflowID(cmd, args)
		if err != nil {
			return err
		}
		configPath, _ := cmd.Flags().GetString("config-file")
		mergeConfigPath, _ := cmd.Flags().GetString("merge-config-file")
		if configPath != "" && mergeConfigPath != "" {
			return fmt.Errorf("--config-file and --merge-config-file are mutually exclusive")
		}
		if !cmd.Flags().Changed("label") && !cmd.Flags().Changed("position-x") &&
			!cmd.Flags().Changed("position-y") && !cmd.Flags().Changed("width") &&
			!cmd.Flags().Changed("height") && !cmd.Flags().Changed("parent-id") &&
			!cmd.Flags().Changed("config-file") && !cmd.Flags().Changed("merge-config-file") {
			return fmt.Errorf("nothing to update: pass at least one of --label, --position-x, --position-y, --width, --height, --parent-id, --config-file, or --merge-config-file")
		}
		req := retab.WorkflowBlocksUpdateParams{}
		if cmd.Flags().Changed("label") {
			v, _ := cmd.Flags().GetString("label")
			req.Label = &v
		}
		if cmd.Flags().Changed("position-x") {
			v, _ := cmd.Flags().GetFloat64("position-x")
			req.PositionX = &v
		}
		if cmd.Flags().Changed("position-y") {
			v, _ := cmd.Flags().GetFloat64("position-y")
			req.PositionY = &v
		}
		if cmd.Flags().Changed("width") {
			v, _ := cmd.Flags().GetFloat64("width")
			req.Width = &v
		}
		if cmd.Flags().Changed("height") {
			v, _ := cmd.Flags().GetFloat64("height")
			req.Height = &v
		}
		if cmd.Flags().Changed("parent-id") {
			v, _ := cmd.Flags().GetString("parent-id")
			req.ParentID = &v
		}
		if configPath != "" {
			cfg, err := readJSONMap(configPath)
			if err != nil {
				return fmt.Errorf("--config-file: %w", err)
			}
			if err := rejectLegacyReviewConfig(&cfg); err != nil {
				return fmt.Errorf("--config-file: %w", err)
			}
			req.Config = &cfg
			req.ConfigMode = ptr(retab.UpdateWorkflowBlockRequestConfigModeReplace)
		}
		client, err := newClient(cmd)
		if err != nil {
			return err
		}
		ctx, cancel := ctxFor(cmd)
		defer cancel()
		if mergeConfigPath != "" {
			patch, err := readJSONMap(mergeConfigPath)
			if err != nil {
				return fmt.Errorf("--merge-config-file: %w", err)
			}
			if err := rejectLegacyReviewConfig(&patch); err != nil {
				return fmt.Errorf("--merge-config-file: %w", err)
			}
			if len(patch) == 0 {
				return fmt.Errorf("--merge-config-file %s: patch contains no keys; nothing to merge", mergeConfigPath)
			}
			req.Config = &patch
			req.ConfigMode = ptr(retab.UpdateWorkflowBlockRequestConfigModeMerge)
		}
		req.WorkflowID = workflowID
		result, err := client.Workflows.Blocks.Update(ctx, blockID, &req)
		if err != nil {
			return err
		}
		return printResult(cmd, result)
	}),
}

func init() {
	workflowsBlocksCreateCmd.Flags().String("block-file", "", "JSON file describing the block (or - for stdin)")
	workflowsBlocksDeleteCmd.Flags().BoolP("yes", "y", false, "skip the confirmation prompt (required when stdin is not a TTY)")
	workflowsBlocksDeleteCmd.Flags().String("workflow-id", "", "scope flat block-id lookup to one workflow (for legacy duplicate ids)")
	workflowsBlocksGetCmd.Flags().String("workflow-id", "", "scope flat block-id lookup to one workflow (for legacy duplicate ids)")
	workflowsBlocksListCmd.Flags().String("workflow-id", "", "workflow id (alternative to the positional form)")
	workflowsBlocksListCmd.Flags().String("before", "", "block id: return the page before this id (mutually exclusive with --after)")
	workflowsBlocksListCmd.Flags().String("after", "", "block id: return the page after this id (mutually exclusive with --before)")
	workflowsBlocksListCmd.MarkFlagsMutuallyExclusive("before", "after")
	workflowsBlocksListCmd.Flags().Var(&boundedIntFlagValue{min: 1, max: 200}, "limit", "max items to return (1-200)")
	workflowsBlocksUpdateCmd.Flags().String("label", "", "update label")
	workflowsBlocksUpdateCmd.Flags().Float64("position-x", 0, "update X position")
	workflowsBlocksUpdateCmd.Flags().Float64("position-y", 0, "update Y position")
	workflowsBlocksUpdateCmd.Flags().Var(&nonNegativeFloatFlagValue{}, "width", "update width")
	workflowsBlocksUpdateCmd.Flags().Var(&nonNegativeFloatFlagValue{}, "height", "update height")
	workflowsBlocksUpdateCmd.Flags().String("parent-id", "", "update parent id")
	workflowsBlocksUpdateCmd.Flags().String("config-file", "", "JSON file to use as the full new config - REPLACES the existing config (or - for stdin)")
	workflowsBlocksUpdateCmd.Flags().String("merge-config-file", "", "JSON file to deep-merge into the existing config; nulls delete keys (RFC 7396) (or - for stdin)")
	workflowsBlocksUpdateCmd.Flags().String("workflow-id", "", "scope flat block-id lookup to one workflow (for legacy duplicate ids)")

	workflowsBlocksCmd.AddCommand(workflowsBlocksCreateCmd, workflowsBlocksDeleteCmd, workflowsBlocksGetCmd, workflowsBlocksListCmd, workflowsBlocksUpdateCmd)
	workflowsCmd.AddCommand(workflowsBlocksCmd)
}
