// Code generated by retab-cli-emitter. DO NOT EDIT.

//go:build retab_oagen_cli_prototype && retab_oagen_cli_workflows_spec

package cmd

import (
	"fmt"
	retab "github.com/retab-dev/retab/clients/go"
	"github.com/spf13/cobra"
	"os"
)

var workflowsSpecCmd = &cobra.Command{
	Use:     "spec",
	Short:   "Manage workflows declaratively from YAML",
	Long:    "Validate, plan, apply, and get YAML workflow specs.\n\nA spec is a single YAML file describing a workflow's blocks, edges, and\nmetadata. The four verbs form a declarative workflow loop:\n\n  validate   parse + type-check the spec, no server changes\n  plan       diff the spec against the live workflow without applying\n  apply      create or update the workflow from the spec\n  get        dump a live workflow's spec back to YAML\n\nThe three POST verbs read YAML from a file path, or from stdin when the\npath is \"-\". Output is JSON on stdout, suitable for piping into `jq`.\n\n`apiVersion` is required and currently pinned at\n`workflows.retab.com/v1alpha2`. `metadata.id` is the durable identity\nused by `plan` / `apply` to decide whether to create or update; the\nsame id makes `apply` idempotent.",
	Example: "  # Round-trip a workflow through git\n  retab workflows spec get wf_abc123 > workflow.yaml\n  $EDITOR workflow.yaml\n  retab workflows spec validate workflow.yaml\n  retab workflows spec plan     workflow.yaml\n  retab workflows spec apply    workflow.yaml\n\n  # Tail of a pipe\n  cat workflow.yaml | retab workflows spec apply -",
}

var workflowsSpecValidateCmd = &cobra.Command{
	Use:     "validate <path>",
	Short:   "Parse + type-check a YAML spec without touching the server",
	Long:    "Send the YAML to the server's spec validator. No workflow is\ncreated or modified - the server only returns whether the spec parses\nand whether its referenced blocks / schemas / model ids exist.\n\nReturns a non-zero exit if validation fails, with the server's diagnostic\nJSON on stderr - wire it into pre-commit / CI to keep broken specs out\nof main.",
	Example: "  retab workflows spec validate ./workflow.yaml\n  cat workflow.yaml | retab workflows spec validate -",
	Args:    cobra.ExactArgs(1),
	RunE: runE(func(cmd *cobra.Command, args []string) error {
		yaml, err := readSpecYAML(args[0])
		if err != nil {
			return err
		}
		client, err := newClient(cmd)
		if err != nil {
			return err
		}
		ctx, cancel := ctxFor(cmd)
		defer cancel()
		result, err := client.Workflows.Spec.Validate(ctx, &retab.WorkflowSpecValidateParams{YamlDefinition: yaml})
		if err != nil {
			return translateSpecAPIError(err)
		}
		if err := failIfSpecValidationInvalid(validationResponseAsResource(result)); err != nil {
			return err
		}
		return printResult(cmd, result)
	}),
}

var workflowsSpecPlanCmd = &cobra.Command{
	Use:     "plan <path>",
	Short:   "Diff a YAML spec against the live workflow without applying",
	Long:    "Compute what would change if the spec were applied: which\nblocks would be created, updated, deleted; which edges would be re-wired.\n\nPlan is read-only - safe to run on production specs. Pair it with\n`apply` for a declarative workflow review-then-apply loop.",
	Example: "  retab workflows spec plan ./workflow.yaml\n  cat workflow.yaml | retab workflows spec plan - | jq .changes",
	Args:    cobra.ExactArgs(1),
	RunE: runE(func(cmd *cobra.Command, args []string) error {
		yaml, err := readSpecYAML(args[0])
		if err != nil {
			return err
		}
		client, err := newClient(cmd)
		if err != nil {
			return err
		}
		ctx, cancel := ctxFor(cmd)
		defer cancel()
		result, err := client.Workflows.Spec.Plan(ctx, &retab.WorkflowSpecPlanParams{YamlDefinition: yaml})
		if err != nil {
			return translateSpecAPIError(err)
		}
		if err := failIfSpecValidationInvalid(planResponseAsResource(result)); err != nil {
			return err
		}
		return printResult(cmd, result)
	}),
}

var workflowsSpecApplyCmd = &cobra.Command{
	Use:     "apply <path>",
	Short:   "Create or update a workflow from a YAML spec",
	Long:    "Apply the YAML spec. Id-less specs create a workflow with a fresh\nserver-generated id; exported specs are id-less so round-tripping one does\nnot reproduce the source workflow id.\n\nLegacy specs that explicitly include `metadata.id` are accepted for\nbackward compatibility, but the id is ignored when applying.\n\nMutating. Before applying, the command runs `spec plan` and inspects the\ndestroy count. When the plan would delete one or more resources, it\nrequires confirmation unless `--yes` is passed.",
	Example: "  retab workflows spec apply ./workflow.yaml\n  retab workflows spec apply ./workflow.yaml --yes\n  cat workflow.yaml | retab workflows spec apply -",
	Args:    cobra.ExactArgs(1),
	RunE: runE(func(cmd *cobra.Command, args []string) error {
		yaml, err := readSpecYAML(args[0])
		if err != nil {
			return err
		}
		client, err := newClient(cmd)
		if err != nil {
			return err
		}
		ctx, cancel := ctxFor(cmd)
		defer cancel()
		plan, err := client.Workflows.Spec.Plan(ctx, &retab.WorkflowSpecPlanParams{YamlDefinition: yaml})
		if err != nil {
			return translateSpecAPIError(err)
		}
		planAsResource := planResponseAsResource(plan)
		if err := failIfSpecValidationInvalid(planAsResource); err != nil {
			return err
		}
		if err := confirmDestructiveApply(cmd, planAsResource); err != nil {
			return err
		}
		result, err := client.Workflows.Spec.Apply(ctx, &retab.WorkflowSpecApplyParams{YamlDefinition: yaml})
		if err != nil {
			return translateSpecAPIError(err)
		}
		if err := failIfSpecValidationInvalid(applyResponseAsResource(result)); err != nil {
			return err
		}
		return printResult(cmd, result)
	}),
}

var workflowsSpecExportCmd = &cobra.Command{
	Use:     "get <workflow-id>",
	Aliases: []string{"export"},
	Short:   "Dump a live workflow's spec back to YAML",
	Long:    "Fetch the YAML spec representing the workflow's current state.\nUseful for round-tripping a workflow created in the dashboard back into a\ngit-managed YAML file, or for diffing two environments.\n\nBy default, the raw YAML body is written to stdout so the command can be\nredirected straight into a file. Pass `--format json` to see the full\nserver response object.",
	Example: "  retab workflows spec get wf_abc123 > workflow.yaml\n  retab workflows spec get wf_abc123 --format json | jq .",
	Args:    cobra.ExactArgs(1),
	RunE: runE(func(cmd *cobra.Command, args []string) error {
		format, err := cmd.Flags().GetString("format")
		if err != nil {
			return err
		}
		if jsonShortcut, _ := cmd.Flags().GetBool("json"); jsonShortcut && format == "yaml" {
			format = "json"
		}
		if format != "yaml" && format != "json" {
			return fmt.Errorf("invalid --format value %q (want: yaml | json)", format)
		}
		client, err := newClient(cmd)
		if err != nil {
			return err
		}
		ctx, cancel := ctxFor(cmd)
		defer cancel()
		result, err := client.Workflows.Spec.Get(ctx, args[0])
		if err != nil {
			return err
		}
		return writeSpecExport(os.Stdout, exportResponseAsResource(result), format)
	}),
}

func init() {
	workflowsSpecApplyCmd.Flags().BoolP("yes", "y", false, "skip the destructive-change confirmation prompt (required when stdin is not a TTY and the plan would destroy resources)")
	workflowsSpecExportCmd.Flags().String("format", "yaml", "output format: yaml | json")
	workflowsSpecExportCmd.Flags().Bool("json", false, "shorthand for --format json")

	workflowsSpecCmd.AddCommand(workflowsSpecValidateCmd, workflowsSpecPlanCmd, workflowsSpecApplyCmd, workflowsSpecExportCmd)
	workflowsCmd.AddCommand(workflowsSpecCmd)
}
