//go:build retab_oagen_cli_prototype && retab_oagen_cli_tables

// Code generated by retab-cli-emitter. DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	retab "github.com/retab-dev/retab/clients/go"
	"github.com/spf13/cobra"
)

var tablesCmd = &cobra.Command{
	Use:   "tables",
	Short: "Manage tables",
}

var tablesCreateCmd = &cobra.Command{
	Use:   "create",
	Short: "Create Table",
	Args:  cobra.NoArgs,
	RunE: runE(func(cmd *cobra.Command, args []string) error {
		params := retab.TablesCreateParams{}
		name, err := requireNonBlankFlag(cmd, "name")
		if err != nil {
			return err
		}
		params.Name = name
		file, err := requireNonBlankFlag(cmd, "file")
		if err != nil {
			return err
		}
		params.File = file
		if v, _ := cmd.Flags().GetString("column-schema-overrides"); v != "" || cmd.Flags().Changed("column-schema-overrides") {
			params.ColumnSchemaOverrides = ptr(v)
		}
		client, err := newClient(cmd)
		if err != nil {
			return err
		}
		ctx, cancel := ctxFor(cmd)
		defer cancel()
		result, err := client.Tables.Create(ctx, &params)
		if err != nil {
			return err
		}
		return printJSON(result)
	}),
}

var tablesDeleteCmd = &cobra.Command{
	Use:   "delete <table-id>",
	Short: "Delete Table",
	Args:  cobra.ExactArgs(1),
	RunE: runE(func(cmd *cobra.Command, args []string) error {
		if err := confirmDestructive(cmd, "tables", args[0]); err != nil {
			return err
		}
		client, err := newClient(cmd)
		if err != nil {
			return err
		}
		ctx, cancel := ctxFor(cmd)
		defer cancel()
		if err := client.Tables.Delete(ctx, args[0]); err != nil {
			return err
		}
		confirmDeleted("tables", args[0])
		return nil
	}),
}

var tablesDownloadCmd = &cobra.Command{
	Use:   "download <table-id>",
	Short: "Download Table Csv",
	Args:  cobra.ExactArgs(1),
	RunE: runE(func(cmd *cobra.Command, args []string) error {
		client, err := newClient(cmd)
		if err != nil {
			return err
		}
		ctx, cancel := ctxFor(cmd)
		defer cancel()
		return client.Tables.Download(ctx, args[0])
	}),
}

var tablesGetCmd = &cobra.Command{
	Use:   "get <table-id>",
	Short: "Get Table",
	Args:  cobra.ExactArgs(1),
	RunE: runE(func(cmd *cobra.Command, args []string) error {
		client, err := newClient(cmd)
		if err != nil {
			return err
		}
		ctx, cancel := ctxFor(cmd)
		defer cancel()
		result, err := client.Tables.Get(ctx, args[0])
		if err != nil {
			return err
		}
		return printJSON(result)
	}),
}

var tablesListCmd = &cobra.Command{
	Use:   "list",
	Short: "List Tables",
	Args:  cobra.NoArgs,
	RunE: runE(func(cmd *cobra.Command, args []string) error {
		client, err := newClient(cmd)
		if err != nil {
			return err
		}
		ctx, cancel := ctxFor(cmd)
		defer cancel()
		result, err := client.Tables.List(ctx)
		if err != nil {
			return err
		}
		return printResult(cmd, result)
	}),
}

var tablesQueryCmd = &cobra.Command{
	Use:   "query <table-id>",
	Short: "Query Table",
	Args:  cobra.ExactArgs(1),
	RunE: runE(func(cmd *cobra.Command, args []string) error {
		body := map[string]any{}
		if v, _ := cmd.Flags().GetString("filters"); v != "" || cmd.Flags().Changed("filters") {
			var filters []any
			if err := json.Unmarshal([]byte(v), &filters); err != nil {
				return fmt.Errorf("--filters must be a JSON array: %w", err)
			}
			body["filters"] = filters
		}
		if v, _ := cmd.Flags().GetString("sort-column"); v != "" || cmd.Flags().Changed("sort-column") {
			body["sort_column"] = v
		}
		if v, _ := cmd.Flags().GetString("sort-direction"); v != "" || cmd.Flags().Changed("sort-direction") {
			body["sort_direction"] = v
		}
		if v, _ := cmd.Flags().GetInt("offset"); cmd.Flags().Changed("offset") {
			body["offset"] = v
		}
		if v, _ := cmd.Flags().GetInt("limit"); cmd.Flags().Changed("limit") {
			body["limit"] = v
		}
		if v, _ := cmd.Flags().GetString("viewer-mode"); v != "" || cmd.Flags().Changed("viewer-mode") {
			body["viewer_mode"] = v
		}
		params := retab.TablesQueryParams{Body: body}
		client, err := newClient(cmd)
		if err != nil {
			return err
		}
		ctx, cancel := ctxFor(cmd)
		defer cancel()
		result, err := client.Tables.Query(ctx, args[0], &params)
		if err != nil {
			return err
		}
		return printResult(cmd, result)
	}),
}

var tablesReplaceCmd = &cobra.Command{
	Use:   "replace <table-id>",
	Short: "Replace Table",
	Args:  cobra.ExactArgs(1),
	RunE: runE(func(cmd *cobra.Command, args []string) error {
		params := retab.TablesReplaceParams{}
		file, err := requireNonBlankFlag(cmd, "file")
		if err != nil {
			return err
		}
		params.File = file
		if v, _ := cmd.Flags().GetString("column-schema-overrides"); v != "" || cmd.Flags().Changed("column-schema-overrides") {
			params.ColumnSchemaOverrides = ptr(v)
		}
		client, err := newClient(cmd)
		if err != nil {
			return err
		}
		ctx, cancel := ctxFor(cmd)
		defer cancel()
		result, err := client.Tables.Replace(ctx, args[0], &params)
		if err != nil {
			return err
		}
		return printJSON(result)
	}),
}

var tablesUpdateCmd = &cobra.Command{
	Use:   "update <table-id>",
	Short: "Update Table",
	Args:  cobra.ExactArgs(1),
	RunE: runE(func(cmd *cobra.Command, args []string) error {
		params := retab.TablesUpdateParams{}
		if v, _ := cmd.Flags().GetString("name"); v != "" || cmd.Flags().Changed("name") {
			params.Name = ptr(v)
		}
		if v, _ := cmd.Flags().GetString("metadata"); v != "" || cmd.Flags().Changed("metadata") {
			metadata, err := parseJSONMap(v)
			if err != nil {
				return fmt.Errorf("--metadata must be a JSON object: %w", err)
			}
			params.Metadata = metadata
		}
		if params.Name == nil && params.Metadata == nil {
			return fmt.Errorf("provide at least one of --name or --metadata")
		}
		client, err := newClient(cmd)
		if err != nil {
			return err
		}
		ctx, cancel := ctxFor(cmd)
		defer cancel()
		result, err := client.Tables.Update(ctx, args[0], &params)
		if err != nil {
			return err
		}
		return printJSON(result)
	}),
}

func init() {
	tablesCreateCmd.Flags().String("name", "", "name value (required)")
	_ = tablesCreateCmd.MarkFlagRequired("name")
	tablesCreateCmd.Flags().String("file", "", "file value (required)")
	_ = tablesCreateCmd.MarkFlagRequired("file")
	tablesCreateCmd.Flags().String("column-schema-overrides", "", "column-schema-overrides value")
	tablesDeleteCmd.Flags().BoolP("yes", "y", false, "skip the confirmation prompt (required when stdin is not a TTY)")
	tablesQueryCmd.Flags().String("filters", "", "JSON array of filter rules")
	tablesQueryCmd.Flags().String("sort-column", "", "column to sort by")
	tablesQueryCmd.Flags().Var(newEnumStringFlagValue("--sort-direction", "asc", "desc"), "sort-direction", "sort direction: asc | desc")
	tablesQueryCmd.Flags().Var(&nonNegativeIntFlagValue{}, "offset", "zero-based row offset")
	tablesQueryCmd.Flags().Var(&nonNegativeIntFlagValue{}, "limit", "max rows to return")
	tablesQueryCmd.Flags().String("viewer-mode", "", "viewer mode; use windowed for large tables")
	tablesReplaceCmd.Flags().String("file", "", "file value (required)")
	_ = tablesReplaceCmd.MarkFlagRequired("file")
	tablesReplaceCmd.Flags().String("column-schema-overrides", "", "column-schema-overrides value")
	tablesUpdateCmd.Flags().String("name", "", "table name")
	tablesUpdateCmd.Flags().String("metadata", "", "JSON metadata object")

	tablesCmd.AddCommand(tablesCreateCmd, tablesDeleteCmd, tablesDownloadCmd, tablesGetCmd, tablesListCmd, tablesQueryCmd, tablesReplaceCmd, tablesUpdateCmd)
	rootCmd.AddCommand(tablesCmd)
}
