// This file is auto-generated by the Retab oagen emitter. Do not edit by hand.

import { z } from 'zod';
/** POST /workflows/reviews/versions body. */
export interface CreateReviewVersionRequest {
  reviewId: string;
  parentId: string;
  /** The full reviewed snapshot to store as an immutable version. The object must match the gated block type: extract uses the raw output object; classifier uses {'category': string}; split uses {'documents': [{'name': string, 'pages': positive sorted int[]}]}; for_each uses {'partitions': [{'key': string, 'pages': positive sorted int[]}]}. The server validates the shape and stores the exact submitted object when valid. */
  snapshot: Record<string, unknown>;
  note?: string | null;
}

export interface CreateReviewVersionRequestResponse {
  review_id: string;
  parent_id: string;
  snapshot: Record<string, unknown>;
  note?: string | null;
}

export const ZCreateReviewVersionRequest = z.object({
  reviewId: z.string(),
  parentId: z.string(),
  snapshot: z.record(z.string(), z.unknown()),
  note: z.string().nullable().optional(),
}) as z.ZodType<CreateReviewVersionRequest>;

export function deserializeCreateReviewVersionRequest(
  wire: CreateReviewVersionRequestResponse
): CreateReviewVersionRequest {
  return {
    reviewId: wire['review_id'],
    parentId: wire['parent_id'],
    snapshot: wire['snapshot'],
    note: wire['note'],
  };
}

export function serializeCreateReviewVersionRequest(
  domain: CreateReviewVersionRequest
): CreateReviewVersionRequestResponse {
  return {
    review_id: domain['reviewId'],
    parent_id: domain['parentId'],
    snapshot: domain['snapshot'],
    note: domain['note'],
  };
}
