# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module Retab
  class WorkflowExportPayloadRequest
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(String) }
    def workflow_id; end

    sig { params(value: String).returns(String) }
    def workflow_id=(value); end

    sig { returns(String) }
    def block_id; end

    sig { params(value: String).returns(String) }
    def block_id=(value); end

    sig { returns(T.nilable(String)) }
    def export_source; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def export_source=(value); end

    sig { returns(T.nilable(T::Array[String])) }
    def selected_run_ids; end

    sig { params(value: T.nilable(T::Array[String])).returns(T.nilable(T::Array[String])) }
    def selected_run_ids=(value); end

    sig { returns(T.nilable(T::Array[String])) }
    def selected_doc_types; end

    sig { params(value: T.nilable(T::Array[String])).returns(T.nilable(T::Array[String])) }
    def selected_doc_types=(value); end

    sig { returns(T.nilable(String)) }
    def status; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def status=(value); end

    sig { returns(T.nilable(String)) }
    def exclude_status; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def exclude_status=(value); end

    sig { returns(T.nilable(String)) }
    def from_date; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def from_date=(value); end

    sig { returns(T.nilable(String)) }
    def to_date; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def to_date=(value); end

    sig { returns(T.nilable(String)) }
    def trigger_type; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def trigger_type=(value); end

    sig { returns(T.nilable(T::Array[String])) }
    def preferred_columns; end

    sig { params(value: T.nilable(T::Array[String])).returns(T.nilable(T::Array[String])) }
    def preferred_columns=(value); end

    sig { returns(T.nilable(String)) }
    def delimiter; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def delimiter=(value); end

    sig { returns(T.nilable(String)) }
    def line_delimiter; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def line_delimiter=(value); end

    sig { returns(T.nilable(String)) }
    def quote; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def quote=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
