// This file is auto-generated by oagen. Do not edit.

package com.retab.workflowblocks;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import com.retab.RetabClient;
import com.retab.models.UpdateWorkflowBlockRequest;
import com.retab.models.ValidateWorkflowBlockConfigRequest;
import com.retab.models.ValidateWorkflowBlockConfigResponse;
import com.retab.models.WorkflowBlock;
import com.retab.models.WorkflowBlockCreateRequest;
import com.retab.models.WorkflowBlockVersion;
import com.retab.models.WorkflowBlockVersionDiff;
import com.retab.types.UpdateWorkflowBlockRequestConfigMode;
import com.retab.types.ValidateWorkflowBlockConfigRequestConfigMode;
import com.retab.types.WorkflowBlockCreateRequestType;
import com.retab.workflowblockexecutions.WorkflowBlockExecutionsApi;
import java.io.IOException;
import java.net.URI;
import java.net.URLEncoder;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public final class WorkflowBlocksApi {
  private final RetabClient client;

  public WorkflowBlocksApi(RetabClient client) {
    this.client = client;
  }

  public RetabClient getClient() {
    return client;
  }

  public WorkflowBlockExecutionsApi executions() {
    return new WorkflowBlockExecutionsApi(client);
  }

  public List<WorkflowBlock> list(String workflowId, String before, String after, Long limit)
      throws IOException, InterruptedException {
    String path = "/v1/workflows/blocks";
    StringBuilder query = new StringBuilder();
    appendQueryParam(query, "workflow_id", workflowId);
    appendQueryParam(query, "before", before);
    appendQueryParam(query, "after", after);
    appendQueryParam(query, "limit", limit);
    URI uri = URI.create(client.getBaseUrl() + path + (query.length() == 0 ? "" : "?" + query));
    HttpRequest.BodyPublisher publisher = HttpRequest.BodyPublishers.noBody();
    HttpRequest.Builder requestBuilder =
        HttpRequest.newBuilder(uri)
            .header("Accept", "application/json")
            .header("Authorization", "Bearer " + client.getApiKey());
    HttpRequest httpRequest = requestBuilder.method("GET", publisher).build();
    HttpResponse<String> response =
        client.getHttpClient().send(httpRequest, HttpResponse.BodyHandlers.ofString());
    if (response.statusCode() < 200 || response.statusCode() >= 300) {
      throw new IOException("Request failed (" + response.statusCode() + "): " + response.body());
    }
    if (response.body() == null || response.body().isBlank()) {
      return null;
    }
    JsonNode root = client.getObjectMapper().readTree(response.body());
    JsonNode data = root.isArray() ? root : root.get("data");
    if (data == null || data.isNull()) {
      return List.of();
    }
    return client
        .getObjectMapper()
        .readValue(
            data.traverse(client.getObjectMapper()), new TypeReference<List<WorkflowBlock>>() {});
  }

  public WorkflowBlock create(WorkflowBlockCreateRequest request)
      throws IOException, InterruptedException {
    return create(
        request == null ? null : request.getWorkflowId(),
        request == null ? null : request.getId(),
        request == null ? null : request.getType(),
        request == null ? null : request.getLabel(),
        request == null ? null : request.getPositionX(),
        request == null ? null : request.getPositionY(),
        request == null ? null : request.getWidth(),
        request == null ? null : request.getHeight(),
        request == null ? null : request.getConfig(),
        request == null ? null : request.getParentId());
  }

  public WorkflowBlock create(
      String workflowId,
      String id,
      WorkflowBlockCreateRequestType type,
      String label,
      Double positionX,
      Double positionY,
      Double width,
      Double height,
      Map<String, Object> config,
      String parentId)
      throws IOException, InterruptedException {
    String path = "/v1/workflows/blocks";
    StringBuilder query = new StringBuilder();
    URI uri = URI.create(client.getBaseUrl() + path + (query.length() == 0 ? "" : "?" + query));
    Map<String, Object> body = new LinkedHashMap<>();
    body.put("workflow_id", workflowId);
    if (id != null) {
      body.put("id", id);
    }
    body.put("type", type);
    if (label != null) {
      body.put("label", label);
    }
    if (positionX != null) {
      body.put("position_x", positionX);
    }
    if (positionY != null) {
      body.put("position_y", positionY);
    }
    if (width != null) {
      body.put("width", width);
    }
    if (height != null) {
      body.put("height", height);
    }
    if (config != null) {
      body.put("config", config);
    }
    if (parentId != null) {
      body.put("parent_id", parentId);
    }
    String requestBody = client.getObjectMapper().writeValueAsString(body);
    HttpRequest.BodyPublisher publisher = HttpRequest.BodyPublishers.ofString(requestBody);
    HttpRequest.Builder requestBuilder =
        HttpRequest.newBuilder(uri)
            .header("Accept", "application/json")
            .header("Authorization", "Bearer " + client.getApiKey());
    requestBuilder.header("Content-Type", "application/json");
    HttpRequest httpRequest = requestBuilder.method("POST", publisher).build();
    HttpResponse<String> response =
        client.getHttpClient().send(httpRequest, HttpResponse.BodyHandlers.ofString());
    if (response.statusCode() < 200 || response.statusCode() >= 300) {
      throw new IOException("Request failed (" + response.statusCode() + "): " + response.body());
    }
    if (response.body() == null || response.body().isBlank()) {
      return null;
    }
    return client.getObjectMapper().readValue(response.body(), WorkflowBlock.class);
  }

  public List<WorkflowBlockVersion> listVersions(
      String workflowId,
      String blockId,
      String workflowVersionId,
      String before,
      String after,
      Long limit)
      throws IOException, InterruptedException {
    String path = "/v1/workflows/blocks/versions";
    StringBuilder query = new StringBuilder();
    appendQueryParam(query, "workflow_id", workflowId);
    appendQueryParam(query, "block_id", blockId);
    appendQueryParam(query, "workflow_version_id", workflowVersionId);
    appendQueryParam(query, "before", before);
    appendQueryParam(query, "after", after);
    appendQueryParam(query, "limit", limit);
    URI uri = URI.create(client.getBaseUrl() + path + (query.length() == 0 ? "" : "?" + query));
    HttpRequest.BodyPublisher publisher = HttpRequest.BodyPublishers.noBody();
    HttpRequest.Builder requestBuilder =
        HttpRequest.newBuilder(uri)
            .header("Accept", "application/json")
            .header("Authorization", "Bearer " + client.getApiKey());
    HttpRequest httpRequest = requestBuilder.method("GET", publisher).build();
    HttpResponse<String> response =
        client.getHttpClient().send(httpRequest, HttpResponse.BodyHandlers.ofString());
    if (response.statusCode() < 200 || response.statusCode() >= 300) {
      throw new IOException("Request failed (" + response.statusCode() + "): " + response.body());
    }
    if (response.body() == null || response.body().isBlank()) {
      return null;
    }
    JsonNode root = client.getObjectMapper().readTree(response.body());
    JsonNode data = root.isArray() ? root : root.get("data");
    if (data == null || data.isNull()) {
      return List.of();
    }
    return client
        .getObjectMapper()
        .readValue(
            data.traverse(client.getObjectMapper()),
            new TypeReference<List<WorkflowBlockVersion>>() {});
  }

  public WorkflowBlockVersionDiff listDiff(String fromBlockVersionId, String toBlockVersionId)
      throws IOException, InterruptedException {
    String path = "/v1/workflows/blocks/versions/diff";
    StringBuilder query = new StringBuilder();
    appendQueryParam(query, "from_block_version_id", fromBlockVersionId);
    appendQueryParam(query, "to_block_version_id", toBlockVersionId);
    URI uri = URI.create(client.getBaseUrl() + path + (query.length() == 0 ? "" : "?" + query));
    HttpRequest.BodyPublisher publisher = HttpRequest.BodyPublishers.noBody();
    HttpRequest.Builder requestBuilder =
        HttpRequest.newBuilder(uri)
            .header("Accept", "application/json")
            .header("Authorization", "Bearer " + client.getApiKey());
    HttpRequest httpRequest = requestBuilder.method("GET", publisher).build();
    HttpResponse<String> response =
        client.getHttpClient().send(httpRequest, HttpResponse.BodyHandlers.ofString());
    if (response.statusCode() < 200 || response.statusCode() >= 300) {
      throw new IOException("Request failed (" + response.statusCode() + "): " + response.body());
    }
    if (response.body() == null || response.body().isBlank()) {
      return null;
    }
    return client.getObjectMapper().readValue(response.body(), WorkflowBlockVersionDiff.class);
  }

  public WorkflowBlockVersion getVersion(String blockVersionId)
      throws IOException, InterruptedException {
    String path = "/v1/workflows/blocks/versions/" + encodePathSegment(blockVersionId);
    StringBuilder query = new StringBuilder();
    URI uri = URI.create(client.getBaseUrl() + path + (query.length() == 0 ? "" : "?" + query));
    HttpRequest.BodyPublisher publisher = HttpRequest.BodyPublishers.noBody();
    HttpRequest.Builder requestBuilder =
        HttpRequest.newBuilder(uri)
            .header("Accept", "application/json")
            .header("Authorization", "Bearer " + client.getApiKey());
    HttpRequest httpRequest = requestBuilder.method("GET", publisher).build();
    HttpResponse<String> response =
        client.getHttpClient().send(httpRequest, HttpResponse.BodyHandlers.ofString());
    if (response.statusCode() < 200 || response.statusCode() >= 300) {
      throw new IOException("Request failed (" + response.statusCode() + "): " + response.body());
    }
    if (response.body() == null || response.body().isBlank()) {
      return null;
    }
    return client.getObjectMapper().readValue(response.body(), WorkflowBlockVersion.class);
  }

  public WorkflowBlock createVersionRestore(String blockVersionId)
      throws IOException, InterruptedException {
    String path = "/v1/workflows/blocks/versions/" + encodePathSegment(blockVersionId) + "/restore";
    StringBuilder query = new StringBuilder();
    URI uri = URI.create(client.getBaseUrl() + path + (query.length() == 0 ? "" : "?" + query));
    HttpRequest.BodyPublisher publisher = HttpRequest.BodyPublishers.noBody();
    HttpRequest.Builder requestBuilder =
        HttpRequest.newBuilder(uri)
            .header("Accept", "application/json")
            .header("Authorization", "Bearer " + client.getApiKey());
    HttpRequest httpRequest = requestBuilder.method("POST", publisher).build();
    HttpResponse<String> response =
        client.getHttpClient().send(httpRequest, HttpResponse.BodyHandlers.ofString());
    if (response.statusCode() < 200 || response.statusCode() >= 300) {
      throw new IOException("Request failed (" + response.statusCode() + "): " + response.body());
    }
    if (response.body() == null || response.body().isBlank()) {
      return null;
    }
    return client.getObjectMapper().readValue(response.body(), WorkflowBlock.class);
  }

  public WorkflowBlock get(String blockId) throws IOException, InterruptedException {
    return get(blockId, null);
  }

  public WorkflowBlock get(String blockId, String workflowId)
      throws IOException, InterruptedException {
    String path = "/v1/workflows/blocks/" + encodePathSegment(blockId);
    StringBuilder query = new StringBuilder();
    appendQueryParam(query, "workflow_id", workflowId);
    URI uri = URI.create(client.getBaseUrl() + path + (query.length() == 0 ? "" : "?" + query));
    HttpRequest.BodyPublisher publisher = HttpRequest.BodyPublishers.noBody();
    HttpRequest.Builder requestBuilder =
        HttpRequest.newBuilder(uri)
            .header("Accept", "application/json")
            .header("Authorization", "Bearer " + client.getApiKey());
    HttpRequest httpRequest = requestBuilder.method("GET", publisher).build();
    HttpResponse<String> response =
        client.getHttpClient().send(httpRequest, HttpResponse.BodyHandlers.ofString());
    if (response.statusCode() < 200 || response.statusCode() >= 300) {
      throw new IOException("Request failed (" + response.statusCode() + "): " + response.body());
    }
    if (response.body() == null || response.body().isBlank()) {
      return null;
    }
    return client.getObjectMapper().readValue(response.body(), WorkflowBlock.class);
  }

  public WorkflowBlock update(String blockId, String workflowId, UpdateWorkflowBlockRequest request)
      throws IOException, InterruptedException {
    return update(
        blockId,
        workflowId,
        request == null ? null : request.getLabel(),
        request == null ? null : request.getPositionX(),
        request == null ? null : request.getPositionY(),
        request == null ? null : request.getWidth(),
        request == null ? null : request.getHeight(),
        request == null ? null : request.getConfig(),
        request == null ? null : request.getParentId(),
        request == null ? null : request.getConfigMode());
  }

  public WorkflowBlock update(
      String blockId,
      String workflowId,
      String label,
      Double positionX,
      Double positionY,
      Double width,
      Double height,
      Map<String, Object> config,
      String parentId,
      UpdateWorkflowBlockRequestConfigMode configMode)
      throws IOException, InterruptedException {
    String path = "/v1/workflows/blocks/" + encodePathSegment(blockId);
    StringBuilder query = new StringBuilder();
    appendQueryParam(query, "workflow_id", workflowId);
    URI uri = URI.create(client.getBaseUrl() + path + (query.length() == 0 ? "" : "?" + query));
    Map<String, Object> body = new LinkedHashMap<>();
    if (label != null) {
      body.put("label", label);
    }
    if (positionX != null) {
      body.put("position_x", positionX);
    }
    if (positionY != null) {
      body.put("position_y", positionY);
    }
    if (width != null) {
      body.put("width", width);
    }
    if (height != null) {
      body.put("height", height);
    }
    if (config != null) {
      body.put("config", config);
    }
    if (parentId != null) {
      body.put("parent_id", parentId);
    }
    if (configMode != null) {
      body.put("config_mode", configMode);
    }
    String requestBody = client.getObjectMapper().writeValueAsString(body);
    HttpRequest.BodyPublisher publisher = HttpRequest.BodyPublishers.ofString(requestBody);
    HttpRequest.Builder requestBuilder =
        HttpRequest.newBuilder(uri)
            .header("Accept", "application/json")
            .header("Authorization", "Bearer " + client.getApiKey());
    requestBuilder.header("Content-Type", "application/json");
    HttpRequest httpRequest = requestBuilder.method("PATCH", publisher).build();
    HttpResponse<String> response =
        client.getHttpClient().send(httpRequest, HttpResponse.BodyHandlers.ofString());
    if (response.statusCode() < 200 || response.statusCode() >= 300) {
      throw new IOException("Request failed (" + response.statusCode() + "): " + response.body());
    }
    if (response.body() == null || response.body().isBlank()) {
      return null;
    }
    return client.getObjectMapper().readValue(response.body(), WorkflowBlock.class);
  }

  public Object delete(String blockId) throws IOException, InterruptedException {
    return delete(blockId, null);
  }

  public Object delete(String blockId, String workflowId) throws IOException, InterruptedException {
    String path = "/v1/workflows/blocks/" + encodePathSegment(blockId);
    StringBuilder query = new StringBuilder();
    appendQueryParam(query, "workflow_id", workflowId);
    URI uri = URI.create(client.getBaseUrl() + path + (query.length() == 0 ? "" : "?" + query));
    HttpRequest.BodyPublisher publisher = HttpRequest.BodyPublishers.noBody();
    HttpRequest.Builder requestBuilder =
        HttpRequest.newBuilder(uri)
            .header("Accept", "application/json")
            .header("Authorization", "Bearer " + client.getApiKey());
    HttpRequest httpRequest = requestBuilder.method("DELETE", publisher).build();
    HttpResponse<String> response =
        client.getHttpClient().send(httpRequest, HttpResponse.BodyHandlers.ofString());
    if (response.statusCode() < 200 || response.statusCode() >= 300) {
      throw new IOException("Request failed (" + response.statusCode() + "): " + response.body());
    }
    if (response.body() == null || response.body().isBlank()) {
      return null;
    }
    return client.getObjectMapper().readValue(response.body(), Object.class);
  }

  public ValidateWorkflowBlockConfigResponse createBlockValidateConfig(
      String blockId, String workflowId, ValidateWorkflowBlockConfigRequest request)
      throws IOException, InterruptedException {
    return createBlockValidateConfig(
        blockId,
        workflowId,
        request == null ? null : request.getConfig(),
        request == null ? null : request.getConfigMode());
  }

  public ValidateWorkflowBlockConfigResponse createBlockValidateConfig(
      String blockId,
      String workflowId,
      Map<String, Object> config,
      ValidateWorkflowBlockConfigRequestConfigMode configMode)
      throws IOException, InterruptedException {
    String path = "/v1/workflows/blocks/" + encodePathSegment(blockId) + "/validate-config";
    StringBuilder query = new StringBuilder();
    appendQueryParam(query, "workflow_id", workflowId);
    URI uri = URI.create(client.getBaseUrl() + path + (query.length() == 0 ? "" : "?" + query));
    Map<String, Object> body = new LinkedHashMap<>();
    body.put("config", config);
    if (configMode != null) {
      body.put("config_mode", configMode);
    }
    String requestBody = client.getObjectMapper().writeValueAsString(body);
    HttpRequest.BodyPublisher publisher = HttpRequest.BodyPublishers.ofString(requestBody);
    HttpRequest.Builder requestBuilder =
        HttpRequest.newBuilder(uri)
            .header("Accept", "application/json")
            .header("Authorization", "Bearer " + client.getApiKey());
    requestBuilder.header("Content-Type", "application/json");
    HttpRequest httpRequest = requestBuilder.method("POST", publisher).build();
    HttpResponse<String> response =
        client.getHttpClient().send(httpRequest, HttpResponse.BodyHandlers.ofString());
    if (response.statusCode() < 200 || response.statusCode() >= 300) {
      throw new IOException("Request failed (" + response.statusCode() + "): " + response.body());
    }
    if (response.body() == null || response.body().isBlank()) {
      return null;
    }
    return client
        .getObjectMapper()
        .readValue(response.body(), ValidateWorkflowBlockConfigResponse.class);
  }

  private static String encodePathSegment(Object value) {
    return URLEncoder.encode(serializeParam(value), StandardCharsets.UTF_8).replace("+", "%20");
  }

  private static void appendQueryParam(StringBuilder query, String name, Object value) {
    if (value == null) {
      return;
    }
    if (query.length() > 0) {
      query.append("&");
    }
    query.append(URLEncoder.encode(name, StandardCharsets.UTF_8).replace("+", "%20"));
    query.append("=");
    query.append(
        URLEncoder.encode(serializeParam(value), StandardCharsets.UTF_8).replace("+", "%20"));
  }

  private static String serializeParam(Object value) {
    if (value instanceof Enum<?>) {
      try {
        Object serialized = value.getClass().getMethod("getValue").invoke(value);
        if (serialized != null) {
          return String.valueOf(serialized);
        }
      } catch (ReflectiveOperationException ignored) {
        // Fall through to the enum name if the enum does not expose a wire value.
      }
    }
    return String.valueOf(value);
  }
}
