// This file is auto-generated by the Retab oagen emitter. Do not edit by hand.

import { z } from 'zod';
import type {
  V1UsageUsageRunTriggeredBy,
  V1UsageUsageRunTriggeredByResponse,
} from './v-1-usage-usage-run-triggered-by.interface.js';
import {
  ZV1UsageUsageRunTriggeredBy,
  deserializeV1UsageUsageRunTriggeredBy,
  serializeV1UsageUsageRunTriggeredBy,
} from './v-1-usage-usage-run-triggered-by.interface.js';

export interface UsageRunRecord {
  completedAt: Date | null;
  createdAt: Date | null;
  credits: number;
  durationMs: number | null;
  executionDurationMs: number;
  pageCount: number;
  retryCount: number;
  runId: string;
  startedAt: Date | null;
  status: string;
  triggerType: string;
  triggeredBy?: V1UsageUsageRunTriggeredBy | null;
  workflowId: string;
}

export interface UsageRunRecordResponse {
  completed_at: string | null;
  created_at: string | null;
  credits: number;
  duration_ms: number | null;
  execution_duration_ms: number;
  page_count: number;
  retry_count: number;
  run_id: string;
  started_at: string | null;
  status: string;
  trigger_type: string;
  triggered_by?: V1UsageUsageRunTriggeredByResponse | null;
  workflow_id: string;
}

export const ZUsageRunRecord = z.object({
  completedAt: z.coerce.date().nullable(),
  createdAt: z.coerce.date().nullable(),
  credits: z.number(),
  durationMs: z.number().int().nullable(),
  executionDurationMs: z.number().int(),
  pageCount: z.number().int(),
  retryCount: z.number().int(),
  runId: z.string(),
  startedAt: z.coerce.date().nullable(),
  status: z.string(),
  triggerType: z.string(),
  triggeredBy: ZV1UsageUsageRunTriggeredBy.nullable().optional(),
  workflowId: z.string(),
}) as z.ZodType<UsageRunRecord>;

export function deserializeUsageRunRecord(wire: UsageRunRecordResponse): UsageRunRecord {
  return {
    completedAt:
      wire['completed_at'] == null ? wire['completed_at'] : new Date(wire['completed_at']),
    createdAt: wire['created_at'] == null ? wire['created_at'] : new Date(wire['created_at']),
    credits: wire['credits'],
    durationMs: wire['duration_ms'],
    executionDurationMs: wire['execution_duration_ms'],
    pageCount: wire['page_count'],
    retryCount: wire['retry_count'],
    runId: wire['run_id'],
    startedAt: wire['started_at'] == null ? wire['started_at'] : new Date(wire['started_at']),
    status: wire['status'],
    triggerType: wire['trigger_type'],
    triggeredBy:
      wire['triggered_by'] == null
        ? (wire['triggered_by'] as undefined)
        : wire['triggered_by'] == null
          ? wire['triggered_by']
          : deserializeV1UsageUsageRunTriggeredBy(wire['triggered_by']),
    workflowId: wire['workflow_id'],
  };
}

export function serializeUsageRunRecord(domain: UsageRunRecord): UsageRunRecordResponse {
  return {
    completed_at:
      domain['completedAt'] == null ? domain['completedAt'] : domain['completedAt'].toISOString(),
    created_at:
      domain['createdAt'] == null ? domain['createdAt'] : domain['createdAt'].toISOString(),
    credits: domain['credits'],
    duration_ms: domain['durationMs'],
    execution_duration_ms: domain['executionDurationMs'],
    page_count: domain['pageCount'],
    retry_count: domain['retryCount'],
    run_id: domain['runId'],
    started_at:
      domain['startedAt'] == null ? domain['startedAt'] : domain['startedAt'].toISOString(),
    status: domain['status'],
    trigger_type: domain['triggerType'],
    triggered_by:
      domain['triggeredBy'] == null
        ? (domain['triggeredBy'] as undefined)
        : domain['triggeredBy'] == null
          ? domain['triggeredBy']
          : serializeV1UsageUsageRunTriggeredBy(domain['triggeredBy']),
    workflow_id: domain['workflowId'],
  };
}
