// This file is auto-generated by the Retab oagen emitter. Do not edit by hand.

import { z } from 'zod';
export interface UsagePrimitiveTriggeredBy {
  accessTokenId: string | null;
  apiKeyId: string | null;
  authMethod: string | null;
  keyName: string | null;
  keyPrefix: string | null;
  userId: string | null;
}

export interface UsagePrimitiveTriggeredByResponse {
  access_token_id: string | null;
  api_key_id: string | null;
  auth_method: string | null;
  key_name: string | null;
  key_prefix: string | null;
  user_id: string | null;
}

export const ZUsagePrimitiveTriggeredBy = z.object({
  accessTokenId: z.string().nullable(),
  apiKeyId: z.string().nullable(),
  authMethod: z.string().nullable(),
  keyName: z.string().nullable(),
  keyPrefix: z.string().nullable(),
  userId: z.string().nullable(),
}) as z.ZodType<UsagePrimitiveTriggeredBy>;

export function deserializeUsagePrimitiveTriggeredBy(
  wire: UsagePrimitiveTriggeredByResponse
): UsagePrimitiveTriggeredBy {
  return {
    accessTokenId: wire['access_token_id'],
    apiKeyId: wire['api_key_id'],
    authMethod: wire['auth_method'],
    keyName: wire['key_name'],
    keyPrefix: wire['key_prefix'],
    userId: wire['user_id'],
  };
}

export function serializeUsagePrimitiveTriggeredBy(
  domain: UsagePrimitiveTriggeredBy
): UsagePrimitiveTriggeredByResponse {
  return {
    access_token_id: domain['accessTokenId'],
    api_key_id: domain['apiKeyId'],
    auth_method: domain['authMethod'],
    key_name: domain['keyName'],
    key_prefix: domain['keyPrefix'],
    user_id: domain['userId'],
  };
}
