<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Service;

use Retab\Resource\DeclarativeApplyResponse;
use Retab\Resource\DeclarativeExportResponse;
use Retab\Resource\DeclarativeValidationResponse;

class WorkflowSpec
{
    public function __construct(
        private readonly \Retab\HttpClient $client,
    ) {}

    /**
     * Validate Workflow Spec
     *
     * Validate declarative YAML without changing the workflow.
     *
     * Any error-level diagnostic responds with 400 and the structured issues.
     * Warnings do not make a spec invalid: a warning-only spec responds with
     * 200, `is_valid=True`, and the warnings in `diagnostics`.
     * @param string $yamlDefinition Workflow YAML definition
     * @param string|null $projectId Project that should own a workflow created from this spec. Required when applying a spec that creates a new workflow.
     * @return \Retab\Resource\DeclarativeValidationResponse
     * @throws \Retab\Exception\RetabException
     */
    public function validate(
        string $yamlDefinition,
        ?string $projectId = null,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\Resource\DeclarativeValidationResponse {
        $body = array_filter([
            'yaml_definition' => $yamlDefinition,
            'project_id' => $projectId,
        ], fn($v) => $v !== null);
        $response = $this->client->request(
            method: 'POST',
            path: 'v1/workflows/spec/validate',
            body: $body,
            options: $options,
        );
        return DeclarativeValidationResponse::fromArray($response);
    }

    /**
     * Export Workflow Spec
     *
     * Export draft workflow state as canonical declarative YAML.
     * @param string $workflowId
     * @return \Retab\Resource\DeclarativeExportResponse
     * @throws \Retab\Exception\RetabException
     */
    public function get(
        string $workflowId,
        ?\Retab\RequestOptions $options = null,
    ): \Retab\Resource\DeclarativeExportResponse {
        $response = $this->client->request(
            method: 'GET',
            path: 'v1/workflows/' . rawurlencode($workflowId) . '/spec',
            options: $options,
        );
        return DeclarativeExportResponse::fromArray($response);
    }
}
