# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module Retab
  class RejectReviewRequest < Retab::Types::BaseModel

    HASH_ATTRS = {
      version_id: :version_id,
      reason: :reason
    }.freeze

    attr_accessor(
      :version_id,
      :reason
    )

    def initialize(json)
      super()
      hash = self.class.normalize(json)
      @version_id = hash[:version_id]
      @reason = hash[:reason]
    end
  end
end
