# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module Retab
  class ReconstructResponse < Retab::Types::BaseModel

    HASH_ATTRS = {
      tables: :tables
    }.freeze

    attr_accessor :tables

    def initialize(json)
      super()
      hash = self.class.normalize(json)
      @tables = (hash[:tables] || []).map { |item| item ? Retab::ReconstructEnrichedTable.new(item) : nil }
    end
  end
end
