# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require "test_helper"

class WorkflowBlockExecutionsTest < Minitest::Test
  include FixtureHelper

  def setup
    @client = Retab::Client.new(api_key: "sk_test_123")
  end

  def test_list_returns_expected_result
    stub_request(:get, %r{\Ahttps://api\.retab\.com/v1/workflows/blocks/executions(\?|\z)})
      .to_return(body: "{\"data\": [], \"list_metadata\": {}}", status: 200)
    result = @client.workflow_block_executions.list(run_id: "stub", block_id: "stub")
    assert_kind_of(Retab::PaginatedList, result)
  end

  def test_list_requires_required_query_params
    assert_raises(ArgumentError) do
      @client.workflow_block_executions.list
    end
  end

  def test_create_returns_expected_result
    stub_request(:post, %r{\Ahttps://api\.retab\.com/v1/workflows/blocks/executions(\?|\z)})
      .to_return(body: "{}", status: 200)
    result = @client.workflow_block_executions.create(run_id: "stub", block_id: "stub")
    refute_nil(result)
  end

  # Parameterized authentication error tests (one per endpoint).
  [
    {
      name: :list,
      verb: :get,
      url: %r{\Ahttps://api\.retab\.com/v1/workflows/blocks/executions(\?|\z)},
      args: {run_id: "stub", block_id: "stub"}
    },
    {
      name: :create,
      verb: :post,
      url: %r{\Ahttps://api\.retab\.com/v1/workflows/blocks/executions(\?|\z)},
      args: {run_id: "stub", block_id: "stub"}
    }
  ].each do |spec|
    define_method("test_#{spec[:name]}_raises_authentication_error_on_401") do
      stub_request(spec[:verb], spec[:url])
        .to_return(body: "{\"message\": \"Unauthorized\"}", status: 401)
      assert_raises(Retab::AuthenticationError) do
        @client.workflow_block_executions.send(spec[:name], **(spec[:args] || {}))
      end
    end
  end
end
