# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require 'test_helper'

class WorkflowSpecsTest < Minitest::Test
  include FixtureHelper

  def setup
    @client = Retab::Client.new(api_key: "sk_test_123")
  end

  def test_validate_returns_expected_result
    stub_request(:post, %r{\Ahttps://api\.retab\.com/v1/workflows/spec/validate(\?|\z)})
      .to_return(body: "{}", status: 200)
    result = @client.workflow_specs.validate(yaml_definition: "stub")
    refute_nil result
  end

  def test_plan_returns_expected_result
    stub_request(:post, %r{\Ahttps://api\.retab\.com/v1/workflows/spec/plan(\?|\z)})
      .to_return(body: "{}", status: 200)
    result = @client.workflow_specs.plan(yaml_definition: "stub")
    refute_nil result
  end

  def test_apply_returns_expected_result
    stub_request(:post, %r{\Ahttps://api\.retab\.com/v1/workflows/spec/apply(\?|\z)})
      .to_return(body: "{}", status: 200)
    result = @client.workflow_specs.apply(yaml_definition: "stub")
    refute_nil result
  end

  def test_get_returns_expected_result
    stub_request(:get, %r{\Ahttps://api\.retab\.com/v1/workflows/stub/spec(\?|\z)})
      .to_return(body: "{}", status: 200)
    result = @client.workflow_specs.get(workflow_id: "stub")
    refute_nil result
  end

  # Parameterized authentication error tests (one per endpoint).
  [
    { name: :validate, verb: :post, url: %r{\Ahttps://api\.retab\.com/v1/workflows/spec/validate(\?|\z)}, args: { yaml_definition: "stub" } },
    { name: :plan, verb: :post, url: %r{\Ahttps://api\.retab\.com/v1/workflows/spec/plan(\?|\z)}, args: { yaml_definition: "stub" } },
    { name: :apply, verb: :post, url: %r{\Ahttps://api\.retab\.com/v1/workflows/spec/apply(\?|\z)}, args: { yaml_definition: "stub" } },
    { name: :get, verb: :get, url: %r{\Ahttps://api\.retab\.com/v1/workflows/stub/spec(\?|\z)}, args: { workflow_id: "stub" } },
  ].each do |spec|
    define_method("test_#{spec[:name]}_raises_authentication_error_on_401") do
      stub_request(spec[:verb], spec[:url])
        .to_return(body: '{"message": "Unauthorized"}', status: 401)
      assert_raises(Retab::AuthenticationError) do
        @client.workflow_specs.send(spec[:name], **(spec[:args] || {}))
      end
    end
  end
end
