// This file is auto-generated by oagen. Do not edit.

package com.retab.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonEnumDefaultValue;
import com.fasterxml.jackson.annotation.JsonValue;

public enum ExperimentSummaryMetricsResponseBlockType {
  @JsonEnumDefaultValue
  UNKNOWN("unknown"),
  EXTRACT("extract"),
  CLASSIFIER("classifier"),
  SPLIT("split"),
  FOR_EACH("for_each");

  private final String value;

  ExperimentSummaryMetricsResponseBlockType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @JsonCreator
  public static ExperimentSummaryMetricsResponseBlockType fromValue(String value) {
    for (ExperimentSummaryMetricsResponseBlockType item : values()) {
      if (item.value.equals(value)) {
        return item;
      }
    }
    return UNKNOWN;
  }
}
