// This file is auto-generated by oagen. Do not edit.

package com.retab.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonEnumDefaultValue;
import com.fasterxml.jackson.annotation.JsonValue;

public enum ReviewVerdict {
  @JsonEnumDefaultValue
  UNKNOWN("unknown"),
  APPROVED("approved"),
  REJECTED("rejected");

  private final String value;

  ReviewVerdict(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @JsonCreator
  public static ReviewVerdict fromValue(String value) {
    for (ReviewVerdict item : values()) {
      if (item.value.equals(value)) {
        return item;
      }
    }
    return UNKNOWN;
  }
}
