// This file is auto-generated by oagen. Do not edit.

package com.retab.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonEnumDefaultValue;
import com.fasterxml.jackson.annotation.JsonValue;

public enum SourceJobStatus {
  @JsonEnumDefaultValue
  UNKNOWN("unknown"),
  PENDING("pending"),
  RUNNING("running"),
  COMPLETED("completed"),
  ERROR("error");

  private final String value;

  SourceJobStatus(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @JsonCreator
  public static SourceJobStatus fromValue(String value) {
    for (SourceJobStatus item : values()) {
      if (item.value.equals(value)) {
        return item;
      }
    }
    return UNKNOWN;
  }
}
