// This file is auto-generated by oagen. Do not edit.

package com.retab.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonEnumDefaultValue;
import com.fasterxml.jackson.annotation.JsonValue;

public enum WorkflowRunsTriggerType {
  @JsonEnumDefaultValue
  UNKNOWN("unknown"),
  MANUAL("manual"),
  API("api"),
  SCHEDULE("schedule"),
  WEBHOOK("webhook"),
  EMAIL("email"),
  RESTART("restart");

  private final String value;

  WorkflowRunsTriggerType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @JsonCreator
  public static WorkflowRunsTriggerType fromValue(String value) {
    for (WorkflowRunsTriggerType item : values()) {
      if (item.value.equals(value)) {
        return item;
      }
    }
    return UNKNOWN;
  }
}
