// This file is auto-generated by oagen. Do not edit.

package com.retab.workflows;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import com.retab.RetabClient;
import com.retab.models.CreateWorkflowRequest;
import com.retab.models.DeclarativeApplyResponse;
import com.retab.models.DeclarativePlanResponse;
import com.retab.models.DeclarativeWorkflowRequest;
import com.retab.models.UpdateWorkflowRequest;
import com.retab.models.Workflow;
import com.retab.models.WorkflowGraphVersion;
import com.retab.models.WorkflowGraphVersionDiff;
import com.retab.types.SortOrder;
import com.retab.workflowartifacts.WorkflowArtifactsApi;
import com.retab.workflowblocks.WorkflowBlocksApi;
import com.retab.workflowedges.WorkflowEdgesApi;
import com.retab.workflowexperiments.WorkflowExperimentsApi;
import com.retab.workflowreviews.WorkflowReviewsApi;
import com.retab.workflowruns.WorkflowRunsApi;
import com.retab.workflowspec.WorkflowSpecApi;
import com.retab.workflowsteps.WorkflowStepsApi;
import java.io.IOException;
import java.net.URI;
import java.net.URLEncoder;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public final class WorkflowsApi {
  private final RetabClient client;

  public WorkflowsApi(RetabClient client) {
    this.client = client;
  }

  public RetabClient getClient() {
    return client;
  }

  public WorkflowArtifactsApi artifacts() {
    return new WorkflowArtifactsApi(client);
  }

  public WorkflowBlocksApi blocks() {
    return new WorkflowBlocksApi(client);
  }

  public WorkflowEdgesApi edges() {
    return new WorkflowEdgesApi(client);
  }

  public WorkflowExperimentsApi experiments() {
    return new WorkflowExperimentsApi(client);
  }

  public WorkflowReviewsApi reviews() {
    return new WorkflowReviewsApi(client);
  }

  public WorkflowRunsApi runs() {
    return new WorkflowRunsApi(client);
  }

  public WorkflowSpecApi spec() {
    return new WorkflowSpecApi(client);
  }

  public WorkflowStepsApi steps() {
    return new WorkflowStepsApi(client);
  }

  public List<Workflow> list() throws IOException, InterruptedException {
    return list(null, null, null, null, null, null);
  }

  public List<Workflow> list(
      String before, String after, Long limit, SortOrder order, String sortBy, String projectId)
      throws IOException, InterruptedException {
    String path = "/v1/workflows";
    StringBuilder query = new StringBuilder();
    appendQueryParam(query, "before", before);
    appendQueryParam(query, "after", after);
    appendQueryParam(query, "limit", limit);
    appendQueryParam(query, "order", order);
    appendQueryParam(query, "sort_by", sortBy);
    appendQueryParam(query, "project_id", projectId);
    URI uri = URI.create(client.getBaseUrl() + path + (query.length() == 0 ? "" : "?" + query));
    HttpRequest.BodyPublisher publisher = HttpRequest.BodyPublishers.noBody();
    HttpRequest.Builder requestBuilder =
        HttpRequest.newBuilder(uri)
            .header("Accept", "application/json")
            .header("Authorization", "Bearer " + client.getApiKey());
    HttpRequest httpRequest = requestBuilder.method("GET", publisher).build();
    HttpResponse<String> response =
        client.getHttpClient().send(httpRequest, HttpResponse.BodyHandlers.ofString());
    if (response.statusCode() < 200 || response.statusCode() >= 300) {
      throw new IOException("Request failed (" + response.statusCode() + "): " + response.body());
    }
    if (response.body() == null || response.body().isBlank()) {
      return null;
    }
    JsonNode root = client.getObjectMapper().readTree(response.body());
    JsonNode data = root.isArray() ? root : root.get("data");
    if (data == null || data.isNull()) {
      return List.of();
    }
    return client
        .getObjectMapper()
        .readValue(data.traverse(client.getObjectMapper()), new TypeReference<List<Workflow>>() {});
  }

  public Workflow create(CreateWorkflowRequest request) throws IOException, InterruptedException {
    return create(
        request == null ? null : request.getName(),
        request == null ? null : request.getDescription(),
        request == null ? null : request.getProjectId());
  }

  public Workflow create(String name, String description, String projectId)
      throws IOException, InterruptedException {
    String path = "/v1/workflows";
    StringBuilder query = new StringBuilder();
    URI uri = URI.create(client.getBaseUrl() + path + (query.length() == 0 ? "" : "?" + query));
    Map<String, Object> body = new LinkedHashMap<>();
    if (name != null) {
      body.put("name", name);
    }
    if (description != null) {
      body.put("description", description);
    }
    body.put("project_id", projectId);
    String requestBody = client.getObjectMapper().writeValueAsString(body);
    HttpRequest.BodyPublisher publisher = HttpRequest.BodyPublishers.ofString(requestBody);
    HttpRequest.Builder requestBuilder =
        HttpRequest.newBuilder(uri)
            .header("Accept", "application/json")
            .header("Authorization", "Bearer " + client.getApiKey());
    requestBuilder.header("Content-Type", "application/json");
    HttpRequest httpRequest = requestBuilder.method("POST", publisher).build();
    HttpResponse<String> response =
        client.getHttpClient().send(httpRequest, HttpResponse.BodyHandlers.ofString());
    if (response.statusCode() < 200 || response.statusCode() >= 300) {
      throw new IOException("Request failed (" + response.statusCode() + "): " + response.body());
    }
    if (response.body() == null || response.body().isBlank()) {
      return null;
    }
    return client.getObjectMapper().readValue(response.body(), Workflow.class);
  }

  public DeclarativeApplyResponse apply(DeclarativeWorkflowRequest request, String workflowId)
      throws IOException, InterruptedException {
    return apply(
        request == null ? null : request.getYamlDefinition(),
        request == null ? null : request.getProjectId(),
        workflowId);
  }

  public DeclarativeApplyResponse apply(String yamlDefinition, String projectId, String workflowId)
      throws IOException, InterruptedException {
    String path =
        workflowId != null && !workflowId.isEmpty()
            ? "/v1/workflows/" + encodePathSegment(workflowId) + "/spec/apply"
            : "/v1/workflows/spec/apply";
    StringBuilder query = new StringBuilder();
    URI uri = URI.create(client.getBaseUrl() + path + (query.length() == 0 ? "" : "?" + query));
    Map<String, Object> body = new LinkedHashMap<>();
    body.put("yaml_definition", yamlDefinition);
    if (projectId != null) {
      body.put("project_id", projectId);
    }
    String requestBody = client.getObjectMapper().writeValueAsString(body);
    HttpRequest.BodyPublisher publisher = HttpRequest.BodyPublishers.ofString(requestBody);
    HttpRequest.Builder requestBuilder =
        HttpRequest.newBuilder(uri)
            .header("Accept", "application/json")
            .header("Authorization", "Bearer " + client.getApiKey());
    requestBuilder.header("Content-Type", "application/json");
    HttpRequest httpRequest = requestBuilder.method("POST", publisher).build();
    HttpResponse<String> response =
        client.getHttpClient().send(httpRequest, HttpResponse.BodyHandlers.ofString());
    if (response.statusCode() < 200 || response.statusCode() >= 300) {
      throw new IOException("Request failed (" + response.statusCode() + "): " + response.body());
    }
    if (response.body() == null || response.body().isBlank()) {
      return null;
    }
    return client.getObjectMapper().readValue(response.body(), DeclarativeApplyResponse.class);
  }

  public DeclarativePlanResponse plan(DeclarativeWorkflowRequest request, String workflowId)
      throws IOException, InterruptedException {
    return plan(
        request == null ? null : request.getYamlDefinition(),
        request == null ? null : request.getProjectId(),
        workflowId);
  }

  public DeclarativePlanResponse plan(String yamlDefinition, String projectId, String workflowId)
      throws IOException, InterruptedException {
    String path =
        workflowId != null && !workflowId.isEmpty()
            ? "/v1/workflows/" + encodePathSegment(workflowId) + "/spec/plan"
            : "/v1/workflows/spec/plan";
    StringBuilder query = new StringBuilder();
    URI uri = URI.create(client.getBaseUrl() + path + (query.length() == 0 ? "" : "?" + query));
    Map<String, Object> body = new LinkedHashMap<>();
    body.put("yaml_definition", yamlDefinition);
    if (projectId != null) {
      body.put("project_id", projectId);
    }
    String requestBody = client.getObjectMapper().writeValueAsString(body);
    HttpRequest.BodyPublisher publisher = HttpRequest.BodyPublishers.ofString(requestBody);
    HttpRequest.Builder requestBuilder =
        HttpRequest.newBuilder(uri)
            .header("Accept", "application/json")
            .header("Authorization", "Bearer " + client.getApiKey());
    requestBuilder.header("Content-Type", "application/json");
    HttpRequest httpRequest = requestBuilder.method("POST", publisher).build();
    HttpResponse<String> response =
        client.getHttpClient().send(httpRequest, HttpResponse.BodyHandlers.ofString());
    if (response.statusCode() < 200 || response.statusCode() >= 300) {
      throw new IOException("Request failed (" + response.statusCode() + "): " + response.body());
    }
    if (response.body() == null || response.body().isBlank()) {
      return null;
    }
    return client.getObjectMapper().readValue(response.body(), DeclarativePlanResponse.class);
  }

  public List<WorkflowGraphVersion> listVersions(
      String workflowId, String before, String after, Long limit)
      throws IOException, InterruptedException {
    String path = "/v1/workflows/versions";
    StringBuilder query = new StringBuilder();
    appendQueryParam(query, "workflow_id", workflowId);
    appendQueryParam(query, "before", before);
    appendQueryParam(query, "after", after);
    appendQueryParam(query, "limit", limit);
    URI uri = URI.create(client.getBaseUrl() + path + (query.length() == 0 ? "" : "?" + query));
    HttpRequest.BodyPublisher publisher = HttpRequest.BodyPublishers.noBody();
    HttpRequest.Builder requestBuilder =
        HttpRequest.newBuilder(uri)
            .header("Accept", "application/json")
            .header("Authorization", "Bearer " + client.getApiKey());
    HttpRequest httpRequest = requestBuilder.method("GET", publisher).build();
    HttpResponse<String> response =
        client.getHttpClient().send(httpRequest, HttpResponse.BodyHandlers.ofString());
    if (response.statusCode() < 200 || response.statusCode() >= 300) {
      throw new IOException("Request failed (" + response.statusCode() + "): " + response.body());
    }
    if (response.body() == null || response.body().isBlank()) {
      return null;
    }
    JsonNode root = client.getObjectMapper().readTree(response.body());
    JsonNode data = root.isArray() ? root : root.get("data");
    if (data == null || data.isNull()) {
      return List.of();
    }
    return client
        .getObjectMapper()
        .readValue(
            data.traverse(client.getObjectMapper()),
            new TypeReference<List<WorkflowGraphVersion>>() {});
  }

  public WorkflowGraphVersionDiff listDiff(
      String workflowId, String fromWorkflowVersionId, String toWorkflowVersionId)
      throws IOException, InterruptedException {
    String path = "/v1/workflows/versions/diff";
    StringBuilder query = new StringBuilder();
    appendQueryParam(query, "workflow_id", workflowId);
    appendQueryParam(query, "from_workflow_version_id", fromWorkflowVersionId);
    appendQueryParam(query, "to_workflow_version_id", toWorkflowVersionId);
    URI uri = URI.create(client.getBaseUrl() + path + (query.length() == 0 ? "" : "?" + query));
    HttpRequest.BodyPublisher publisher = HttpRequest.BodyPublishers.noBody();
    HttpRequest.Builder requestBuilder =
        HttpRequest.newBuilder(uri)
            .header("Accept", "application/json")
            .header("Authorization", "Bearer " + client.getApiKey());
    HttpRequest httpRequest = requestBuilder.method("GET", publisher).build();
    HttpResponse<String> response =
        client.getHttpClient().send(httpRequest, HttpResponse.BodyHandlers.ofString());
    if (response.statusCode() < 200 || response.statusCode() >= 300) {
      throw new IOException("Request failed (" + response.statusCode() + "): " + response.body());
    }
    if (response.body() == null || response.body().isBlank()) {
      return null;
    }
    return client.getObjectMapper().readValue(response.body(), WorkflowGraphVersionDiff.class);
  }

  public WorkflowGraphVersion getVersion(String workflowVersionId, String workflowId)
      throws IOException, InterruptedException {
    String path = "/v1/workflows/versions/" + encodePathSegment(workflowVersionId);
    StringBuilder query = new StringBuilder();
    appendQueryParam(query, "workflow_id", workflowId);
    URI uri = URI.create(client.getBaseUrl() + path + (query.length() == 0 ? "" : "?" + query));
    HttpRequest.BodyPublisher publisher = HttpRequest.BodyPublishers.noBody();
    HttpRequest.Builder requestBuilder =
        HttpRequest.newBuilder(uri)
            .header("Accept", "application/json")
            .header("Authorization", "Bearer " + client.getApiKey());
    HttpRequest httpRequest = requestBuilder.method("GET", publisher).build();
    HttpResponse<String> response =
        client.getHttpClient().send(httpRequest, HttpResponse.BodyHandlers.ofString());
    if (response.statusCode() < 200 || response.statusCode() >= 300) {
      throw new IOException("Request failed (" + response.statusCode() + "): " + response.body());
    }
    if (response.body() == null || response.body().isBlank()) {
      return null;
    }
    return client.getObjectMapper().readValue(response.body(), WorkflowGraphVersion.class);
  }

  public Workflow createVersionRestore(String workflowVersionId, String workflowId)
      throws IOException, InterruptedException {
    String path = "/v1/workflows/versions/" + encodePathSegment(workflowVersionId) + "/restore";
    StringBuilder query = new StringBuilder();
    appendQueryParam(query, "workflow_id", workflowId);
    URI uri = URI.create(client.getBaseUrl() + path + (query.length() == 0 ? "" : "?" + query));
    HttpRequest.BodyPublisher publisher = HttpRequest.BodyPublishers.noBody();
    HttpRequest.Builder requestBuilder =
        HttpRequest.newBuilder(uri)
            .header("Accept", "application/json")
            .header("Authorization", "Bearer " + client.getApiKey());
    HttpRequest httpRequest = requestBuilder.method("POST", publisher).build();
    HttpResponse<String> response =
        client.getHttpClient().send(httpRequest, HttpResponse.BodyHandlers.ofString());
    if (response.statusCode() < 200 || response.statusCode() >= 300) {
      throw new IOException("Request failed (" + response.statusCode() + "): " + response.body());
    }
    if (response.body() == null || response.body().isBlank()) {
      return null;
    }
    return client.getObjectMapper().readValue(response.body(), Workflow.class);
  }

  public Workflow get(String workflowId) throws IOException, InterruptedException {
    String path = "/v1/workflows/" + encodePathSegment(workflowId);
    StringBuilder query = new StringBuilder();
    URI uri = URI.create(client.getBaseUrl() + path + (query.length() == 0 ? "" : "?" + query));
    HttpRequest.BodyPublisher publisher = HttpRequest.BodyPublishers.noBody();
    HttpRequest.Builder requestBuilder =
        HttpRequest.newBuilder(uri)
            .header("Accept", "application/json")
            .header("Authorization", "Bearer " + client.getApiKey());
    HttpRequest httpRequest = requestBuilder.method("GET", publisher).build();
    HttpResponse<String> response =
        client.getHttpClient().send(httpRequest, HttpResponse.BodyHandlers.ofString());
    if (response.statusCode() < 200 || response.statusCode() >= 300) {
      throw new IOException("Request failed (" + response.statusCode() + "): " + response.body());
    }
    if (response.body() == null || response.body().isBlank()) {
      return null;
    }
    return client.getObjectMapper().readValue(response.body(), Workflow.class);
  }

  public Workflow update(String workflowId, UpdateWorkflowRequest request)
      throws IOException, InterruptedException {
    return update(
        workflowId,
        request == null ? null : request.getName(),
        request == null ? null : request.getDescription());
  }

  public Workflow update(String workflowId, String name, String description)
      throws IOException, InterruptedException {
    String path = "/v1/workflows/" + encodePathSegment(workflowId);
    StringBuilder query = new StringBuilder();
    URI uri = URI.create(client.getBaseUrl() + path + (query.length() == 0 ? "" : "?" + query));
    Map<String, Object> body = new LinkedHashMap<>();
    if (name != null) {
      body.put("name", name);
    }
    if (description != null) {
      body.put("description", description);
    }
    String requestBody = client.getObjectMapper().writeValueAsString(body);
    HttpRequest.BodyPublisher publisher = HttpRequest.BodyPublishers.ofString(requestBody);
    HttpRequest.Builder requestBuilder =
        HttpRequest.newBuilder(uri)
            .header("Accept", "application/json")
            .header("Authorization", "Bearer " + client.getApiKey());
    requestBuilder.header("Content-Type", "application/json");
    HttpRequest httpRequest = requestBuilder.method("PATCH", publisher).build();
    HttpResponse<String> response =
        client.getHttpClient().send(httpRequest, HttpResponse.BodyHandlers.ofString());
    if (response.statusCode() < 200 || response.statusCode() >= 300) {
      throw new IOException("Request failed (" + response.statusCode() + "): " + response.body());
    }
    if (response.body() == null || response.body().isBlank()) {
      return null;
    }
    return client.getObjectMapper().readValue(response.body(), Workflow.class);
  }

  public Object delete(String workflowId) throws IOException, InterruptedException {
    String path = "/v1/workflows/" + encodePathSegment(workflowId);
    StringBuilder query = new StringBuilder();
    URI uri = URI.create(client.getBaseUrl() + path + (query.length() == 0 ? "" : "?" + query));
    HttpRequest.BodyPublisher publisher = HttpRequest.BodyPublishers.noBody();
    HttpRequest.Builder requestBuilder =
        HttpRequest.newBuilder(uri)
            .header("Accept", "application/json")
            .header("Authorization", "Bearer " + client.getApiKey());
    HttpRequest httpRequest = requestBuilder.method("DELETE", publisher).build();
    HttpResponse<String> response =
        client.getHttpClient().send(httpRequest, HttpResponse.BodyHandlers.ofString());
    if (response.statusCode() < 200 || response.statusCode() >= 300) {
      throw new IOException("Request failed (" + response.statusCode() + "): " + response.body());
    }
    if (response.body() == null || response.body().isBlank()) {
      return null;
    }
    return client.getObjectMapper().readValue(response.body(), Object.class);
  }

  public Workflow discardDraft(String workflowId) throws IOException, InterruptedException {
    String path = "/v1/workflows/" + encodePathSegment(workflowId) + "/discard-draft";
    StringBuilder query = new StringBuilder();
    URI uri = URI.create(client.getBaseUrl() + path + (query.length() == 0 ? "" : "?" + query));
    HttpRequest.BodyPublisher publisher = HttpRequest.BodyPublishers.noBody();
    HttpRequest.Builder requestBuilder =
        HttpRequest.newBuilder(uri)
            .header("Accept", "application/json")
            .header("Authorization", "Bearer " + client.getApiKey());
    HttpRequest httpRequest = requestBuilder.method("POST", publisher).build();
    HttpResponse<String> response =
        client.getHttpClient().send(httpRequest, HttpResponse.BodyHandlers.ofString());
    if (response.statusCode() < 200 || response.statusCode() >= 300) {
      throw new IOException("Request failed (" + response.statusCode() + "): " + response.body());
    }
    if (response.body() == null || response.body().isBlank()) {
      return null;
    }
    return client.getObjectMapper().readValue(response.body(), Workflow.class);
  }

  public Workflow publish(String workflowId) throws IOException, InterruptedException {
    String path = "/v1/workflows/" + encodePathSegment(workflowId) + "/publish";
    StringBuilder query = new StringBuilder();
    URI uri = URI.create(client.getBaseUrl() + path + (query.length() == 0 ? "" : "?" + query));
    HttpRequest.BodyPublisher publisher = HttpRequest.BodyPublishers.noBody();
    HttpRequest.Builder requestBuilder =
        HttpRequest.newBuilder(uri)
            .header("Accept", "application/json")
            .header("Authorization", "Bearer " + client.getApiKey());
    HttpRequest httpRequest = requestBuilder.method("POST", publisher).build();
    HttpResponse<String> response =
        client.getHttpClient().send(httpRequest, HttpResponse.BodyHandlers.ofString());
    if (response.statusCode() < 200 || response.statusCode() >= 300) {
      throw new IOException("Request failed (" + response.statusCode() + "): " + response.body());
    }
    if (response.body() == null || response.body().isBlank()) {
      return null;
    }
    return client.getObjectMapper().readValue(response.body(), Workflow.class);
  }

  private static String encodePathSegment(Object value) {
    return URLEncoder.encode(serializeParam(value), StandardCharsets.UTF_8).replace("+", "%20");
  }

  private static void appendQueryParam(StringBuilder query, String name, Object value) {
    if (value == null) {
      return;
    }
    if (query.length() > 0) {
      query.append("&");
    }
    query.append(URLEncoder.encode(name, StandardCharsets.UTF_8).replace("+", "%20"));
    query.append("=");
    query.append(
        URLEncoder.encode(serializeParam(value), StandardCharsets.UTF_8).replace("+", "%20"));
  }

  private static String serializeParam(Object value) {
    if (value instanceof Enum<?>) {
      try {
        Object serialized = value.getClass().getMethod("getValue").invoke(value);
        if (serialized != null) {
          return String.valueOf(serialized);
        }
      } catch (ReflectiveOperationException ignored) {
        // Fall through to the enum name if the enum does not expose a wire value.
      }
    }
    return String.valueOf(value);
  }
}
