// This file is auto-generated by the Retab oagen emitter. Do not edit by hand.

import { z } from 'zod';
import type {
  PrimitiveError,
  PrimitiveErrorResponse,
} from '../../classifications/interfaces/primitive-error.interface.js';
import {
  ZPrimitiveError,
  deserializePrimitiveError,
  serializePrimitiveError,
} from '../../classifications/interfaces/primitive-error.interface.js';
import type { MainServerServicesV1SchemasModelsSchemaGenerationStatus } from './main-server-services-v-1-schemas-models-schema-generation-status.interface.js';
import { ZMainServerServicesV1SchemasModelsSchemaGenerationStatus } from './main-server-services-v-1-schemas-models-schema-generation-status.interface.js';

/** Public generated schema response. */
export interface MainServerServicesV1SchemasModelsSchemaGeneration {
  /** @default "schema" */
  object?: string;
  createdAt?: Date | null;
  /** @default {} */
  jsonSchema?: Record<string, unknown>;
  /** @default true */
  strict?: boolean;
  /** Unique identifier of the schema generation. */
  id?: string;
  /**
   * Lifecycle status. The synchronous path returns 'completed'. Background runs progress pending -> queued -> in_progress -> completed | failed | cancelled.
   * @default "pending"
   */
  status?: MainServerServicesV1SchemasModelsSchemaGenerationStatus;
  /** Error details when a background run fails; null otherwise. Always present so consumers can read it without an existence check. */
  error?: PrimitiveError | null;
}

export interface MainServerServicesV1SchemasModelsSchemaGenerationResponse {
  object?: string;
  created_at?: string | null;
  json_schema?: Record<string, unknown>;
  strict?: boolean;
  id?: string;
  status?: MainServerServicesV1SchemasModelsSchemaGenerationStatus;
  error?: PrimitiveErrorResponse | null;
}

export const ZMainServerServicesV1SchemasModelsSchemaGeneration = z.object({
  object: z.string().optional(),
  createdAt: z.coerce.date().nullable().optional(),
  jsonSchema: z.record(z.string(), z.unknown()).optional(),
  strict: z.boolean().optional(),
  id: z.string().optional(),
  status: ZMainServerServicesV1SchemasModelsSchemaGenerationStatus.optional(),
  error: ZPrimitiveError.nullable().optional(),
}) as z.ZodType<MainServerServicesV1SchemasModelsSchemaGeneration>;

export function deserializeMainServerServicesV1SchemasModelsSchemaGeneration(
  wire: MainServerServicesV1SchemasModelsSchemaGenerationResponse
): MainServerServicesV1SchemasModelsSchemaGeneration {
  return {
    object: wire['object'],
    createdAt:
      wire['created_at'] == null
        ? (wire['created_at'] as undefined)
        : wire['created_at'] == null
          ? wire['created_at']
          : new Date(wire['created_at']),
    jsonSchema: wire['json_schema'],
    strict: wire['strict'],
    id: wire['id'],
    status: wire['status'],
    error:
      wire['error'] == null
        ? (wire['error'] as undefined)
        : wire['error'] == null
          ? wire['error']
          : deserializePrimitiveError(wire['error']),
  };
}

export function serializeMainServerServicesV1SchemasModelsSchemaGeneration(
  domain: MainServerServicesV1SchemasModelsSchemaGeneration
): MainServerServicesV1SchemasModelsSchemaGenerationResponse {
  return {
    object: domain['object'],
    created_at:
      domain['createdAt'] == null
        ? (domain['createdAt'] as undefined)
        : domain['createdAt'] == null
          ? domain['createdAt']
          : domain['createdAt'].toISOString(),
    json_schema: domain['jsonSchema'],
    strict: domain['strict'],
    id: domain['id'],
    status: domain['status'],
    error:
      domain['error'] == null
        ? (domain['error'] as undefined)
        : domain['error'] == null
          ? domain['error']
          : serializePrimitiveError(domain['error']),
  };
}
