# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module Retab
  class WhileLoopTermination < Retab::Types::BaseModel

    HASH_ATTRS = {
      operation: :operation,
      id: :id,
      run_id: :run_id,
      step_id: :step_id,
      termination_reason: :termination_reason,
      evaluations: :evaluations,
      created_at: :created_at
    }.freeze

    attr_accessor(
      :operation,
      :id,
      :run_id,
      :step_id,
      :termination_reason,
      :evaluations,
      :created_at
    )

    def initialize(json)
      super()
      hash = self.class.normalize(json)
      @operation = hash[:operation].nil? ? "while_loop_termination" : hash[:operation]
      @id = hash[:id]
      @run_id = hash[:run_id]
      @step_id = hash[:step_id]
      @termination_reason = hash[:termination_reason]
      @evaluations = (hash[:evaluations] || []).map { |item| item ? Retab::ConditionEvaluationResult.new(item) : nil }
      @created_at = hash[:created_at]
    end
  end
end
