<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class AuthStatusEnvironment implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $id,
        public ?string $name = null,
        public ?EnvironmentType $type = null,
    ) {}

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'id',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for AuthStatusEnvironment::fromArray()");
            }
        }
        return new self(
            id: $data['id'],
            name: $data['name'] ?? null,
            type: isset($data['type']) ? EnvironmentType::from($data['type']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'name' => $this->name,
            'type' => $this->type?->value,
        ];
    }
}
