<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class CreateSecretRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $name,
        public string $value,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'name',
            'value',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for CreateSecretRequest::fromArray()");
            }
        }
        return new self(
            name: $data['name'],
            value: $data['value'],
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'name' => $this->name,
            'value' => $this->value,
        ];
    }
}
