<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/**
 * Request body to create an experiment run.
 *
 * `workflow_id` is optional; when omitted it is taken from the experiment,
 * and when supplied it must match the experiment's workflow.
 */
readonly class CreateExperimentRunRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** The experiment to create a run for. */
        public string $experimentId,
        /** Optional. When omitted, the workflow is derived from the experiment record. When supplied, must match the experiment's workflow_id (404 otherwise). */
        public ?string $workflowId = null,
        /** Optional short-lived token returned by the run-plan preview. When supplied, run creation rejects if the current plan no longer matches the preview. */
        public ?string $planToken = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'experiment_id',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for CreateExperimentRunRequest::fromArray()");
            }
        }
        return new self(
            experimentId: $data['experiment_id'],
            workflowId: $data['workflow_id'] ?? null,
            planToken: $data['plan_token'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'experiment_id' => $this->experimentId,
            'workflow_id' => $this->workflowId,
            'plan_token' => $this->planToken,
        ];
    }
}
