<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class EvalRunTrigger implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public TriggerInfoType $type,
    ) {}

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'type',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for EvalRunTrigger::fromArray()");
            }
        }
        return new self(
            type: TriggerInfoType::from($data['type']),
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'type' => $this->type->value,
        ];
    }
}
