<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

enum EvidenceSourceRole: string
{
    case Answer = 'answer';
    case Input = 'input';
    case Comparison = 'comparison';
}
