<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** Public generated schema response. */
readonly class MainServerServicesV1SchemasModelsSchemaGeneration implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public ?string $object = null,
        public ?\DateTimeImmutable $createdAt = null,
        /** @var array<string, mixed>|null */
        public ?array $jsonSchema = null,
        public ?bool $strict = null,
        /** Unique identifier of the schema generation. */
        public ?string $id = null,
        /** Lifecycle status. The synchronous path returns 'completed'. Background runs progress pending -> queued -> in_progress -> completed | failed | cancelled. */
        public ?EditStatus $status = null,
        /** Error details when a background run fails; null otherwise. Always present so consumers can read it without an existence check. */
        public ?PrimitiveError $error = null,
    ) {}

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            object: $data['object'] ?? null,
            createdAt: isset($data['created_at']) ? new \DateTimeImmutable($data['created_at']) : null,
            jsonSchema: $data['json_schema'] ?? null,
            strict: $data['strict'] ?? null,
            id: $data['id'] ?? null,
            status: isset($data['status']) ? EditStatus::from($data['status']) : null,
            error: isset($data['error']) ? PrimitiveError::fromArray($data['error']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'object' => $this->object,
            'created_at' => $this->createdAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
            'json_schema' => $this->jsonSchema,
            'strict' => $this->strict,
            'id' => $this->id,
            'status' => $this->status?->value,
            'error' => $this->error?->toArray(),
        ];
    }
}
