<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class PartialSchema implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public ?string $object = null,
        public ?\DateTimeImmutable $createdAt = null,
        /** @var array<string, mixed>|null */
        public ?array $jsonSchema = null,
        public ?bool $strict = null,
    ) {}

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            object: $data['object'] ?? null,
            createdAt: isset($data['created_at']) ? new \DateTimeImmutable($data['created_at']) : null,
            jsonSchema: $data['json_schema'] ?? null,
            strict: $data['strict'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'object' => $this->object,
            'created_at' => $this->createdAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
            'json_schema' => $this->jsonSchema,
            'strict' => $this->strict,
        ];
    }
}
