<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** Public handle payload exposed by workflow step APIs. */
readonly class PublicHandlePayload implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Type of payload */
        public PublicHandlePayloadType $type,
        /** For file handles: document reference */
        public ?FileRef $document = null,
        /** For JSON handles: structured data */
        public mixed $data = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'type',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for PublicHandlePayload::fromArray()");
            }
        }
        return new self(
            type: PublicHandlePayloadType::from($data['type']),
            document: isset($data['document']) ? FileRef::fromArray($data['document']) : null,
            data: $data['data'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'type' => $this->type->value,
            'document' => $this->document?->toArray(),
            'data' => $this->data,
        ];
    }
}
