<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/**
 * Timing information for a run.
 *
 * Three event timestamps that consumers cannot reconstruct on their own.
 * Wall-clock duration is a trivial `completed_at - started_at` subtraction
 * done client-side; it is not stored or exposed.
 */
readonly class RunTiming implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** When the run record was created */
        public ?\DateTimeImmutable $createdAt = null,
        /** When the run started executing */
        public ?\DateTimeImmutable $startedAt = null,
        /** When the run finished executing */
        public ?\DateTimeImmutable $completedAt = null,
    ) {}

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            createdAt: isset($data['created_at']) ? new \DateTimeImmutable($data['created_at']) : null,
            startedAt: isset($data['started_at']) ? new \DateTimeImmutable($data['started_at']) : null,
            completedAt: isset($data['completed_at']) ? new \DateTimeImmutable($data['completed_at']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'created_at' => $this->createdAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
            'started_at' => $this->startedAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
            'completed_at' => $this->completedAt?->format(\DateTimeInterface::RFC3339_EXTENDED),
        ];
    }
}
