<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class SourceFieldEvidence implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public SourceFieldEvidenceKind $kind,
        /**
         * Printed answer locations and supporting inputs. Supporting evidence does not establish that an inferred answer is correct.
         * @var array<\Retab\Resource\EvidenceSource>|null
         */
        public ?array $sources,
        public SourceFieldEvidenceStatus $status,
    ) {}

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'kind',
            'sources',
            'status',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for SourceFieldEvidence::fromArray()");
            }
        }
        return new self(
            kind: SourceFieldEvidenceKind::from($data['kind']),
            sources: isset($data['sources']) ? array_map(fn($item) => EvidenceSource::fromArray($item), $data['sources']) : null,
            status: SourceFieldEvidenceStatus::from($data['status']),
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'kind' => $this->kind->value,
            'sources' => $this->sources !== null ? array_map(fn($item) => $item->toArray(), $this->sources) : null,
            'status' => $this->status->value,
        ];
    }
}
