<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

readonly class WorkflowTableValidationRequest implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** @var array<string>|null */
        public ?array $requiredColumns = null,
        /** @var array<string, \Retab\Resource\WorkflowTableValidationColumnRule>|null */
        public ?array $columns = null,
        /** @var array<array<string>>|null */
        public ?array $unique = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            requiredColumns: $data['required_columns'] ?? null,
            columns: $data['columns'] ?? null,
            unique: $data['unique'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'required_columns' => $this->requiredColumns,
            'columns' => $this->columns,
            'unique' => $this->unique,
        ];
    }
}
