<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** The outcome of one test within a test run: its `lifecycle`, `timing`, and `verdict`. */
readonly class WorkflowTestResult implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        public string $id,
        public string $testId,
        public string $workflowId,
        public string $blockId,
        public string $blockType,
        public ?string $workflowTestRunId = null,
        public PendingWorkflowTestRun|QueuedWorkflowTestRun|RunningWorkflowTestRun|CompletedWorkflowTestRun|ErrorWorkflowTestRun|CancelledWorkflowTestRun|null $lifecycle = null,
        public ?WorkflowTestRunTiming $timing = null,
        /** Verdict label populated only when the underlying test reaches a terminal lifecycle state and the verdict could be determined. Execution-error details flow through `lifecycle`, not through this enum. */
        public ?AssertionOutcome $verdict = null,
        public ?string $executionFingerprint = null,
        public ?string $handleInputsFingerprint = null,
        public ?string $workflowDraftFingerprint = null,
        public ?string $blockConfigFingerprint = null,
        public ?StepArtifactRef $artifact = null,
        /** @var array<string, \Retab\Resource\JsonHandleInput|\Retab\Resource\FileHandleInput>|null */
        public ?array $handleInputs = null,
        /** @var array<string, \Retab\Resource\JsonHandleInput|\Retab\Resource\FileHandleInput>|null */
        public ?array $handleOutputs = null,
        /** @var array<string>|null */
        public ?array $routingDecisions = null,
        /** @var array<string>|null */
        public ?array $warnings = null,
        public ?AssertionResult $assertionResult = null,
        public ?VerdictSummary $verdictSummary = null,
    ) {}

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'id',
            'test_id',
            'workflow_id',
            'block_id',
            'block_type',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for WorkflowTestResult::fromArray()");
            }
        }
        return new self(
            id: $data['id'],
            testId: $data['test_id'],
            workflowId: $data['workflow_id'],
            blockId: $data['block_id'],
            blockType: $data['block_type'],
            workflowTestRunId: $data['workflow_test_run_id'] ?? null,
            lifecycle: isset($data['lifecycle']) ? match ($data['lifecycle']['status'] ?? null) {
                'cancelled' => CancelledWorkflowTestRun::fromArray($data['lifecycle']), 'completed' => CompletedWorkflowTestRun::fromArray($data['lifecycle']), 'error' => ErrorWorkflowTestRun::fromArray($data['lifecycle']), 'pending' => PendingWorkflowTestRun::fromArray($data['lifecycle']), 'queued' => QueuedWorkflowTestRun::fromArray($data['lifecycle']), 'running' => RunningWorkflowTestRun::fromArray($data['lifecycle']), default => throw new \UnexpectedValueException(sprintf('Unknown status: %s', json_encode($data['lifecycle']['status'] ?? null))),
            } : null,
            timing: isset($data['timing']) ? WorkflowTestRunTiming::fromArray($data['timing']) : null,
            verdict: isset($data['verdict']) ? AssertionOutcome::from($data['verdict']) : null,
            executionFingerprint: $data['execution_fingerprint'] ?? null,
            handleInputsFingerprint: $data['handle_inputs_fingerprint'] ?? null,
            workflowDraftFingerprint: $data['workflow_draft_fingerprint'] ?? null,
            blockConfigFingerprint: $data['block_config_fingerprint'] ?? null,
            artifact: isset($data['artifact']) ? StepArtifactRef::fromArray($data['artifact']) : null,
            handleInputs: $data['handle_inputs'] ?? null,
            handleOutputs: $data['handle_outputs'] ?? null,
            routingDecisions: $data['routing_decisions'] ?? null,
            warnings: $data['warnings'] ?? null,
            assertionResult: isset($data['assertion_result']) ? AssertionResult::fromArray($data['assertion_result']) : null,
            verdictSummary: isset($data['verdict_summary']) ? VerdictSummary::fromArray($data['verdict_summary']) : null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'test_id' => $this->testId,
            'workflow_id' => $this->workflowId,
            'block_id' => $this->blockId,
            'block_type' => $this->blockType,
            'workflow_test_run_id' => $this->workflowTestRunId,
            'lifecycle' => $this->lifecycle?->toArray(),
            'timing' => $this->timing?->toArray(),
            'verdict' => $this->verdict?->value,
            'execution_fingerprint' => $this->executionFingerprint,
            'handle_inputs_fingerprint' => $this->handleInputsFingerprint,
            'workflow_draft_fingerprint' => $this->workflowDraftFingerprint,
            'block_config_fingerprint' => $this->blockConfigFingerprint,
            'artifact' => $this->artifact?->toArray(),
            'handle_inputs' => $this->handleInputs,
            'handle_outputs' => $this->handleOutputs,
            'routing_decisions' => $this->routingDecisions,
            'warnings' => $this->warnings,
            'assertion_result' => $this->assertionResult?->toArray(),
            'verdict_summary' => $this->verdictSummary?->toArray(),
        ];
    }
}
