<?php

declare(strict_types=1);

// This file is auto-generated by oagen. Do not edit.

namespace Retab\Resource;

/** Public workflow version resource without tenant fields. */
readonly class WorkflowGraphVersion implements \JsonSerializable
{
    use JsonSerializableTrait;

    public function __construct(
        /** Public content-addressed workflow version ID */
        public string $id,
        public string $workflowId,
        public \DateTimeImmutable $createdAt,
        /** @var array<\Retab\Resource\WorkflowConfigBlock>|null */
        public ?array $blocks = null,
        /** @var array<\Retab\Resource\WorkflowConfigEdge>|null */
        public ?array $edges = null,
        /** @var array<string>|null */
        public ?array $blockVersionIds = null,
        /** @var array<string>|null */
        public ?array $edgeVersionIds = null,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        foreach ([
            'id',
            'workflow_id',
            'created_at',
        ] as $__required) {
            if (!array_key_exists($__required, $data)) {
                throw new \UnexpectedValueException("Missing required field '$__required' for WorkflowGraphVersion::fromArray()");
            }
        }
        return new self(
            id: $data['id'],
            workflowId: $data['workflow_id'],
            createdAt: new \DateTimeImmutable($data['created_at']),
            blocks: isset($data['blocks']) ? array_map(fn ($item) => WorkflowConfigBlock::fromArray($item), $data['blocks']) : null,
            edges: isset($data['edges']) ? array_map(fn ($item) => WorkflowConfigEdge::fromArray($item), $data['edges']) : null,
            blockVersionIds: $data['block_version_ids'] ?? null,
            edgeVersionIds: $data['edge_version_ids'] ?? null,
        );
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'workflow_id' => $this->workflowId,
            'created_at' => $this->createdAt->format(\DateTimeInterface::RFC3339_EXTENDED),
            'blocks' => $this->blocks !== null ? array_map(fn ($item) => $item->toArray(), $this->blocks) : null,
            'edges' => $this->edges !== null ? array_map(fn ($item) => $item->toArray(), $this->edges) : null,
            'block_version_ids' => $this->blockVersionIds,
            'edge_version_ids' => $this->edgeVersionIds,
        ];
    }
}
