// This file is auto-generated by the Retab oagen emitter. Do not edit by hand.

import { z } from 'zod';
export interface DeclarativePlanSummary {
  /** @default 0 */
  add?: number;
  /** @default 0 */
  change?: number;
  /** @default 0 */
  destroy?: number;
  /** @default 0 */
  replace?: number;
  /** @default 0 */
  noop?: number;
  /** @default 0 */
  total?: number;
  /** @default false */
  hasChanges?: boolean;
}

export interface DeclarativePlanSummaryResponse {
  add?: number;
  change?: number;
  destroy?: number;
  replace?: number;
  noop?: number;
  total?: number;
  has_changes?: boolean;
}

export const ZDeclarativePlanSummary = z.object({
  add: z.number().int().optional(),
  change: z.number().int().optional(),
  destroy: z.number().int().optional(),
  replace: z.number().int().optional(),
  noop: z.number().int().optional(),
  total: z.number().int().optional(),
  hasChanges: z.boolean().optional(),
}) as z.ZodType<DeclarativePlanSummary>;

export function deserializeDeclarativePlanSummary(
  wire: DeclarativePlanSummaryResponse
): DeclarativePlanSummary {
  return {
    add: wire['add'],
    change: wire['change'],
    destroy: wire['destroy'],
    replace: wire['replace'],
    noop: wire['noop'],
    total: wire['total'],
    hasChanges: wire['has_changes'],
  };
}
